{
  "hash": "9853496129c91cefeaa335186b41f9fe",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"2. Singular Value Decomposition\"\nauthor: \"Lieven Clement\"\ndate: \"statOmics, Ghent University (https://statomics.github.io)\"\nformat:\n  html: default\n  pdf: default\n---\n\n\n\n\n# Introduction\n\n## Motivation\n\nThe SVD is one of the most well used and general purpose tools from linear algebra for data processing!\n\nMethodologically\n\n- Dimension reduction (e.g. images, gene expression data, movie preferences)\n- Used as a first step in many data reduction and machine learning approaches\n- Taylor a coordinate system driven by the data\n- Solve system of linear equations for non-square matrices: e.g. linear regression\n- Basis for principal component analysis (PCA) and multidimensional scaling (MDS).\n  - PCA is one of the most widely used methods to study high dimensional data and to understand them in terms of their  dominant patterns and correlations\n\nApplications:\n\n- At the heart of search engines: Google\n- Basis of many facial recognition methods: e.g. Facebook\n- Recommender systems such as Amazon and Netflix\n- A standard tool for data exploration and dimension reduction in Genomics\n\n## Disclaimer\n\nWhen you want to run the script you will have to comment out the eval=FALSE statement in some R chunks. Because the SVD takes a while on the faces example we save the svd for later use. So you have to comment the eval=FALSE statement in this chunk when you run the script for the first time.\n\n## Data\n\n- Extended Yale Face Database B\n- Cropped and aligned images of 38 individuals under 64 lighting conditions.\n- Each image is 192 pixels tall and 168 pixels wide.\n- Each of the facial images in our library will be reshaped into a large vector with 192 × 168 = 32 256 elements.\n- We will use the 64 images of 36 people to build our models\n\n\n::: {.cell silent='true'}\n\n```{.r .cell-code}\nlibrary(pixmap)\nlibrary(tidyverse)\nlibrary(gridExtra)\nlibrary(grid)\nlibrary(ggmap)\nlibrary(downloader)\nlibrary(imager)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Download and unzip data\nif(!dir.exists(\"raw-data\")) dir.create(\"raw-data\")\ndownload(\n  \"https://github.com/statOmics/HDA2020/raw/data/yalefaces_cropped.zip\",\n  destfile = \"raw-data/yalefaces_cropped.zip\", mode = \"wb\", quiet = TRUE\n)\nunzip (\"raw-data/yalefaces_cropped.zip\", exdir = \"./raw-data\")\n\ndir <- \"./raw-data/CroppedYale\"\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npeople <- list.files(dir)\npeople2 <- sapply(people,\n  function(x) list.files(\n    paste0(dir,\"/\",x),\n    full.names=TRUE\n    )\n  )\n\nfacesList <- lapply(people2, function(x) read.pnm(x))\n\n grid.arrange(\n  grobs=lapply(facesList[1+(0:35)*64],\n     function(x) getChannels(x) |>\n        ggimage(coord_equal=TRUE)\n        ),\n  ncol=6)\n```\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-2-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n## Method\n\nLet $\\mathbf{X}$ be an $n\\times p$ matrix e.g.\n\n- gene expression of $p=40 000$ genes for $n=30$ subjects\n- n = 100 000 000 webpages indexed with p search terms, or\n- $n$ images each stored as a $p=32 256$ vector with the intensity of each pixel\n\n<!-- Need \"emo\" package for emojis, install with -->\n<!-- `devtools::install_github(\"hadley/emo\")` -->\n\n__Note:__ the emoji characters will not be visible in the PDF output.\n\n\\[X=\n\\left[\\begin{array}{ccc}\n-&\\mathbf{x}_{1}^T &- \\\\\n\\vdots&\\vdots&\\vdots\\\\\n-&\\mathbf{x}_{i}^T &- \\\\\n\\vdots&\\vdots&\\vdots\\\\\n-&\\mathbf{x}_{n}^T &- \\\\\n\\end{array}\\right]_{n \\times p}\n\\begin{array}{c}\n💇\\\\\\\\\n👮\\\\\n\\\\\n👸\\\\\n\\end{array}\n\\]\n\nThe data matrix  $\\mathbf{X}$ can be decomposed with the SVD into 3 matrices:\n\n\\[\n\\mathbf{X}=\\mathbf{U}_{n\\times n}\\boldsymbol{\\Delta}_{n\\times p}\\mathbf{V}^T_{p \\times p}\n\\]\n\n- an orthonormal matrix $\\mathbf{U}_{n\\times n}$ with left singular vectors: $\\mathbf{u}_j^T \\mathbf{u}_k=1$ if $k=j$ and $\\mathbf{u}_j^T \\mathbf{u}_k=0$ if $j\\neq k$, i.e.\n\\[ \\mathbf{U}^T\\mathbf{U}=\\mathbf{I}\\]\n\n- a matrix $\\boldsymbol{\\Delta}_{n\\times p}$ with only singular values: the singular values $\\delta_i$ are the only non-zero elements of the matrix and are on the diagonal element $[\\boldsymbol{\\Delta}]_{ii}$. They are also organised so that $\\delta_1 > \\delta_2 > \\ldots > \\delta_r$.\n\n- an orthonormal matrix $\\mathbf{V}_{p\\times p}$ with right singular vectors: $\\mathbf{v}_j^T \\mathbf{v}_k=1$ if $k=j$ and $\\mathbf{v}_j^T \\mathbf{v}_k=0$ if $j\\neq k$ otherwise, i.e.\n\\[ \\mathbf{V}^T\\mathbf{V}=\\mathbf{I}\\]\n\n\nNote, that there are only $r$ non-zero singular values, with $r$ the rank of matrix $X$: $r \\leq \\text{min}(n,p)$. So we have $k=1 \\ldots r$ non-zero singular values. Hence, we can also rewrite the approximation by restricting us to the rank of matrix $\\mathbf{X}$. Indeed, the n times p matrix $\\boldsymbol\\Delta$ only contains $r$ non-zero diagonal elements!\n\n- So\n\\[\n\\mathbf{X}=\\mathbf{U}_{n\\times r}\\boldsymbol{\\Delta}_{r\\times r}\\mathbf{V}^T_{p \\times r}\n\\]\n\n\n\\[\n\\left[\\begin{array}{ccc}\n-&\\mathbf{x}_{1}^T &- \\\\\n\\vdots&\\vdots&\\vdots\\\\\n-&\\mathbf{x}_{i}^T &- \\\\\n\\vdots&\\vdots&\\vdots\\\\\n-&\\mathbf{x}_{n}^T &- \\\\\n\\end{array}\\right]_{n \\times p}\n=\n\\left[\\begin{array}{ccc}\n\\mid&&\\mid\\\\\n\\mathbf{u}_1&\\ldots&\\mathbf{u}_r\\\\\n\\mid&&\\mid\n\\end{array}\\right]_{n \\times r}\n\\left[\\begin{array}{ccc}\n\\delta_1\\\\\n&\\ddots&\\\\\n&&\\delta_r\\\\\n\\end{array}\\right]_{r \\times r}\n\\left[\\begin{array}{ccc}\n\\mid&&\\mid\\\\\n\\mathbf{v}_1&\\ldots&\\mathbf{v}_r\\\\\n\\mid&&\\mid\\\\\n\\end{array}\n\\right]^T_{p \\times r}\n\\]\n\nAlso note that\n\\[\n\\mathbf{V}^T=\\left[\\begin{array}{ccc}\n-&\\mathbf{v}_{1}^T &- \\\\\n\\vdots&\\vdots&\\vdots\\\\\n-&\\mathbf{v}_{r}^T &- \\\\\n\\end{array}\\right]_{r \\times p}\n\\]\n\n\n- For high dimensional data $p>>>n$ $\\rightarrow$ $\\text{max}(r)=n$ and\n\n- equivalently for multivariate data with $n>p$ $\\rightarrow$ $\\text{max}(r)=p$\n\n\nWe can also rewrite the decomposition using the properties of matrix multiplication\n\n\\begin{eqnarray}\n\\mathbf{X} &=& \\delta_1\\left[\n\\begin{array}{c}\n\\mid\\\\\n\\mathbf{u}_1\\\\\n\\mid\n\\end{array}\n\\right]\n\\begin{array}{c}\n\\left[\n\\begin{array}{ccc}\n-&\n\\mathbf{v}_1^T&\n-\n\\end{array}\n\\right]\\\\\\quad\\\\\\quad\n\\end{array}\n+ \\ldots +\n\\delta_r\\left[\n\\begin{array}{c}\n\\mid\\\\\n\\mathbf{u}_r\\\\\n\\mid\n\\end{array}\n\\right]\n\\begin{array}{c}\n\\left[\n\\begin{array}{ccc}\n-&\n\\mathbf{v}_r^T&\n-\n\\end{array}\n\\right]\\\\\\quad\\\\\\quad\n\\end{array}\\\\\n\\mathbf{X} &=& \\sum_{k=1}^r \\delta_k\\mathbf{u}_k\\mathbf{v}_k^T\n\\end{eqnarray}\n\n- Because both $\\mathbf{U}$ and $\\mathbf{V}$ are orthonormal all their $r$ vectors are having unit length and they are thus reshaped by the singular values.\n\n- Hence, the singular values determine the importance of the rank one matrices $\\delta_k\\mathbf{u}_k\\mathbf{v}_k^T$ in the reconstruction of the matrix $\\mathbf{X}$ and they are ordered so that $\\delta_1 > \\ldots > \\delta_r$.\n\nNote, that for symmetric positive semi-definite matrices $\\mathbf{X}$ $\\longrightarrow$ $\\mathbf{U} = \\mathbf{V}$.\n\n## Interpretation of singular vectors: face example\n\n### Convert images to vectors\n1. Convert images to vectors and store them as a matrix\n    - We use an `sapply` loop to loop over all faces\n    - We extract the grey intensities from the pictures\n    - We convert the matrix in a long skinny vector (`c`)\n    - We transpose the resulting matrix from sapply\n\n::: {.cell}\n\n```{.r .cell-code}\nallFacesMx <- sapply(facesList,\n                     function(x)\n                        getChannels(x) |> c()\n                     ) |> t()\ndim(allFacesMx)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1]  2432 32256\n```\n\n\n:::\n:::\n\n\nSave memory by removing facesList object\n```\nrm(facesList)\ngc()\n```\n\nHence we obtain a matrix for n = 2432 images with p = 32256 intensities for each pixel of an image.\n\nBefore we do the svd we typically center the data by subtracting the average of the columns, i.e. the average face.\n\nWe will only work with the first 36 people: $n = 36 \\times 64 = 2304$ pictures.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nallFacesCenteredMx <- allFacesMx[1:(36*64),]\nmeanFace <- colMeans(allFacesCenteredMx)\n\nallFacesMxCentered <- allFacesCenteredMx -\n  matrix(1, nrow=nrow(allFacesCenteredMx), ncol=1) %*% matrix(meanFace,nrow=1)\n```\n:::\n\n\n### Visualisation of mean image\n\n::: {.cell}\n\n```{.r .cell-code}\nplotFaceVector <- function(faceVector,nrow=192,ncol=168) {\n  matrix(faceVector,nrow=nrow,ncol=ncol) |>\n  ggimage()\n}\n\nmeanFace |>\n  plotFaceVector()\n```\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-5-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n### SVD\n\n#### Perform SVD in R\n\n1. We adopt svd on the centered matrix\n2. We cache the result because the calculation takes 10 minutes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfaceSvd <- svd(allFacesMxCentered)\n```\n:::\n\n\n<!-- ```{r, eval=FALSE} -->\n<!-- ## Run this code manually to store the SVD for later re-use -->\n<!-- saveRDS(faceSvd, file = \"faceSvd.rds\") -->\n<!-- ``` -->\n\n<!-- ```{r, eval=FALSE} -->\n<!-- ## Run this code manually to reload the SVD result -->\n<!-- faceSvd <- readRDS(\"faceSvd.rds\") -->\n<!-- ``` -->\n\n\n\n#### SVD\n\nDimensions of $\\mathbf{U}$, $\\mathbf{V}$?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- nrow(allFacesCenteredMx)\np <- ncol(allFacesCenteredMx)\ndim(faceSvd$u)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 2304 2304\n```\n\n\n:::\n\n```{.r .cell-code}\ndim(faceSvd$v)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 32256  2304\n```\n\n\n:::\n:::\n\n\nIndeed, for the face example $n<p$ so $r=n$\n\nCheck orthogonality?\n\nWe do not do it for all vectors because it takes too long.\nFirst left singular vector and second left singular vector.\nHappens in $\\mathbf{U}^T\\mathbf{U}$\n\n::: {.cell}\n\n```{.r .cell-code}\nt(faceSvd$u[,1])%*%faceSvd$u[,1]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>      [,1]\n#> [1,]    1\n```\n\n\n:::\n\n```{.r .cell-code}\nt(faceSvd$u[,1])%*%faceSvd$u[,2]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>              [,1]\n#> [1,] 4.830461e-17\n```\n\n\n:::\n\n```{.r .cell-code}\nt(faceSvd$u[,2])%*%faceSvd$u[,2]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>      [,1]\n#> [1,]    1\n```\n\n\n:::\n:::\n\nSo we see that the left singular vectors are orthonormal.\n\nWe check if it also holds for the rows i.e. $\\mathbf{U}\\mathbf{U}^T$\n\n::: {.cell}\n\n```{.r .cell-code}\nt(faceSvd$u[1,])%*%faceSvd$u[1,]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>      [,1]\n#> [1,]    1\n```\n\n\n:::\n\n```{.r .cell-code}\nt(faceSvd$u[2,])%*%faceSvd$u[1,]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>              [,1]\n#> [1,] 4.955286e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nt(faceSvd$u[2,])%*%faceSvd$u[2,]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>      [,1]\n#> [1,]    1\n```\n\n\n:::\n:::\n\nWe also see that the rows of $\\mathbf{U}$ are orthonormal.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt(faceSvd$v[,1])%*%faceSvd$v[,1]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>      [,1]\n#> [1,]    1\n```\n\n\n:::\n\n```{.r .cell-code}\nt(faceSvd$v[,1])%*%faceSvd$v[,2]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>               [,1]\n#> [1,] -6.150696e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nt(faceSvd$v[,2])%*%faceSvd$v[,2]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>      [,1]\n#> [1,]    1\n```\n\n\n:::\n:::\n\nSo we see that the right singular vectors are orthonormal.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt(faceSvd$v[1,])%*%faceSvd$v[1,]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>           [,1]\n#> [1,] 0.1493919\n```\n\n\n:::\n\n```{.r .cell-code}\nt(faceSvd$v[1,])%*%faceSvd$v[2,]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>            [,1]\n#> [1,] 0.08950106\n```\n\n\n:::\n\n```{.r .cell-code}\nt(faceSvd$v[2,])%*%faceSvd$v[2,]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>           [,1]\n#> [1,] 0.1017501\n```\n\n\n:::\n:::\n\n\nThis, however does not hold for the rows of $\\mathbf{V}$.\nThis is because the matrix $\\mathbf{V}$ no longer is a square matrix! $r=n$ and $r<p$!\n\n#### Visualize right singular vectors $\\mathbf{V}$\n\n::: {.cell}\n\n```{.r .cell-code}\ngrid.arrange(\n grobs=apply(\n   faceSvd$v[,1:36],\n   2,\n   plotFaceVector\n   )\n )\n```\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-11-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n- Hence, the right singular vectors (in $\\mathbf{V}$ of $\\mathbf{X}=\\mathbf{U}\\boldsymbol{\\Delta}\\mathbf{V}$) are also faces and we can thus reconstruct the original faces by linear combinations of the singular faces.\n\n- The first singular faces are most important to capture overall patterns in the matrix.\n\n- Here it are mainly characteristics and shadows that are important for all faces.\n\n- From singular face 5 onwards we start to see specific features.\n\n- In this case: $n < p$, so $r = n$.\n\n\\[\n\\mathbf{X}_{n\\times p}=\\mathbf{U}_{n \\times n}\\boldsymbol{\\Delta}_{n\\times n}\\mathbf{V}_{p\\times n}^T\n\\]\n\n\\[\n\\begin{array}{ccccc}\n\\left[\\begin{array}{ccc}\n-&\\mathbf{x}_{1}^T &- \\\\\n\\vdots&\\vdots&\\vdots\\\\\n-&\\mathbf{x}_{i}^T &- \\\\\n\\vdots&\\vdots&\\vdots\\\\\n-&\\mathbf{x}_{n}^T &- \\\\\n\\end{array}\\right]_{n \\times p}\n\\begin{array}{c}\n💇\\\\\\\\\n👮\\\\\n\\\\\n👸\\\\\n\\end{array}\n&=&\n\\begin{array}{c}\n\\quad\\\\\n\\left[\\begin{array}{ccc}\n\\mid&&\\mid\\\\\n\\mathbf{u}_1&\\ldots&\\mathbf{u}_n\\\\\n\\mid&&\\mid\n\\end{array}\\right]_{n \\times n}\\\\\n\\quad \\\\\n\\end{array}\n\\begin{array}{c}\n\\quad\\\\\n\\left[\\begin{array}{ccc}\n\\delta_1\\\\\n&\\ddots&\\\\\n&&\\delta_n\\\\\n\\end{array}\\right]_{n \\times n}\\\\\n\\quad\\\\\n\\end{array}\n\\begin{array}{c}\n\\quad\n\\left[\\begin{array}{ccc}\n\\mid&&\\mid\\\\\n\\mathbf{v}_1&\\ldots&\\mathbf{v}_n\\\\\n\\mid&&\\mid\\\\\n\\end{array}\n\\right]^T_{p \\times n}\\\\\n\\begin{array}{ccc}\n😨&\\quad&😐\n\\end{array}\n\\end{array}\n\\end{array}\n\\]\n\n- Or upon transposing the matrix $\\mathbf{V}$\n\n\\[\n\\begin{array}{ccccc}\n\\left[\\begin{array}{ccc}\n-&\\mathbf{x}_{1}^T &- \\\\\n\\vdots&\\vdots&\\vdots\\\\\n-&\\mathbf{x}_{i}^T &- \\\\\n\\vdots&\\vdots&\\vdots\\\\\n-&\\mathbf{x}_{n}^T &- \\\\\n\\end{array}\\right]_{n \\times p}\n\\begin{array}{c}\n💇\\\\\\\\\n👮\\\\\n\\\\\n👸\\\\\n\\end{array}\n&=&\n\\left[\\begin{array}{ccc}\n\\mid&&\\mid\\\\\n\\mathbf{u}_1&\\ldots&\\mathbf{u}_n\\\\\n\\mid&&\\mid\n\\end{array}\\right]_{n \\times n}\n\\left[\\begin{array}{ccc}\n\\delta_1\\\\\n&\\ddots&\\\\\n&&\\delta_r\\\\\n\\end{array}\\right]_{n \\times n}\n\\left[\\begin{array}{ccc}\n-&\\mathbf{v}_{1}^T &- \\\\\n\\vdots&\\vdots&\\vdots\\\\\n-&\\mathbf{v}_{p}^T &- \\\\\n\\end{array}\\right]_{n \\times p}\n\\begin{array}{c}\n😨\\\\\n\\\\\n😐\n\\end{array}\n\\end{array}\n\\]\n\n#### Reconstruction of faces via linear combination of singular faces.\n\nIn left singular vectors $u_{ij}$ we quantify the contribution of the $j^\\text{th}$ singular face in the reconstruction of face $i$ and we rescale the importance of each singular face by its corresponding singular value $\\delta_j$.\n\n\\[\n\\left[\\begin{array}{ccc}\n-&\\mathbf{x}_{1}^T &- \\\\\n\\vdots&\\vdots&\\vdots\\\\\n-&\\mathbf{x}_{i}^T &- \\\\\n\\vdots&\\vdots&\\vdots\\\\\n-&\\mathbf{x}_{n}^T &- \\\\\n\\end{array}\\right]_{n \\times p}\n\\begin{array}{c}\n💇\\\\\\\\\n👮\\\\\n\\\\\n👸\\\\\n\\end{array} =\n\\delta_1\\left[\n\\begin{array}{c}\n\\mid\\\\\n\\mathbf{u}_1\\\\\n\\mid\n\\end{array}\n\\right]\n\\begin{array}{c}\n\\left[\n\\begin{array}{ccc}\n-&\n\\mathbf{v}_1^T&\n-\n\\end{array}\n\\right]\\\\\\quad\\\\\\quad\n\\end{array}\n\\begin{array}{c}\n😨\n\\\\\\quad\\\\\\quad\n\\end{array}\n+ \\ldots +\n\\delta_r\\left[\n\\begin{array}{c}\n\\mid\\\\\n\\mathbf{u}_r\\\\\n\\mid\n\\end{array}\n\\right]\n\\begin{array}{c}\n\\left[\n\\begin{array}{ccc}\n-&\n\\mathbf{v}_r^T&\n-\n\\end{array}\n\\right]\\\\\\quad\\\\\\quad\n\\end{array}\n\\begin{array}{c}\n😐\n\\\\\\quad\\\\\\quad\n\\end{array}\n\\]\n\nIf we truncate the singular faces say at $k<r$ we can approximate faces using a limited number of singular faces!\n\n\n::: {.cell}\n\n```{.r .cell-code}\napproximateFace <- function(meanFace,faceSvd,k){\n  reconstruct <- (meanFace + faceSvd$u[1,1:k] %*%\n    diag(faceSvd$d[1:k]) %*%\n  t(faceSvd$v[,1:k]) |>\n  c())\n}\n\napproxHlp <- sapply(\n      c(25,100,500),\n      approximateFace,\n      meanFace=meanFace,\n      faceSvd=faceSvd)\n\ngrid.arrange(\n grobs=apply(\n   cbind(\n     approxHlp,\n     allFacesMxCentered[1,]+meanFace\n   ),\n   2,\n   plotFaceVector\n   )\n )\n```\n\n::: {.cell-output-display}\n![approximation with 25 (top left),  100 (top right) and 500 (bottom left) singular faces and original face (bottom right, or with all singular faces)](svd_files/figure-pdf/unnamed-chunk-12-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n# SVD as a Matrix Approximation Method\n\n- We have seen that we can use the truncated SVD to approximate matrix $\\mathbf{X}$ by $\\tilde{\\mathbf{X}}$, with $k<r$ and\n\\[\n\\tilde{\\mathbf{X}}=\\mathbf{U}_{n\\times k}\\boldsymbol{\\Delta}_{k\\times k}\\mathbf{V}_{p \\times k}^T\n\\]\n- It can be shown that **SVD: optimal approximation**\n\n  - Let $\\mathbf{X}$ be an $n\\times p$ matrix of rank $r\\leq \\min(n,p)$, and let $\\mathbf{A}$ denote an $n \\times p$ matrix of rank $k\\leq r$, with elements denoted by $a_{ij}$.\n\n  - The matrix $\\mathbf{A}$ of rank $k\\leq r$ that minimises the Frobenius norm\n  \\[\n    \\vert\\vert\\mathbf{X}-\\mathbf{A}\\vert\\vert^2_\\text{fr}=\\sum_{i=1}^n\\sum_{j=1}^p (x_{ij}-a_{ij})^2\n  \\]\n  is given by the truncated SVD\n  \\[\n     \\mathbf{X}_k = \\sum_{j=1}^k \\delta_j \\mathbf{u}_j\\mathbf{v}_j^T.\n  \\]\n\n  - The truncated SVD has $k < r$ terms. Hence, generally $\\mathbf{X}_k$ does not coincide with $\\mathbf{X}$. It is considered as an approximation.\n\n  - Note, that the truncated SVD thus approximates the matrix by minimising a kind of sum of least squared errors between the elements of matrix $\\mathbf{X}$ and $\\mathbf{A}$ and that\n\n  - the truncated SVD $\\mathbf{X}_k$ is the best rank-k approximation of $\\mathbf{X}$ in terms of this\nFrobenius norm.\n\n  - Also, note that upon truncation\n  \\[\\mathbf{V}^T_{p\\times k} \\mathbf{V}_{p\\times k} = \\mathbf{I}_{k\\times k}\\]\n  \\[\\mathbf{U}^T_{n\\times k} \\mathbf{U}_{n\\times k} = \\mathbf{I}_{k\\times k}\\]\n\n  - But, that\n\\[\\mathbf{V}_{p\\times k} \\mathbf{V}_{p\\times k}^T \\neq \\mathbf{I}_{p\\times p}!!!\\]\n\\[\\mathbf{U}_{n\\times k} \\mathbf{U}_{n\\times k}^T \\neq \\mathbf{I}_{n\\times n}!!!\\]\n\n---\n\n\nSome **informal statement** about the truncated SVD\n  \\[\n     \\mathbf{X}_k = \\sum_{j=1}^k \\delta_j \\mathbf{u}_j\\mathbf{v}_j^T.\n  \\]\n\n - It can be considered as a weighted sum of matrices $\\mathbf{u}_j\\mathbf{v}_j^T$, with weights $\\delta_j$.\n\n\n - The terms are ordered with decreasing weights $\\delta_1\\geq \\delta_2 \\geq \\cdots \\geq \\delta_k >0$.\n\n\n - The matrices $\\mathbf{u}_j\\mathbf{v}_j^T$ are of equal \"magnitude\" (constructed from normalised vectors).\n\n - Truncation at $k$ results in $k$ $\\delta_j$'s, $k\\times n$ elements in the $\\mathbf{u}_j$ and $k \\times p$ elements in the $\\mathbf{v}_j$. Hence a total of $k+kn+kp=k(1+n+p)$ elements (usually much smaller than $np$). (Note that restrictions apply to $\\mathbf{u}_j$ and $\\mathbf{v}_j$; hence even less independent elements).\n\n $\\longrightarrow$ **data compression**\n\n## Example 1: Image compression\n\n### Painting Mondriaan: Composition_No.III with red, blue, yellow and black (1929).\n\n- Have a look at this painting of Mondriaan (1872 -- 1944), here shown in black-and-white.\n\n#### Load the original painting\n\n1. fetch image from the web\n2. convert into greyscale\n3. plot\n4. save as Matrix\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmondriaan <- load.image(\"https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Piet_Mondrian_-_Composition_No._III%2C_with_red%2C_blue%2C_yellow_and_black%2C_1929.jpg/1920px-Piet_Mondrian_-_Composition_No._III%2C_with_red%2C_blue%2C_yellow_and_black%2C_1929.jpg\")\nmondriaan <- grayscale(mondriaan)\nplot(mondriaan,axes=FALSE)\n```\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-13-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nX <- matrix(as.data.frame(mondriaan)[,3],nrow=nrow(mondriaan),ncol=ncol(mondriaan))\n```\n:::\n\n\n- This picture can be represented as a $1920 \\times 1913$ matrix $\\mathbf{X}$ with gray scale intensities $\\in [0,1]$. ($\\approx 4\\times 10^6$ data entries)\n\n- We will here not transform the image in a vector, but will look at the performance of the SVD to compress this image. The SVD can be applied to any matrix!\n\n\n#### Singular values\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonSvd <- svd(X)\n\np1 <- data.frame(x=1:length(monSvd$d),y=monSvd$d) |>\n  ggplot(aes(x=x,y=y)) +\n  geom_point() +\n  xlab(\"k\") +\n  ylab(\"singular value\")\n\np2 <- data.frame(x=1:10,y=monSvd$d[1:10]) |>\n  ggplot(aes(x=x,y=y)) +\n  geom_point() +\n  xlab(\"k\") +\n  ylab(\"singular value\")\n\ngrid.arrange(p1,p2,nrow=1)\n```\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-14-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n- The singular values decay very quickly!\n\n#### Data compression\n\n- We make the plot for a reconstruction with 1 singular vector. This leads to a data compression of $1-\\frac{(1+1920+1913)}{1920\\times 1913}$ = 99.9%. We only use 1 left singular vector (1920), 1 singular value, 1 right singular vector (1913).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk <- 1\napproxMon <- monSvd$u[,1:k] %*%\n  diag(monSvd$d[1:k],ncol=k) %*%\n  t(monSvd$v[,1:k])\n\napproxMon[approxMon < 0] <- 0\napproxMon[approxMon > 1] <- 1\n\nas.cimg(approxMon) |>\n  plot(main=paste0(\"Approximation with \",k,\" singular vectors\"),axes=FALSE)\n```\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-15-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n- We make the plot for a reconstruction with 2 singular vector. This leads to a data compression of $1-\\frac{2\\times (1+1920+1913)}{1920\\times 1913}$ = 99.8%. We only use 2 left singular vectors\n(2 $\\times$ 1920), 2 singular values, 2 right singular vectors (2 $\\times$ 1913).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk <- 2\napproxMon <- monSvd$u[,1:k] %*%\n  diag(monSvd$d[1:k],ncol=k) %*%\n  t(monSvd$v[,1:k])\n\napproxMon[approxMon < 0] <- 0\napproxMon[approxMon > 1] <- 1\n\nas.cimg(approxMon) |>\n  plot(main=paste0(\"Approximation with \",k,\" singular vectors\"),axes=FALSE)\n```\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-16-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar (mfrow=c(3,3))\npar(mar=c(1,2,1,1))\nfor (k in c(1:8))\n{\napproxMon <- monSvd$u[,1:k] %*%\n  diag(monSvd$d[1:k],ncol=k) %*%\n  t(monSvd$v[,1:k])\n\n\napproxMon[approxMon < 0] <- 0\napproxMon[approxMon > 1] <- 1\n\n\napproxMon |>\n  as.cimg() |>\n  plot(main=paste0(k,\" singular vectors\"),axes=FALSE)\n}\nplot(as.cimg(X),main=paste0(\"Original image\"),axes=FALSE)\n```\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-17-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n### More complex painting: Composition A, Piet Mondriaan\n\n#### Load the original painting\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmondriaan <- load.image(\"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Composition_A_by_Piet_Mondrian_Galleria_Nazionale_d%27Arte_Moderna_e_Contemporanea.jpg/1920px-Composition_A_by_Piet_Mondrian_Galleria_Nazionale_d%27Arte_Moderna_e_Contemporanea.jpg\")\nmondriaan <- grayscale(mondriaan)\nplot(mondriaan,axes=FALSE)\n```\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-18-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nX <- matrix(as.data.frame(mondriaan)[,3],nrow=dim(mondriaan)[1],ncol=dim(mondriaan)[2])\n```\n:::\n\n\n\n#### Singular values\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonSvd <- svd(X)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- data.frame(x=1:length(monSvd$d),y=monSvd$d) |>\n  ggplot(aes(x=x,y=y)) +\n  geom_point() +\n  xlab(\"k\") +\n  ylab(\"singular value\")\n\np2 <- data.frame(x=1:10,y=monSvd$d[1:10]) |>\n  ggplot(aes(x=x,y=y)) +\n  geom_point() +\n  xlab(\"k\") +\n  ylab(\"singular value\")\n\ngrid.arrange(p1,p2,nrow=1)\n```\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-20-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n- The singular values decay a bit slower. The painting is a bit more complex. More lines and colors.\n\n#### Evaluate data compression\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar (mfrow=c(3,3))\npar(mar=c(1,2,1,1))\nfor (k in c(1,seq(3,21,3)))\n{\napproxMon <- monSvd$u[,1:k] %*%\n  diag(monSvd$d[1:k],ncol=k) %*%\n  t(monSvd$v[,1:k])\n\n\napproxMon[approxMon < 0] <- 0\napproxMon[approxMon > 1] <- 1\n\n\napproxMon |>\n  as.cimg() |>\n  plot(main=paste0(k,\" singular vectors\"),axes=FALSE)\n}\nplot(as.cimg(X),main=paste0(\"Original image\"),axes=FALSE)\n```\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-21-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n### Self portrait Piet Mondriaan\n\n#### Load the painting\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmondriaan <- load.image(\"https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Mondrian_Zelfportret.jpg/1920px-Mondrian_Zelfportret.jpg\")\nmondriaan <- grayscale(mondriaan)\nplot(mondriaan,axes=FALSE)\n```\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-22-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nX <- matrix(as.data.frame(mondriaan)[,3],nrow=dim(mondriaan)[1],ncol=dim(mondriaan)[2])\n```\n:::\n\n\n#### Singular values\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonSvd <- svd(X)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- data.frame(x=1:length(monSvd$d),y=monSvd$d) |>\n  ggplot(aes(x=x,y=y)) +\n  geom_point() +\n  xlab(\"k\") +\n  ylab(\"singular value\")\n\np2 <- data.frame(x=1:10,y=monSvd$d[1:10]) |>\n  ggplot(aes(x=x,y=y)) +\n  geom_point() +\n  xlab(\"k\") +\n  ylab(\"singular value\")\n\ngrid.arrange(p1,p2,nrow=1)\n```\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-24-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n- The singular values decay much slower. The painting is more complex.\n\n#### Evaluate compression\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar (mfrow=c(3,3))\npar(mar=c(1,2,1,1))\nfor (k in c(1,5,10,20,30,40,50,100))\n{\napproxMon <- monSvd$u[,1:k] %*%\n  diag(monSvd$d[1:k],ncol=k) %*%\n  t(monSvd$v[,1:k])\n\n\napproxMon[approxMon < 0] <- 0\napproxMon[approxMon > 1] <- 1\n\n\napproxMon |>\n  as.cimg() |>\n  plot(main=paste0(k,\" singular vectors\"),axes=FALSE)\n}\nplot(as.cimg(X),main=paste0(\"Original image\"),axes=FALSE)\n```\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-25-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\nHere we need at least 40 singular vector. This leads to a data compression of $1-\\frac{40\\times (1+1920+2494)}{1920 \\times 2494}$ = 96.3%. We only use 40 left singular vectors ($40 \\times 1920$), 40 singular values, 40 right singular vector ($40\\times 2494$).\n\n# Geometric interpretation\n\n<div style=\"position: relative;width: 100%;height: 0;padding-bottom: 56.25%;\">\n<iframe\nsrc=\"https://www.youtube.com/embed/srUDBwP9IW8\"\nstyle=\" position:absolute;top: 0;left: 0;width: 100%;height: 100%;\"\nframeborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>\n</div>\n\n</br>\n\nWe introduce the geometric interpretation of the svd by using a toy example.\n\n## Iris dataset\n\nThe iris dataset is a dataset on iris flowers.\n\n- Three species (setosa, virginica and versicolor)\n- Length and width of Sepal leafs\n- Length and width of Petal Leafs\n\nFor didactical purposes we will use a subset of the data.\n\n- Virginica Species\n- 3 Variables: Sepal Length, Sepal Width, Petal Length\n- This allows us to visualise the data in 3D plots\n- Illustrate the data compression of the SVD from 3 to two dimensions.\n\n### Subset the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(plotly)\nirisSub <- iris |>\n  filter(Species == \"virginica\") |>\n  dplyr::select(\"Sepal.Length\",\"Sepal.Width\",\"Petal.Length\")\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-27-1.pdf)\n:::\n:::\n\n\n### Center the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nX <- irisSub |> scale(scale=FALSE)\n```\n:::\n\n\nThe data is translated to a mean of [0, 0, 0].\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-29-1.pdf)\n:::\n:::\n\n\nWe zoom in and add the original axis in grey in the origin.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-30-1.pdf)\n:::\n:::\n\n\n## SVD iris dataset\n\n1. We adopt the SVD on the centered data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nirisSvd <- svd(X)\n```\n:::\n\n\n2. We extract\n\n  - the right singular vectors $\\mathbf{V}$ and\n  - the projections $\\mathbf{Z}$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nV <- irisSvd$v\nZ <- irisSvd$u %*% diag(irisSvd$d)\n```\n:::\n\n\nNote, that\n\n- the SVD is essentially a rotation to a new coordinate system.\n- we plotted $\\mathbf{V}_3$ with dots because we will use the SVD for dimension reduction \\[\\text{3D} \\rightarrow \\text{2D}\\]\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-33-1.pdf)\n:::\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-33-2.pdf)\n:::\n:::\n\n\nRotate the plot\n\n- Note, that\n\n  - V1 points in the direction of the largest variability in the data\n  - V2 points in a direction orthogonal on V1 pointing in the direction of the second largest variability in the data.\n\n## Truncated SVD\n\nWrite the **truncated SVD** as\n\\[\n  \\mathbf{X}_k = \\mathbf{U}_k \\boldsymbol{\\Delta}_k \\mathbf{V}_k^T = \\mathbf{Z}_k \\mathbf{V}_k^T\n\\]\nwith\n\\[\n  \\mathbf{Z}_k = \\mathbf{U}_k \\boldsymbol{\\Delta}_k\n\\]\nan $n \\times k$ matrix.\n\nEach of the $n$ rows of $\\mathbf{Z}_k$, say $\\mathbf{z}^T_{k,i}$, represents a point in a $k$-dimensional space.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nV2 <- V[,1:2]\nZ2 <- Z[,1:2]\nX2 <- Z2 %*% t(V2)\n```\n:::\n\n\nBecause of the orthonormality of the singular vectors, we also have\n\\begin{eqnarray*}\n  \\mathbf{X}_k\\mathbf{V}_k &=& \\mathbf{Z}_k \\mathbf{V}_k^T\\mathbf{V}_k \\\\\n  \\mathbf{X}_k\\mathbf{V}_k &=& \\mathbf{Z}_k.\n\\end{eqnarray*}\n\nThus the matrix $\\mathbf{V}_k$ is a **transformation matrix** that may be used to transform $\\mathbf{X}_k$ into $\\mathbf{Z}_k$, and $\\mathbf{Z}_k$ into $\\mathbf{X}_k$.\n\n---\n\nNote that\n\n- The matrix $\\mathbf{V}_k$ transforms the $p$-dimensional $\\mathbf{X}_k$ into the $k$-dimensional $\\mathbf{Z}_k$: $\\mathbf{Z}_k = \\mathbf{X}_k\\mathbf{V}_k$. Note, however, that the matrix $\\mathbf{X}_k$ must not necessarily be used for this transformation, because the SVD of the original matrix $\\mathbf{X}$ also gives directly $\\mathbf{Z}_k = \\mathbf{U}_k \\boldsymbol{\\Delta}_k$.\n\n- The inverse transformation from the  $k$-dimensional $\\mathbf{Z}_k$ to the $p$-dimensional $\\mathbf{X}_k$ is given by the transpose of $\\mathbf{V}_k$: $\\mathbf{Z}_k \\mathbf{V}_k^T=\\mathbf{X}_k$. Often inverse transformations are given by the inverse of a matrix, but thanks to the orthonormality of the columns of $\\mathbf{V}_k$, we get $\\mathbf{V}_k^T\\mathbf{V}_k=\\mathbf{I}$, and thus $\\mathbf{V}_k^T$ acts as an inverse.\n\n- The transformation from the  $k$-dimensional $\\mathbf{Z}_k$ to the $p$-dimensional $\\mathbf{X}_k$ is transforming points from a low dimensional space ($k$) to a high dimensional space ($p$). You may not interpret this as if this transformation adds information; the transformed points in $\\mathbf{X}_k$ still live in a $k$-dimensional subspace of the larger $p$-dimensional space; the matrix $\\mathbf{X}_k$ is only of rank $k$ and thus contains less information than the original data matrix $\\mathbf{X}$ (if rank($\\mathbf{X}$)$=r>k$).\n\n---\n\n\nMore importantly, it can be shown that (thanks to orthonormality of $\\mathbf{V}$)\n\\[\n    \\mathbf{X}\\mathbf{V}_k = \\mathbf{Z}_k.\n\\]\n\nThis follows from (w.l.g. rank($\\mathbf{X}$)=$r$)\n\n\\begin{eqnarray*}\n  \\mathbf{X}\\mathbf{V}_k\n      &=& \\mathbf{U}\\boldsymbol{\\Delta}\\mathbf{V}^T\\mathbf{V}_k = \\mathbf{U}\\boldsymbol{\\Delta}\\begin{pmatrix}\n              \\mathbf{v}_1^T \\\\\n        \\vdots \\\\\n        \\mathbf{v}_r^T\n              \\end{pmatrix}\n              \\begin{pmatrix}\n                \\mathbf{v}_1 \\ldots \\mathbf{v}_k\n              \\end{pmatrix} \\\\\n      &=& \\mathbf{U}\\boldsymbol{\\Delta}\\mathbf{V}^T\\mathbf{V}_k  = \\mathbf{U}\\boldsymbol{\\Delta}\\begin{pmatrix}\n              1 & 0 & \\ldots & 0 \\\\\n              0 & 1 & \\ldots & 0 \\\\\n              \\vdots & \\vdots & \\ddots & 0 \\\\\n              0 & 0 & \\ldots & 1 \\\\\n              0 & 0 & \\ldots & 0 \\\\\n              \\vdots & \\vdots & \\vdots & \\vdots \\\\\n              0 & 0 & \\ldots & 0\n              \\end{pmatrix} \\\\\n      &=& \\mathbf{U}_k\\boldsymbol{\\Delta}_k = \\mathbf{Z}_k\n\\end{eqnarray*}\n\nThe $p \\times k$ matrix $\\mathbf{V}_k$ acts as a transformation matrix: transforming $n$ points in a $p$ dimensional space to $n$ points in a $k$ dimensional space.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nZ2proj <- X %*% V2\nrange(Z2 - Z2proj)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] -1.332268e-15  1.110223e-15\n```\n\n\n:::\n:::\n\n\n\n## Projection of a single data point\n\n\nWe take a closer look at\n\\[\n  \\mathbf{Z}_k = \\mathbf{X}\\mathbf{V}_k = \\begin{pmatrix}\n   \\mathbf{x}_1^T \\\\\n   \\vdots \\\\\n   \\mathbf{x}_n^T\n  \\end{pmatrix} \\begin{pmatrix}\n   \\mathbf{v}_1 \\ldots \\mathbf{v}_k\n  \\end{pmatrix}.\n\\]\n\nThe $i$th row (observation) in $\\mathbf{Z}_k$ equals\n\\[\n \\mathbf{z}_{k,i}^T = \\mathbf{x}_i^T\\mathbf{V}_k = \\left(\\mathbf{x}_i^T \\mathbf{v}_1 , \\mathbf{x}_i^T \\mathbf{v}_2 , \\ldots , \\mathbf{x}_i^T \\mathbf{v}_k\\right).\n\\]\n\nHence, $\\mathbf{z}_{k,i}^T = \\mathbf{x}_i^T\\mathbf{V}_k$ is the orthogonal projection of $\\mathbf{x}_i$ onto the $k$-dimensional subspace spanned by the columns of $\\mathbf{V}_k$.\n\n\n- Zoom in to see projection.\n- The projection is indicated for the blue point $X_{44}$ to the red point $X_{2,44}$ in the plane spanned by V2.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-36-1.pdf)\n:::\n:::\n\n\n## Projection of all datapoints: project all rows of X on V2\n\n- Zoom in first look orthogonal via direction V2 (rotate until text V2 is viewed in the origin)\n- Zoom in first look orthogonal via direction V1 (rotate until text V1 is viewed in the origin)\n- Note, that\n  - V1 points in the direction of the largest variability in the data\n  - V2 points in a direction orthogonal on V1 pointing in the direction of the second largest variability in the data.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-37-1.pdf)\n:::\n:::\n\n\n- Projection only.\n- This clearly shows that the projected points X2 (X projected on V2) live in a two dimensional space\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-38-1.pdf)\n:::\n:::\n\n\nHence, the truncated SVD transforms the data set to a lower dimensional data set:\nThe SVD thus gives a transformation of the $p$ dimensional data to $k\\leq r$ dimensional data:\n\\[\n  \\mathbf{Z}_k = \\mathbf{X}\\mathbf{V}_k.\n\\]\nThis is essentially a dimension reduction.\n\n----\n\nNote that,\n\n- The transformation from $p$-dimensional $\\mathbf{X}$ to $k$-dimensional $\\mathbf{Z}_k$ is important. It shows that the $n$ points in the rows of $\\mathbf{Z}_k$ are the result of projecting the $n$ points in $\\mathbf{X}$ onto the columns of $\\mathbf{V}_k$ (i.e. the first $k$ singular vectors of $\\mathbf{X}$). We say that the space of $\\mathbf{Z}_k$ is spanned by the columns of $\\mathbf{V}_k$.\n\n- The points (rows) in $\\mathbf{X}$ live in a $p$-dimensional space (or rank($\\mathbf{X}$)$=r$ if $r<p$) and they are thus projected onto a lower dimensional space. This is in contrast to the projection $\\mathbf{X}_k\\mathbf{V}_k=\\mathbf{Z}_k$, because the points in $\\mathbf{X}_k$ live in a $k$-dimensional subspace of $\\mathbf{X}$.\n\n- Note that with $k<r$ there is no unique transformation to transform $\\mathbf{Z}_k$ back to $\\mathbf{X}$. On the previous slide we only established the transformation $\\mathbf{Z}_k \\mathbf{V}_k^T=\\mathbf{X}_k$. Indeed, starting from $\\mathbf{X}\\mathbf{V}_k = \\mathbf{Z}_k$, and right-multiplying with $\\mathbf{V}_k^T$ does not give the backtransformation, because $\\mathbf{V}_k\\mathbf{V}_k^T$ is not the identity matrix.\n\n\n# Interpretation of SVD in terms of  variance covariance matrices {#sec-SVDcov}\n\nFor a matrix $\\mathbf X$ the sample variance covariance matrix estimator is $p\\times p$ matrix\n\n\\begin{eqnarray}\n\\mathbf{S}&=&\\frac{1}{N-1}(\\mathbf{X}-\\bar{\\mathbf{X}})^T (\\mathbf{X}-\\bar{\\mathbf{X}})\\\\\n&=&\\frac{1}{N-1}\\left[\\mathbf{X}^T\\mathbf{X} - \\bar{\\mathbf{X}}^T\\bar{\\mathbf{X}}\\right]\n\\end{eqnarray}\n\nSo $\\mathbf{X}^T\\mathbf{X}$ defines up to a constant the variance covariance matrix of $\\mathbf{X}$! When the matrix is column centered $\\mathbf{S}=\\frac{1}{n-1}\\mathbf{X}^T\\mathbf{X}$.\n\nThe same holds for the rows of $\\mathbf{X}$! The covariance between the subjects can be estimated as \\[\\mathbf{S}=\\frac{1}{p-1}\\mathbf{X}\\mathbf{X}^T\\] upon row centering.\n\nNote, that\n\\begin{eqnarray}\n\\mathbf{X}^T\\mathbf{X} &=& \\mathbf{V}\\boldsymbol{\\Delta}\\mathbf{U}^T \\mathbf{U} \\boldsymbol{\\Delta} \\mathbf{V}^T \\\\\n&=&\\mathbf{V}\\boldsymbol{\\Delta}^2 \\mathbf{V}^T\n\\end{eqnarray}\n\nIf we rewrite the expression\n\\begin{eqnarray}\n\\mathbf{X}^T\\mathbf{X}\\mathbf{V} &=&\\mathbf{V}\\boldsymbol{\\Delta}^2 \\mathbf{V}^T\\mathbf{V}\\\\\n&=&\\mathbf{V}\\boldsymbol{\\Delta}^2\n\\end{eqnarray}\n\nSo, if the data are centered, the SVD can be used to perform a spectral decomposition of the sample covariance matrix where the right singular vectors correspond to the eigen vectors of the covariance matrix and the eigen values are the squared singular values!\n\nSimilarly the left singular values can be used to estimate the covariance matrix of the rows of $\\mathbf{X}$. So in our notation covariance between subjects.\n\n\\begin{eqnarray}\n\\mathbf{X}\\mathbf{X}^T &=&\\mathbf{U}\\boldsymbol{\\Delta}^2 \\mathbf{U}^T\n\\end{eqnarray}\n\nThis link is for instance very useful for recommender systems, i.e. to propose movies based on the subjects with whom you correlate. We will also exploit this when we discuss on PCA.\n\n# SVD and inverse of a matrix\n\nA linear system of equations with $n$ equations and $n$ unknowns\n\\[\n\\mathbf{A}_{n\\times n} \\boldsymbol{\\beta} = \\mathbf{b}\n\\]\ncan be solved by\n\\[\n\\boldsymbol{\\beta} = \\mathbf{A}_{n\\times n}^{-1} \\mathbf{b}\n\\]\n\nA unique solution exists if A is full rank.\n\nNote, that a singular value decomposition of the square matrix $\\mathbf{A}=\\mathbf{U}\\boldsymbol{\\Delta}\\mathbf{V}^T$ enables the inverse to be written as\n\n\\[\n\\mathbf{A}^{-1} = \\mathbf{V}\\boldsymbol{\\Delta}^{-1}\\mathbf{U}^T\n\\]\n\nindeed\n\\[\n\\mathbf{A}^{-1} \\mathbf{A} = \\mathbf{V}\\boldsymbol{\\Delta}^{-1}\\mathbf{U}^T\\mathbf{U}\\boldsymbol{\\Delta}\\mathbf{V}^T = \\mathbf{I}\n\\]\n\nNote, that the SVD generalizes this to systems of under (n<p, fat short matrices)\n and over determined systems (n>p tall skinny matrices):\n\nLet\n\\begin{eqnarray}\n\\mathbf{A} = \\mathbf{U}\\boldsymbol{\\Delta}\\mathbf{V}^T\n\\end{eqnarray}\n\nand we want to solve\n\\begin{eqnarray}\n\\mathbf{A} \\boldsymbol{\\beta} &=& \\mathbf{b}\\\\\n\\mathbf{U}\\boldsymbol{\\Delta}\\mathbf{V}^T \\boldsymbol{\\beta} &=& \\mathbf{b}\\\\\n\\mathbf{U}^T\\mathbf{U}\\boldsymbol{\\Delta}\\mathbf{V}^T \\boldsymbol{\\beta} &=& \\mathbf{U}^T\\mathbf{b}\\\\\n\\boldsymbol{\\Delta}\\mathbf{V}^T \\boldsymbol{\\beta} &=& \\mathbf{U}^T\\mathbf{b}\\\\\n\\boldsymbol{\\Delta}^{-1}\\boldsymbol{\\Delta}\\mathbf{V}^T \\boldsymbol{\\beta} &=& \\boldsymbol{\\Delta}^{-1}\\mathbf{U}^T\\mathbf{b}\\\\\n\\mathbf{V}\\mathbf{V}^T \\boldsymbol{\\beta} &=& \\mathbf{V}\\boldsymbol{\\Delta}^{-1}\\mathbf{U}^T\\mathbf{b}\\\\\n\\boldsymbol{\\beta} &=& \\mathbf{V}\\boldsymbol{\\Delta}^{-1}\\mathbf{U}^T\\mathbf{b}\n\\end{eqnarray}\n\nNote, that for an overdetermined system $n>p$ so $r\\leq p$.\nGenerally, $r=p$ and $\\mathbf{V}$ is thus a square matrix so both $\\mathbf{V}^T\\mathbf{V}=\\mathbf{I}$ and  $\\mathbf{V}\\mathbf{V}^T=\\mathbf{I}$. However, $\\mathbf{U}^T\\mathbf{U}=\\mathbf{I}$ but  $\\mathbf{U}\\mathbf{U}^T\\neq\\mathbf{I}$ because $r<n$.\n\n$\\mathbf{A}^\\dagger=\\mathbf{V}\\boldsymbol{\\Delta}^{-1}\\mathbf{U}^T$ is also referred to as the pseudo inverse and it enables us to solve under and overdetermined systems of equations.\n\nNote, that for\n\n- underdetermined systems there typically does not exist a unique solution\n- for overdetermined systems usually there does not exist an exact solution. We will focus on the latter in the next section where we explore the link between linear regression and SVD.\n\n# Linear regression and SVD\n\nSuppose we have the linear regression problem with $n>p$:\n\n\\[\\mathbf{Y}=\\mathbf{X}\\boldsymbol{\\beta} + \\boldsymbol{\\epsilon}\\]\n\n$\\mathbf{X}$ is a tall skinny matrix with $n >> p$.\n\nWe know that\n\\[\n\\hat{\\boldsymbol{\\beta}}=\\left(\\mathbf{X}^T \\mathbf{X}\\right)^{-1}\\mathbf{X}^T\\mathbf{Y}\n\\]\n\nIf we replace $\\mathbf{X}$ by its SVD\n\n\\begin{eqnarray}\n\\hat{\\boldsymbol{\\beta}}&=&\\left(\\mathbf{V}\\boldsymbol{\\Delta}^2\\mathbf{V}^T\\right)^{-1}\\mathbf{V}\\boldsymbol{\\Delta}\\mathbf{U}^T\\mathbf{Y}\\\\\n\\hat{\\boldsymbol{\\beta}}&=&\\mathbf{V}\\boldsymbol{\\Delta}^{-2}\\mathbf{V}^T\\mathbf{V}\\boldsymbol{\\Delta}\\mathbf{U}^T\\mathbf{Y}\\\\\n\\hat{\\boldsymbol{\\beta}}&=&\\mathbf{V}\\boldsymbol{\\Delta}^{-1}\\mathbf{U}^T\\mathbf{Y}\n\\end{eqnarray}\n\nSo the SVD also solves the linear regression problem by using the pseudoinverse!\nIf we now think about the fit:\n\n\\begin{eqnarray}\n\\hat{\\mathbf{Y}}&=&\\mathbf{X}\\hat{\\boldsymbol{\\beta}}\\\\\n&=&\\mathbf{U}\\boldsymbol{\\Delta}^{-1}\\mathbf{V}^T\\mathbf{V}\\boldsymbol{\\Delta}\\mathbf{U}^T\\mathbf{Y}\\\\\n&=&\\mathbf{U}\\mathbf{U}^T\\mathbf{Y}\n\\end{eqnarray}\n\n- For an overdetermined system $\\mathbf{U}\\mathbf{U}^T$ is not equal to the unity matrix $\\mathbf{I}$ (for an overdetermined system only $\\mathbf{U}^T\\mathbf{U}=\\mathbf{I}$ because $n>r$).\n\n- So $\\hat{\\mathbf{Y}}\\neq \\mathbf{Y}$. Hence, we typically do not have an exact solution.\n\n- Note, that $\\mathbf{U}\\mathbf{U}^T$ spans the same space as the columns of $\\mathbf{X}$, and will define the same $p$-dimensional plane in the $n$ dimensional space $\\mathcal{R}^n$, e.g. cfr $\\mathbf{X}\\left(\\mathbf{X}^T\\mathbf{X}\\right)^{-1}\\mathbf{X}^T$. So it projects $\\mathbf{Y}$ in the column space of $\\mathbf{X}$ and the errors will be orthogonal onto this plane.\n\n## Example prostate dataset\n### Fit with lm\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprostate <- read_csv(\n  \"https://raw.githubusercontent.com/GTPB/PSLS20/master/data/prostate.csv\",\n  col_types = cols()\n)\nlm1 <- lm(lpsa ~ lcavol + lweight + svi, prostate)\n```\n:::\n\n\n### Fit with SVD\n\n\n::: {.cell}\n\n```{.r .cell-code}\nX <- prostate[,c(1:2,5)]\nX[,3] <- as.double(X[,3]!=\"healthy\")\nX <- cbind(Intercept=1,X)\n\nsvdX <- svd(X)\nbetaSvd <- svdX$v %*% diag(1/svdX$d) %*% t(svdX$u) %*% prostate$lpsa\n\ncbind(lm1$coef,betaSvd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>                   [,1]       [,2]\n#> (Intercept) -0.2680724 -0.2680724\n#> lcavol       0.5516386  0.5516386\n#> lweight      0.5085359  0.5085359\n#> sviinvasion  0.6661583  0.6661583\n```\n\n\n:::\n:::\n\n\n# SVD and Multi-Dimensional Scaling (MDS)\n\n## Example\n\nIn this section we will use a dataset on food consumption in the UK. The data originate from the UKs ‘Department for Environment, Food and Rural Affairs’ (DEFRA), showing the consumption in grams (per person, per week) of 17 different types of foodstuff measured and averaged in the four countries of the United Kingdom in 1997. We would like to explore the data and interpret how the food patterns of the different countries differ.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nuk <- read_csv(\n  \"https://raw.githubusercontent.com/statOmics/HDA2020/data/ukFoods.csv\",\n  col_types = cols()\n)\nknitr::kable(uk, caption = \"The full UK foods data table\")\n```\n\n::: {.cell-output-display}\n\n\nTable: The full UK foods data table\n\n|...1               | England| Wales| Scotland| N.Ireland|\n|:------------------|-------:|-----:|--------:|---------:|\n|Cheese             |     105|   103|      103|        66|\n|Carcass_meat       |     245|   227|      242|       267|\n|Other_meat         |     685|   803|      750|       586|\n|Fish               |     147|   160|      122|        93|\n|Fats_and_oils      |     193|   235|      184|       209|\n|Sugars             |     156|   175|      147|       139|\n|Fresh_potatoes     |     720|   874|      566|      1033|\n|Fresh_Veg          |     253|   265|      171|       143|\n|Other_Veg          |     488|   570|      418|       355|\n|Processed_potatoes |     198|   203|      220|       187|\n|Processed_Veg      |     360|   365|      337|       334|\n|Fresh_fruit        |    1102|  1137|      957|       674|\n|Cereals            |    1472|  1582|     1462|      1494|\n|Beverages          |      57|    73|       53|        47|\n|Soft_drinks        |    1374|  1256|     1572|      1506|\n|Alcoholic_drinks   |     375|   475|      458|       135|\n|Confectionery      |      54|    64|       62|        41|\n\n\n:::\n:::\n\n\nNote, that here the matrix is displayed with the p variables in the rows and the n experimental units (countries) in the columns.\nThis is often done for high dimensional data where $p>>n$ because this makes it easier to look at to the raw data table.\nNote, that the svd calculates left and right singular vectors so it will also provide the correct solution, we just should look to the other set of singular vectors in order to get to the correct interpretation.\n\n## Motivation\n\nThe objective of Multidimensional Scaling (MDS) is to find a low-dimensional representation, say $k$-dimensional, of $n$ data points such that the distances between the $n$ points in the $k$-dimensional space is a good approximation of a given squared distance matrix, say $\\mathbf{D}_X$.\n\n- The squared distance matrix $\\mathbf{D}_X$ may be given without knowledge of the original observations (not even the dimensionality), or it may be computed from a given set of $n$ $p$-dimensional data points.\n\n\nUse of MDS:\n\n- A high dimensional data matrix $\\mathbf{X}$ is given, and one wants to get a visual representation (in 2 or 3 dimensions) of the observations. In this graph each point represents an observation (row of data matrix). From this graph one wants points close to one another to be similar, and observations far away from one another to be dissimilar. Thus the distances between the $n$ points in the original $p$-dimensional space should be well preserved in the 2 or 3 dimensional space.\n\n- In some applications the researcher only has knowledge of the similarity (or dissimilarity) between observations. For example, food products can be evaluated by a taste panel and a dissimilarity matrix can be completed. This dissimilarity matrix shows for each pair of food products their dissimilarity (numerical values provided by taste panel, but not objectively quantified). Given this dissimilarity matrix, a 2 or 3 dimensional graph could be helpful if the distances between the points (food products) in this graph are monotonically related to the dissimilarities provided by the taste panel. Food products close to one another in this graph, taste similarly.\n\n- Here we discuss the \"metric\" MDS, which actually requires the Euclidean distances between observations. However, the method works also well if the matrix $\\mathbf{D}_X$ contains dissimilarities rather than squared Euclidean distances.\n\n\n---\n\nIn this chapter we assume that the data matrix $\\mathbf{X}$ is column-centered (i.e. each column has mean zero).\n\nCentering can be accomplished by multiplying the original data matrix $\\mathbf{X}$ with the $n \\times n$ $\\mathbf{centering\\ matrix}$\n \\[\n   \\mathbf{H} = \\mathbf{I} - \\frac{1}{n} \\mathbf{1}\\mathbf{1}^T ,\n \\]\n in which $\\mathbf{1}$ is an $n$-vector with all entries equal to 1.\n Hence, $\\mathbf{H}\\mathbf{X}$ is the column-centered data matrix.\n\nWe will assume that $\\mathbf{X}$ is already column-centered, and therefore $\\mathbf{H}\\mathbf{X}=\\mathbf{X}$.\n\n(Note, that the matrix $\\mathbf{1}\\mathbf{1}^T$ is an $n\\times n$ matrix with all entries set to 1.\n)\n\n---\n\nWe will need the following interesting relationship between the **Gram matrix** $\\mathbf{X}\\mathbf{X}^T$ and the distance matrix.\n\n- For an $n\\times p$ data matrix $\\mathbf{X}$, the matrix $\\mathbf{D}_X$ with squared distances has elements\n   \\[\n      (\\mathbf{x}_{i}-\\mathbf{x}_{j})^T(\\mathbf{x}_{i}-\\mathbf{x}_{j}) = \\Vert \\mathbf{x}_i\\Vert^2 - 2 \\mathbf{x}^T_i\\mathbf{x}_j + \\Vert \\mathbf{x}_j\\Vert^2\n   \\]\n\n\n-The $n\\times n$ squared distance matrix can then be written as\n   \\[\n     \\mathbf{D}_X = \\mathbf{N} - 2\\mathbf{X}\\mathbf{X}^T + \\mathbf{N}^T ,\n   \\]\n   with $\\mathbf{N}$ the $n \\times n$ matrix with $i$th row filled with $\\Vert \\mathbf{x}_i\\Vert^2$.\n\n- Note that the elements of $\\mathbf{N}$ can also be found on the diagonal of $\\mathbf{XX}^T$.\n\n- Given the structure of the $\\mathbf{H}$ and $\\mathbf{N}$ matrices, it is easy to verify that\n   \\[\n      -\\frac{1}{2}\\mathbf{H}\\mathbf{D}_X\\mathbf{H} = \\mathbf{X}\\mathbf{X}^T.\n   \\] This gives an important relation between the distance matrix and the Gram matrix. We will use the notation $\\mathbf{G}_X = -\\frac{1}{2}\\mathbf{H}\\mathbf{D}_X\\mathbf{H}$.\n\n-  The $n \\times n$ Gram matrix $\\mathbf{X}\\mathbf{X}^T$  equals\n\\[\n  \\begin{pmatrix}\n   \\mathbf{x}_1^T \\\\\n   \\vdots  \\\\\n   \\mathbf{x}_n^T\n  \\end{pmatrix}\n  \\begin{pmatrix}\n    \\mathbf{x}_1 \\ldots \\mathbf{x}_n\n  \\end{pmatrix}\n\\]\nand\nhas thus on its $(i,j)$th position the inner product\n\\[\n   \\mathbf{x}_i^T\\mathbf{x}_j= \\Vert \\mathbf{x}_i\\Vert\\Vert \\mathbf{x}_j\\Vert \\cos<\\mathbf{x}_i,\\mathbf{x}_j> .\n\\]\n\n- On the diagonal we find $\\mathbf{x}_i^T\\mathbf{x}_i=\\Vert \\mathbf{x}_i\\Vert^2$, the squared norm of the $i$th observation.\n\n- The relation $-\\frac{1}{2}\\mathbf{H}\\mathbf{D}_X\\mathbf{H} = \\mathbf{X}\\mathbf{X}^T$ tells us that the distance matrix and the Gram matrix contain the same information. The distances, however, are in most situations easier to interpret.\n\n---\n\n## Link with the SVD\n\nNote, that we have shown that we can rewrite $\\mathbf{X}\\mathbf{X}^T$ using the SVD:\n\n\\[\n\\mathbf{X}\\mathbf{X}^T = \\mathbf{U}\\boldsymbol{\\Delta}^2\\mathbf{U}^T\n\\]\n\nsee @sec-SVDcov.\n\nBecause the truncated SVD of $\\mathbf{X}$ minimises the Frobenius norm $\\Vert \\mathbf{X}-\\mathbf{X}_k\\Vert_F^2$, it this has an important consequence:\n\n- Let $\\mathbf{D}_X$ denote the $n \\times n$ matrix with the squared Euclidean distances between the $n$ data points $\\mathbf{x}_i$ in the original $p$-dimensional space.\n\n- Let $\\mathbf{D}_{Zk}$ denote the $n \\times n$ matrix with the squared Euclidean distances between the $n$ transformed data points $\\mathbf{z}_{k,i}$ in the reduced $k$-dimensional space.\n\n Then, it can be shown that the truncated SVD also minimises\n \\[\n   \\Vert \\mathbf{D}_X - \\mathbf{D}_{Zk} \\Vert_F^2.\n \\]\n\nOr in other words: The n points $\\mathbf{z}_{k,i}$ in the k-dimensional subspace spanned by the columns of $\\mathbf{V}_k$ are the best approximation of the $n$ original points $\\mathbf{x}_i$ in the original p-dimensional space in the sense that the Euclidean distances between the n original points are best approximated by the Euclidean distances between the n transformed points, among all possible k-dimensional linear subspaces.\n\n---\n\n- If $\\mathbf{X}$ is known, we can readily obtain the k-dimensional projection by the SVD of $\\mathbf{X}$\n\n- If we only know the distance matrix $\\mathbf{D}$\n\n    1. We can readily obtain the Gram matrix\n    \\[-\\frac{1}{2}\\mathbf{H}\\mathbf{D}_X\\mathbf{H} = \\mathbf{X}\\mathbf{X}^T\\]\n    2. The truncated SVD of the squared and symmetric Gram matrix\n    \\[\\mathbf{U}_k\\boldsymbol{\\Delta}_k^\\prime\\mathbf{U}_k^T\\]\n    3. from which also can obtain\n    \\[\\mathbf{Z}_k=\\mathbf{U}_k\\boldsymbol{\\Delta}_k,\\] with $\\boldsymbol{\\Delta}_k= \\mathbf{\\Delta}_k^{\\prime \\frac{1}{2}}$\n\n## Example\n\n\n::: {.cell}\n\n```{.r .cell-code}\nX <- as.matrix(t(uk[,-1]))\nn <- nrow(X)\nH <- diag(n) - matrix(1/n,nrow=n,ncol=n)\nX <- H%*%X\nsvdUk <- svd(X)\n\nk <- 2\nUk <- svdUk$u[,1:k]\nDk <- diag(svdUk$d[1:k])\nZk <- Uk%*%Dk\nrownames(Zk) <- colnames(uk)[-1]\ncolnames(Zk) <- paste0(\"Z\",1:k)\nZk\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>                   Z1          Z2\n#> England   -144.99315   -2.532999\n#> Wales     -240.52915 -224.646925\n#> Scotland   -91.86934  286.081786\n#> N.Ireland  477.39164  -58.901862\n```\n\n\n:::\n\n```{.r .cell-code}\nZk |>\n  as.data.frame() |>\n  ggplot(aes(x=Z1,y=Z2,label=rownames(Zk))) +\n  geom_point(size = 3) +\n  geom_text(nudge_x = 50) +\n  coord_fixed()\n```\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-42-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n- The graph suggests that Wales and England are quite similar in terms of food consumption, and North Ireland seem to have a very different food consumption pattern.\n\n- Also note that England is close to the origin, meaning that the food consumption pattern is close to the average pattern in the UK.\n\n- A few questions remain:\n\n    - How well can the 17-dimensional data be represented in a 2-dimensional subspace?\n    - How can we interpret the distances (differences) between the data points in terms of the original 17 variables?\n\n## The biplot\n\nThe biplot is a single 2-dimensional graph which displays the information in both $\\mathbf{Z}_2=\\mathbf{U}_2\\boldsymbol{\\Delta}_2$ and $\\mathbf{V}_2$.\n\nThe plot of $\\mathbf{Z}_2$ has been discussed previously (e.g. best approximation of distances).\n\nThe name \"bi\"plot refers to the plotting of two parts of the SVD ($\\mathbf{Z}$ and $\\mathbf{V}$) in a single graph.\n\nFrom the geometric interpretation of the SVD we know that\n$\\mathbf{Z}_2$ is the orthogonal projection of $\\mathbf{X}$ on $\\mathbf{V}_2$ the basis spanned by the first two singular values.\nThus for the $i^\\text{th}$ individual we get\n\\[\n\\mathbf{z}_{2,i}^T= \\mathbf{x}_i^T \\left[\\begin{array}{cc}\\mathbf{v}_1&\\mathbf{v}_2\\end{array}\\right]\n\\]\n\nWe also know that we can approximate $\\mathbf{X}$ by $\\mathbf{X}_2$ which equals:\n\n\\begin{align}\n  \\mathbf{X}_2 &= \\mathbf{Z_2}\\mathbf{V}_2^T\\\\\n  &= \\mathbf{Z_2}\\left[\\begin{array}{c} \\mathbf{v}_1^T\\\\\n      \\mathbf{v}_2^T\\end{array}\\right]\n  = \\mathbf{Z_2}\n    \\left[\n      \\begin{array}{ccc}\\tilde{\\mathbf{v}}_{2,1} \\ldots \\tilde{\\mathbf{v}}_{2,p}\\end{array}\n    \\right]\n\\end{align}\n\nwith $\\mathbf{v}_1$ and $\\mathbf{v}_2$ the first two right singular vector and $\\tilde{\\mathbf{v}}_{2,j}$ the j$^\\text{th}$ column of the matrix $\\mathbf{V}_2^T$.\n\n- This basically shows us that the orthogonal projection of $\\mathbf{z}_{2,i}$ for subject/experimental unit i on $\\tilde{\\mathbf{v}}_{2,j}$ gives us the approximation of the value for  j$^\\text{th}$ variable that was observed for the $i^\\text{th}$ experimental unit, i.e. $x_{2,ij}$.\n\\[x_{2,ij}=\\mathbf{z}_{2,i}^T\\tilde{\\mathbf{v}}_{2,j}\\]\n\n### UK  example\n\n#### Biplot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nVk <- svdUk$v[,1:k]\nrownames(Vk) <- uk[[1]]\ncolnames(Vk) <- colnames(Zk)\nscaleFactor <- mean(svdUk$d[1:k])\n\ndiyBiplot <- ggplot() +\n  geom_point(\n    data=Zk |> as.data.frame(),\n    aes(x=Z1,y=Z2),\n    size = 3) +\n  geom_text(\n    data=Zk |> as.data.frame(),\n    aes(x=Z1,y=Z2,label=rownames(Zk)),\n    nudge_x = 50) +\n  geom_segment(\n    data=Vk |> as.data.frame(),\n    aes(x=0, y=0, xend=Z1*scaleFactor, yend=Z2*scaleFactor),\n    arrow=arrow(length=unit(0.4,\"cm\")),\n    alpha=0.25) +\n  geom_text(\n    data=Vk |> as.data.frame(),\n    aes(x=Z1*scaleFactor, y=Z2*scaleFactor, label=rownames(Vk)),\n    alpha=0.5,\n    size=3) +\n   coord_fixed()\n\ndiyBiplot\n```\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-43-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nbiplot(Zk,Vk)\n```\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-43-2.pdf){fig-pos='H'}\n:::\n:::\n\n\nThe R code shows two ways of constructing a biplot: the first method starts from the SVD of $\\mathbf{X}$ and plots the p vectors $\\tilde{\\mathbf{v}}_{2,j}$ as arrows. Note that we used a scaling factor to give the arrows a convenient length in the graph (not too small, not too large); it does not affect the interpretation. The second way of obtaining the biplot is simply by using the R built-in function biplot.\n\n#### Illustration of projection\n\nWe project $\\mathbf{z}_{2,i}$ for N.Ireland on Fresh_potatoes.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-44-1.pdf)\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrownames(X) <- rownames(Zk)\ncolnames(X) <- rownames(Vk)\nX[,\"Fresh_potatoes\"]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>   England     Wales  Scotland N.Ireland \n#>    -78.25     75.75   -232.25    234.75\n```\n\n\n:::\n\n```{.r .cell-code}\nZk[\"N.Ireland\",]%*%Vk[\"Fresh_potatoes\",]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>          [,1]\n#> [1,] 233.7418\n```\n\n\n:::\n:::\n\n\nWe observe that N. Ireland has a consumption in Fresh_potatoes that is 234.75 above the average and this is well approximated by the projection 233.74.\n\nAlso note that\n\n- The origin corresponds to the sample average of the 17-dimensional observations in the data matrix\n\n- England is close to the origin and thus one could say that the food consumption in England is as the average in the UK\n\n- Projecting the $\\mathbf{Z}_2$ coordinates for North Ireland orthogonally onto the vector $\\tilde{\\mathbf{v}}_{2,j}$ of fresh potatoes, we get a large and positive $x_{2,ij}$. Hence, people in N. Ireland tend to eat more fresh potatoes than on average in the UK.\n\n- We can do the same for the other vectors.\n\n### Further interpretation of the Biplot\n\nFrom $\\mathbf{x}_{k,i}^T =  \\mathbf{z}_{k,i}^T\\mathbf{V}_k^T$ we learnt that the original data can be (approximately) reconstructed from the $\\mathbf{z}_{k,i}$.\n\n We now show how the dimensions of $\\mathbf{Z}_k$ (columns or variables) can be interpreted. Remember,\n \\[\n  \\mathbf{z}_{k,i}^T = \\mathbf{x}_i^T\\mathbf{V}_k = \\left(\\mathbf{x}_i^T \\mathbf{v}_1 , \\mathbf{x}_i^T \\mathbf{v}_2 , \\ldots , \\mathbf{x}_i^T \\mathbf{v}_k\\right).\n \\]\n\n The $j$th column of $\\mathbf{Z}_k$ can be written as\n \\[\n   \\mathbf{z}_{k,j} = \\mathbf{X}\\mathbf{v}_j,\n \\]\n\n An individual element of $\\mathbf{Z}_k$ can be written as\n \\[\n   z_{k,ij} = \\mathbf{x}_i^T\\mathbf{v}_j,\n \\]\n\n which is a linear combination of the observations on the $p$ variables in $\\mathbf{x}_i$, with coefficients given by the $p$ elements in $\\mathbf{v}_j$. Understanding the elements in $\\mathbf{v}_j$ will give us insight into the interpretation of the $j$th dimension of $\\mathbf{Z}_k$.\n\n## Illustration Uk food\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot() +\n  geom_bar(\n    aes( x=rownames(Vk), y=Vk[,1]),\n    stat=\"identity\") +\n  xlab(\"V1\") +\n  ylab(\"contribution\") +\n  coord_flip()\n\np2 <-\nggplot() +\n  geom_bar(\n    aes( x=rownames(Vk), y=Vk[,2]),\n    stat=\"identity\") +\n  xlab(\"V2\") +\n  ylab(\"contribution\") +\n  coord_flip()\n\ngrid.arrange(p1,p2,ncol=2)\n```\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-46-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nIn giving an interpretation to the elements in $\\mathbf{v}_1$ and $\\mathbf{v}_2$, we ignore the elements close to zero (this is a subjective decision; later we see more objective methods).\n\nFor $\\mathbf{v}_1$ (1st dimension of $\\mathbf{Z}_2$):\n\n- contrast of soft drinks and fresh potatoes versus fresh fruit and alcoholic drinks\n\n- a large value of $z_{i1}$ can result from eating many fresh potatoes and drinking a lot of soft drinks, but eating only few fresh fruit and drinking not much alcoholic drinks\n\n- a small value of $z_{i1}$ can result from eating few fresh potatoes and drinking only few soft drinks, but eating a lot of fresh fruit and drinking much alcoholic drinks\n\nFor $\\mathbf{v}_2$ (2nd dimension of $\\mathbf{Z}_2$):\n\n- contrast of soft drinks versus fresh potatoes\n\n- a large value of $z_{i2}$ can result from eating many fresh potatoes, but drinking not much soft drinks\n\n- a small value of $z_{i2}$ can result from eating few fresh potatoes, but drinking much soft drinks .\n\n---\n\nThe elements in v1 and v2 are also shown in the biplot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrid.arrange(p1, p2, diyBiplot, ncol=2, layout_matrix = rbind(c(1,2),c(3,3)))\n```\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-47-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nFrom the graph we see e.g. that N. Ireland has a high score for the first dimension. Now that we can give an interpretation to the dimension, we conclude that in Northern Ireland people eat relatively much fresh potatoes and drink many soft drinks, but they do not drink much alcoholic drinks and eat not much fresh fruit. We had already come to these findings by projecting N. Ireland on the vectors of these four food products. This comes to no surprise: both interpretations arise from the same data set and its SVD, and so no contradictory results should arise. Other conclusions can be found in a similar fashion.\n\nWe have derived the interpretation of the first dimension from the barplot of the elements of $\\mathbf{v}_1$. However, there is actually no need to make a separate plot to read the elements of $\\mathbf{v}_1$; they can also be read from projecting the vectors in the biplot onto the first dimension (i.e. basis vector of the first dimension). For example, fresh potatoes is in the 7th column of $\\mathbf{X}$ and thus in the biplot its vector is $\\tilde{\\mathbf{v}}_{2,7}$; it is a 2-dimensional vector (2-dimensional biplot is shown). In the space of the biplot (i.e. the column space of $\\mathbf{Z}_2$), the first basis vector is given by $(1,0)$. Projecting  $\\tilde{\\mathbf{v}}_{2,7}^T$ orthogonally onto $(1,0)$ gives\n\\[\n  \\tilde{\\mathbf{v}}_{2,7}^T  \\begin{pmatrix} 1 \\\\ 0 \\end{pmatrix} = (v_{71} , v_{72}) \\begin{pmatrix} 1 \\\\ 0 \\end{pmatrix} = v_{71}\n\\]\nwhich is the seventh element of the first right-singular vector of $\\mathbf{X}$, which is thus the bar of fresh potatoes in the barplot of the first dimension.\n\n# SVD and principal component analysis (PCA)\n\n- PCA is basically a SVD\n\n- PCA adds another layer of interpretation\n\n- PCA comes with its own terminology\n\n- One of the most widely used algorithms for dimension reduction and data exploration of multivariate and high dimensional data.\n\n- It is motivated from the decomposition of the Variance covariance matrix of the data\n\n## Variance covariance matrix\n\n-   For a given centered data matrix $\\mathbf{X}$ the $p\\times p$ covariance matrix can be estimated by\n  \\[\n    \\boldsymbol{\\Sigma}_X = \\frac{1}{n-1}\\mathbf{X}^T\\mathbf{X} =\\frac{1}{n-1}\\sum_{i=1}^n \\mathbf{x}_i\\mathbf{x}_i^T,\n  \\]\n  i.e. the $(i,j)$th element is given by (column means are zero)\n  \\[\n    \\frac{1}{n-1}\\sum_{m=1}^n x_{mi}x_{mj}=\\frac{1}{n-1}\\sum_{m=1}^n (x_{mi}-\\bar{x}_i)(x_{mj}-\\bar{x}_j).\n  \\]\n\nNote, that when we forget to write the factor $1/(n-1)$ all the derivations still hold. It is only a proportionality factor and it does not affect the interpretation.\n\n---\n\n## Conventional derivation of PCA\n\nPCA is usually introduced as follows.\n\nLet\n\\[\n  y_i=\\mathbf{x}_i^T\\mathbf{a}\n\\]\nwith $\\mathbf{a}$ a $p$-vector of constants. Hence $y_i$ is a linear combination (or transformation) of $\\mathbf{x}_i$.\n\nPCA aims at finding $\\mathbf{a}$ such that the sample variance among the $n$ $y_i$'s is maximal, with\n\\begin{eqnarray*}\n  \\frac{1}{n-1}\\sum_{i=1}^n (y_i - \\bar{y})^2 &=&  \\frac{1}{n-1}\\sum_{i=1}^n y_i ^2 \\\\\n    &=& \\frac{1}{n-1}\\sum_{i=1}^n (\\mathbf{x}_i^T\\mathbf{a})^2\\\\\n    &=& \\frac{1}{n-1} \\mathbf{a}^T \\left(\\sum_{i=1}^n \\mathbf{x}_i\\mathbf{x}_i^T\\right) \\mathbf{a} \\\\\n    &=& \\frac{1}{n-1} \\mathbf{a}^T\\mathbf{X}^T\\mathbf{X}\\mathbf{a}\\\\\n    &=& \\mathbf{a}^T\\boldsymbol{\\Sigma}_X\\mathbf{a}\n\\end{eqnarray*}\nin which $\\boldsymbol{\\Sigma}_X= \\frac{1}{n-1}\\mathbf{X}^T\\mathbf{X}$ is the sample covariance matrix of $\\mathbf{X}$.\n\n### Problem for optimisation\n\nFinding $\\mathbf{a}$ that maximises\n\\[\n  \\text{var}[y]  = \\mathbf{a}^T\\boldsymbol{\\Sigma}_X\\mathbf{a}\n\\]\nhas a trivial solution (set all elements of $\\mathbf{a}$ equal to $\\infty$). To avoid the trivial solution, the solution must satisfy a restriction, e.g.\n\\[\n  \\Vert \\mathbf{a}\\Vert^2 = \\mathbf{a}^T\\mathbf{a}=1.\n\\]\n\nThe solution of the constrained maximisation problem may be formulated as\n\\[\n  \\mathbf{a} = \\text{ArgMax}_{b:\\Vert b\\Vert^2=1} \\mathbf{b}^T\\boldsymbol{\\Sigma}_X\\mathbf{b}.\n\\]\nBy introducing a Lagrange multiplier $\\lambda$, we get an unconstrained maximisation problem,\n\\[\n  \\mathbf{a} = \\text{ArgMax}_{b} \\left(\\mathbf{b}^T\\boldsymbol{\\Sigma}_X\\mathbf{b}-\\lambda(\\mathbf{b}^T\\mathbf{b}-1)\\right).\n\\]\n\n---\n\nNote that,\n\n- If the constraint is linear, then the constrained optimisation problem (here: maximisation) may be replaced by an unconstrained optimisation problem of the same criterion but with an ``penalty term'' added. This method is due to Lagrange. The penalty term vanishes when the constraint is satisfied.\n\n- If the constraint is satisfied, $\\mathbf{b}^T\\mathbf{b}=\\Vert \\mathbf{b}\\Vert^2=1$ and thus $\\mathbf{b}^T\\mathbf{b}-1=0$ and the ``penalty'' term in the unconstrained criterion vanishes.\n\n- The Lagrange multiplier $\\lambda$ is to be considered as an extra parameter that may have to be estimated from the data.\n\n---\n\nThe solution of\n\\[\n  \\mathbf{a} = \\text{ArgMax}_{b} \\left(\\mathbf{b}^T\\boldsymbol{\\Sigma}_X\\mathbf{b}-\\lambda(\\mathbf{b}^T\\mathbf{b}-1)\\right)\n\\]\nis obtained by differentiating $\\mathbf{b}^T\\boldsymbol{\\Sigma}_X\\mathbf{b}-\\lambda(\\mathbf{b}^T\\mathbf{b}-1)$ w.r.t. $\\mathbf{b}$, equating it to zero and solving for $\\mathbf{b}$.\n\\begin{eqnarray*}\n \\frac{\\partial}{\\partial \\mathbf{b}} \\left(\\mathbf{b}^T\\boldsymbol{\\Sigma}_X\\mathbf{b}-\\lambda(\\mathbf{b}^T\\mathbf{b}-1)\\right)\n    &=& 0 \\\\\n    2\\boldsymbol{\\Sigma}_X\\mathbf{b} -2\\lambda\\mathbf{b}\n    &=& 0.\n\\end{eqnarray*}\n\nHence, we need the solution of\n\\[\n  \\boldsymbol{\\Sigma}_X\\mathbf{b} = \\lambda\\mathbf{b}.\n\\]\n\nThis equation has $r$ solutions:\n\n-  $\\mathbf{b}=\\mathbf{e}_j$: the $j$th eigen vector of $\\boldsymbol{\\Sigma}_X$\n\n-  $\\lambda=\\lambda_j$: the $j$th eigen value of $\\boldsymbol{\\Sigma}_X$.\n\nThe eigen vectors are orthonormal, i.e.\n$\\mathbf{e}_i^T\\mathbf{e}_j=1$ if $i=j$ and $\\mathbf{e}_i^T\\mathbf{e}_j=0$ otherwise.\n\n---\n\nConsider the following calculations, with $\\mathbf{b}=\\mathbf{e}_j$, the $j$the eigen vector of $\\boldsymbol{\\Sigma}_X$.\n\\begin{eqnarray*}\n  \\text{var}[y]\n    &=& \\mathbf{e}_j^T\\boldsymbol{\\Sigma}_X\\mathbf{e}_j \\\\\n    &=& \\mathbf{e}_j^T(\\boldsymbol{\\Sigma}_X\\mathbf{e}_j) \\\\\n    &=& \\mathbf{e}_j^T \\left(\\lambda_j \\mathbf{e}_j\\right) \\\\\n    &=& \\lambda_j\\mathbf{e}_j^T\\mathbf{e}_j \\\\\n    &=& \\lambda_j.\n\\end{eqnarray*}\nBy convention the eigen vectors/eigen values are ordered so that\n\\[\n  \\lambda_1 \\geq \\lambda_2 \\geq \\cdots \\geq \\lambda_r.\n\\]\nHence, the first eigen vector $\\mathbf{e}_1$ gives the largest variance $\\lambda_1$. Hence, this is the solution we were looking for.\n\n---\n\nWe now switch notation and from now onwards we denote $y$ by $z$.\n\nThe observations on the first principal component (PC) are then given by\n\\[\n    z_{i1} = \\mathbf{x}_i^T\\mathbf{e}_1.\n\\]\n\nIn PCA terminology they are referred to as the **scores** of the first PC. The elements in the eigen vector $\\mathbf{e}_i$ that make up the transformation are known as the **loadings**  of the first PC.\n\nThe first PC is thus a new variable (construct) that has the largest variance among all linear transformations of the original variables.\n\nVariability between observations is considered as informative to understand differences between the observations.\n\n---\n\nThe equation\n\\[\n  \\boldsymbol{\\Sigma}_X\\mathbf{b} = \\lambda\\mathbf{b}\n\\]\nhas $r=\\text{rank}(\\boldsymbol{\\Sigma}_X)$ solutions. The eigen vectors are orthonormal, i.e.\n\\[\n  \\forall i\\neq j: \\mathbf{e}_i^T \\mathbf{e}_j = 0 \\text{ and } i=j: \\mathbf{e}_i^T \\mathbf{e}_j = 1\n\\]\nHence (for $i\\neq j$)\n\\begin{eqnarray*}\n  \\text{cov}\\left[\\mathbf{x}^T\\mathbf{e}_i,\\mathbf{x}^T\\mathbf{e}_j\\right] &=& \\mathbf{e}_i^T\\text{var}[\\mathbf{x}]\\mathbf{e}_j\\\\\n  &=& \\mathbf{e}_i^T\\boldsymbol{\\Sigma}_X\\mathbf{e}_j\\\\\n  &=& \\mathbf{e}_i^T\\left(\\lambda_j\\mathbf{e}_j\\right)\\\\\n  &=& \\lambda_j \\mathbf{e}_i^T\\mathbf{e}_j \\\\\n  &=& 0\n\\end{eqnarray*}\n\n\nIf $z_{j}=\\mathbf{x}_i^T\\mathbf{e}_j$ denotes the $j$th PC, then\n\\[\n  \\text{cov}\\left[z_i,z_j\\right]=\\text{cov}\\left[\\mathbf{x}^T\\mathbf{e}_i,\\mathbf{x}^T\\mathbf{e}_j\\right] =0 \\text{ if } i\\neq j\n\\]\n\\[\n  \\text{var}\\left[z_j\\right] = \\lambda_j .\n\\]\nWe say that the $j$th PC maximises the variance among all linear transformations such that it is uncorrelated with the previous PCs.\n\n---\n\n### Interpretation of PCA\n\nA PCA is a transformation of the original $p$ variables to $r$ PCs such that\n\n- the first PC has largest variance, equal to first eigen value of $\\boldsymbol{\\Sigma}_X$\n\n-  the next PCs have decreasing variances (decreasing information content)\n\n- all PCs are mutually uncorrelated (no information-overlap).\n\n---\n\n## Link with SVD\n\nIf we write the eigen value decomposition in matrix form:\n\\[\n\\boldsymbol{\\Sigma}_X\\mathbf{\n  B} = \\mathbf{B}\\boldsymbol{\\Lambda}.\n\\]\n\nwith $\\boldsymbol{\\Lambda}$ is a diagonal matrix with diagonal elements $[\\lambda_i]_{ii}$.\n\nWe recognise an expression that we have seen when discussing the link between the SVD and the sample covariance matrix, see @sec-SVDcov.\n\n\\begin{eqnarray}\n\\mathbf{X}^T\\mathbf{X}\\mathbf{V} &=&\\mathbf{V}\\boldsymbol{\\Delta}^2\n\\end{eqnarray}\n\n\n- So, the SVD can be used to solve the spectral decomposition (eigen value eigen vector) problem and the eigen vectors coincide with the right singular vectors and the eigen values are the singular values squared!\n\n## Conservation of variance\n\n- The total variance in a data set $\\mathbf{X}$ is given by the sum of the variances of the variables,\n  \\[\n    \\sigma^2_{\\text{tot}} = \\sum_{j=1}^p \\text{var}\\left[X_j\\right] = \\text{trace}(\\boldsymbol{\\Sigma}_X)\n  \\]\n\n\n-  For a symmetric matrix it holds that\n  \\[\n    \\text{trace}(\\boldsymbol{\\Sigma}_X) = \\sum_{j=1}^r \\lambda_j.\n  \\]\n\n-  Since $\\lambda_j=\\text{var}\\left[Z_j\\right]$, we find\n  \\[\n    \\sigma^2_{\\text{tot}} = \\sum_{j=1}^p \\text{var}\\left[X_j\\right]= \\sum_{j=1}^r \\text{var}\\left[Z_j\\right].\n  \\]\n\n$\\longrightarrow$   Thus no information is lost by the PCA transformation from the original $p$-dimensional space to the $r$-dimensional PCA space.\n\n---\n\n## Choosing the number of dimensions\n\nFor PCA the reasoning is usually based on the relative variance of a PC,\n\\[\n   \\frac{\\text{var}\\left[Z_j\\right]}{\\sigma^2_{\\text{tot}}} = \\frac{\\lambda_j}{\\sum_{i=1}^r \\lambda_i} =\\frac{\\delta_j^2}{\\sum_{i=1}^r \\delta_i^2} .\n\\]\nIf the first $k$ PCs are selected for further use, then they represent\n\\[\n  100 \\times  \\frac{\\sum_{j=1}^k \\lambda_j}{\\sum_{i=1}^r \\lambda_i} \\%\n  = 100 \\times  \\frac{\\sum_{j=1}^k \\delta^2_j}{\\sum_{i=1}^r \\delta_i^2} \\%\n\\]\nof the total variance (or information) of the original data set $\\mathbf{X}$.\n\n### UK example\n\nA scree plot is often used to look at the eigen values. Here it is shown for the UK consumption data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- nrow(X)\nr <- ncol(svdUk$v)\ntotVar <- sum(svdUk$d^2)/(n-1)\nvars <- data.frame(comp=1:4,var=svdUk$d^2/(n-1)) |>\n  mutate(propVar=var/totVar,cumVar=cumsum(var/totVar))\n\npVar1 <- vars |>\n  ggplot(aes(x=comp:r,y=var)) +\n  geom_point() +\n  geom_line() +\n  xlab(\"Component\") +\n  ylab(\"Variance\")\n\npVar2 <- vars |>\n  ggplot(aes(x=comp:r,y=propVar)) +\n  geom_point() +\n  geom_line() +\n  xlab(\"Component\") +\n  ylab(\"Proportion of Total Variance\")\n\npVar3 <- vars |>\n  ggplot(aes(x=comp:r,y=cumVar)) +\n  geom_point() +\n  geom_line() +\n  xlab(\"Component\") +\n  ylab(\"Cum. prop. of tot. var.\")\n\ngrid.arrange(pVar1, pVar2, pVar3, nrow=1)\n```\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-48-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nFrom these graphs we may conclude that with using k = 2 dimensions, more than 95% of the total variance is retained.\n\n---\n\n### Choosing the number of dimensions SVD\n\nMore generally, scree plots are also informative for the SVD.\n\n\n  The motivation comes from\n\n\n  \\begin{eqnarray*}\n  \\text{Min}_{A: \\text{rank}(A)=k} \\Vert \\mathbf{X} - \\mathbf{A}\\Vert_F^2 &=& \\Vert \\mathbf{X} - \\mathbf{X}_k\\Vert_F^2\\\\\n  &=& \\sum_{j=k+1}^r\\delta_{j}^2 \\\\\n  &=& \\sum_{j=k+1}^r\\lambda_{j}.\n\\end{eqnarray*}\n\n  This is known as the **approximation error** of the matrix $\\mathbf{X}_k$.\n\n  Hence,\n  \\[\n    \\frac{\\sum_{j=1}^k\\delta_j^2}{\\sum_{j=1}^r \\delta_j^2}  =\\frac{\\sum_{j=1}^k\\lambda_{j}}{\\sum_{j=1}^r\\lambda_{j}}\n  \\]\n  still makes sense as a relative quality measure for the SVD in general (including matrix approximation and MDS).\n\n### Rules of thumb to select number of dimensions\n\nSelect k such that\n\n- at least 80% of the total variance is retained in the PC space, or, equivalently, at\nmost 20% relative approximation error\n\n- adding more dimensions does not add more information (in a relative sense); this can often be visually detected as the “knee” or “elbow” in the scree plot\n\n- none of the dimensions has a variance smaller than the variance of one of the p original variables (this rule is typically only used when the variables are first standardised - see later).\n\n## Covariance vs Correlation Matrix\n\n### Direction of largest variability\n\n Now that we know how the PCs are constructed, we can give an additional interpretation to the first eigen vector / right-singular vector of $\\boldsymbol{\\Sigma}_X$.\n\n- The first eigen vector of $\\boldsymbol{\\Sigma}_X$ is the direction in the original $p$-dimensional space of the largest variability.\n\n- The second eigen vector of $\\boldsymbol{\\Sigma}_X$ is the direction in the original $p$-dimensional space of the second largest variability, among all directions orthogonal to the first eigen vector\n\n#### Iris example\n\nThe iris dataset in R contains information on leaves of iris flowers from different species.\nHere, we will focus on the setosa species and on the sepal length and sepal width.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nirisSetosa <- iris |>\n  filter(Species == \"setosa\") |>\n  dplyr::select(\"Sepal.Length\",\"Sepal.Width\")\n\nnIris <- nrow(irisSetosa)\nhIris <- diag(nIris) - matrix(1/nIris, nIris, nIris)\nirisX <- irisSetosa |>\n  as.matrix()\nirisX <- hIris %*% irisX\n\nirisSvd <- svd(irisX)\n\npIris <- irisX |>\n  as.data.frame() |>\n  ggplot(aes(x=Sepal.Length,y=Sepal.Width)) +\n  geom_point()\n\npIris <- pIris +\n  geom_segment(\n    aes(\n      x = 0,\n      y = 0,\n      xend = -irisSvd$v[1,1]*irisSvd$d[1]/sqrt(nIris-1),\n      yend = -irisSvd$v[2,1]*irisSvd$d[1]/sqrt(nIris-1)\n      ),\n      arrow = arrow(length=unit(0.4,\"cm\"))\n    ) +\n  geom_segment(\n    aes(\n      x = 0,\n      y = 0,\n      xend = irisSvd$v[1,2]*irisSvd$d[2]/sqrt(nIris-1),\n      yend = irisSvd$v[2,2]*irisSvd$d[2]/sqrt(nIris-1)\n      ),\n    arrow = arrow(length=unit(0.4,\"cm\"))\n    ) +\n  geom_text(\n    aes(\n      x = -irisSvd$v[1,1]*irisSvd$d[1]/sqrt(nIris-1),\n      y = -irisSvd$v[2,1]*irisSvd$d[1]/sqrt(nIris-1)+.1,\n      label=paste0(\"\\u03b4\",\"1e1\")\n      )\n    ) +\n  geom_text(\n    aes(\n      x = irisSvd$v[1,2]*irisSvd$d[2]/sqrt(nIris-1),\n      y = irisSvd$v[2,2]*irisSvd$d[2]/sqrt(nIris-1)+.1,\n      label=paste0(\"\\u03b4\",\"2e2\")\n      )\n    ) +\n  xlim(-1, 1) +\n  ylim(-1,1) +\n  coord_fixed()\n\n\npIris\n```\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-49-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n### Covariance versus correlation matrix\nSo far we have worked with\n\n- the column-centered data matrix $\\mathbf{X}$\n\n- the SVD of $\\mathbf{X}$ and $\\boldsymbol{\\Sigma}_X\\propto \\mathbf{X}^T\\mathbf{X}$ (the covariance matrix).\n\nIn some situations it is better to start from the standardised variables:\n\n- subtract from each element in $\\mathbf{X}$ the  column-mean\n- divide each centered element in $\\mathbf{X}$ by the column-specific standard deviation\n\nThus each element $x_{ij}$ is replaced with\n  \\[\n     \\frac{x_{ij}-\\bar{x}_j}{s_j} ,\n  \\]\nwith $\\bar{x}_j$ and $s_j$ the column mean and column standard deviation.\n\n-   In matrix notation, the standardisation, starting from the centered matrix $\\mathbf{X}$ is computed as\n  \\[\n      \\mathbf{X}\\mathbf{S}^{\\prime-1}\n  \\]\n  where $\\mathbf{S}^\\prime$ is a diagonal matrix with the column-specific standard deviations.\n\n---\n\n#### Iris Example\n\n::: {.cell}\n\n```{.r .cell-code}\nvar(irisX)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>              Sepal.Length Sepal.Width\n#> Sepal.Length   0.12424898  0.09921633\n#> Sepal.Width    0.09921633  0.14368980\n```\n\n\n:::\n\n```{.r .cell-code}\nSprime <- diag(sqrt(diag(var(irisX))))\nXs <- irisX%*%solve(Sprime)\nvar(Xs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>           [,1]      [,2]\n#> [1,] 1.0000000 0.7425467\n#> [2,] 0.7425467 1.0000000\n```\n\n\n:::\n:::\n\n\nMuch faster to use the scale function. By default center=TRUE and scale=TRUE.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nXs <- irisSetosa |> scale()\nvar(Xs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>              Sepal.Length Sepal.Width\n#> Sepal.Length    1.0000000   0.7425467\n#> Sepal.Width     0.7425467   1.0000000\n```\n\n\n:::\n:::\n\n\nShow problem of different units:\n\n- Sepal length in cm\n- Sepal width  in mm\n\n\n::: {.cell}\n\n```{.r .cell-code}\nirisX2 <- irisX\nirisX2[,2] <- irisX2[,2]*10\n\npIris2 <- irisX2 |>\n  as.data.frame() |>\n  ggplot(aes(x=Sepal.Length,y=Sepal.Width)) +\n  geom_point() +   coord_fixed()\n\n\nirisSvd2 <- svd(irisX2)\n\npIris2 <- pIris2 +\n  geom_segment(\n    aes(\n      x = 0,\n      y = 0,\n      xend = irisSvd2$v[1,1]*irisSvd2$d[1]/sqrt(nIris-1),\n      yend = irisSvd2$v[2,1]*irisSvd2$d[1]/sqrt(nIris-1)\n      ),\n      arrow = arrow(length=unit(0.4,\"cm\"))\n    ) +\n  geom_segment(\n    aes(\n      x = 0,\n      y = 0,\n      xend = irisSvd2$v[1,2]*irisSvd2$d[2]/sqrt(nIris-1),\n      yend = irisSvd2$v[2,2]*irisSvd2$d[2]/sqrt(nIris-1)\n      ),\n    arrow = arrow(length=unit(0.4,\"cm\"))\n    ) +\n  geom_text(\n    aes(\n      x = irisSvd2$v[1,1]*irisSvd2$d[1]/sqrt(nIris-1)*1.2,\n      y = irisSvd2$v[2,1]*irisSvd2$d[1]/sqrt(nIris-1)*1.2,\n      label=paste0(\"\\u03b4\",\"1e1\")\n      )\n    ) +\n  geom_text(\n    aes(\n      x = irisSvd2$v[1,2]*irisSvd2$d[2]/sqrt(nIris-1)*1.2,\n      y = irisSvd2$v[2,2]*irisSvd2$d[2]/sqrt(nIris-1)*1.2,\n      label=paste0(\"\\u03b4\",\"2e2\")\n      )\n    ) +\n  xlim(-10, 10) +\n  ylim(-10,10)\n\ngrid.arrange(pIris, pIris2,ncol=2)\n```\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-52-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nLeft: original matrix -- Right: second column of $\\mathbf{X}$ multiplied by 10 (e.g. moving from cm to mm).\n\nDirections of maximal variability are affected by the units of the variables.\n\n---\n\n### Recommendations\n\nWhen to use correlation and when covariance?\n\n- Use correlation when columns of $\\mathbf{X}$ are expressed in different units\n\n- Use covariance when columns of $\\mathbf{X}$ are expressed in the same units.\n\nThere may be exceptions.\n\n---\n\n## PCA and the Multivariate Normal Distribution\n\nThe density function of a multivariate normal distribution (MVN) is given by\n\\[\n  f(\\mathbf{x}) = (2\\pi)^{-p/2}\\vert \\boldsymbol{\\Sigma}\\vert^{-1/2} \\exp\\left( -\\frac{1}{2} (\\mathbf{x}-\\boldsymbol{\\mu})^T \\boldsymbol{\\Sigma}^{-1} (\\mathbf{x}-\\boldsymbol{\\mu})\\right) ,\n\\]\nwhere\n\n- $\\boldsymbol{\\mu}$ is the multivariate mean vector ($p$-dimensional). The $j$th element is $\\mu_j = \\text{E}\\left[X_j\\right]$\n\n- $\\boldsymbol{\\Sigma}$ is the $p \\times p$ covariance matrix. The $(i,j)$th element is $\\sigma_{ij}=\\text{cov}\\left[X_i, X_j\\right]$.\n\n---\n\nTo get a better understanding of the MVN we focus on the exponential which has the factor\n\\[\n    (\\mathbf{x}-\\boldsymbol{\\mu})^T \\boldsymbol{\\Sigma}^{-1} (\\mathbf{x}-\\boldsymbol{\\mu})\n\\]\nThis factor\n\n- is the only factor in the density function that depends on $\\mathbf{x}$\n\n- is a $\\mathbf{quadratic}$ form\n\n- is constant in points $\\mathbf{x}$ with constant density $f(\\mathbf{x})$.\n\n---\n\nConsider $p=2$ (bivariate normal). Then, all $\\mathbf{x} \\in \\mathbb{R}^2$ for which\n\\[\n    (\\mathbf{x}-\\boldsymbol{\\mu})^T \\boldsymbol{\\Sigma}^{-1} (\\mathbf{x}-\\boldsymbol{\\mu}) = \\text{constant } c^2\n\\]\nlie on an ellipse with center $\\boldsymbol{\\mu}$.\n\nThese ellipses are known as **constant density ellipses**.\n\n### Iris example\n\n\n::: {.cell}\n\n```{.r .cell-code}\npIris +\n  stat_ellipse() +\n  stat_ellipse(level=.68) +\n  stat_ellipse(level=.1)\n```\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-53-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n---\n\nNow plug in the SVD of $\\boldsymbol{\\Sigma}=\\mathbf{V}\\boldsymbol{\\Delta}^2\\mathbf{V}^T$, see @sec-SVDcov.\n\n\\begin{eqnarray*}\n   (\\mathbf{x}-\\boldsymbol{\\mu})^T \\boldsymbol{\\Sigma}^{-1} (\\mathbf{x}-\\boldsymbol{\\mu}) &=& c^2\\\\\n   (\\mathbf{x}-\\boldsymbol{\\mu})^T \\mathbf{V}\\boldsymbol{\\Delta}^{-2}\\mathbf{V}^T (\\mathbf{x}-\\boldsymbol{\\mu}) &=& c^2\n\\end{eqnarray*}\n\nNote that $\\mathbf{x}-\\boldsymbol{\\mu}$ is the centered $\\mathbf{x}$. Without loss of generality, take $\\boldsymbol{\\mu}=\\mathbf{0}$.\nHence,\n\\begin{eqnarray*}\n   \\mathbf{x}^T \\mathbf{V}\\boldsymbol{\\Delta}^{-2}\\mathbf{V}^T \\mathbf{x} &=& c^2    \\\\\n   \\left(\\mathbf{x}^T\\mathbf{V}\\right) \\boldsymbol{\\Delta}^{-2} \\left(\\mathbf{x}^T\\mathbf{V}\\right)^T &=& c^2 \\\\\n   \\sum_{j=1}^p (\\mathbf{x}^T\\mathbf{v}_j)^2  / \\delta_j^2 &=& c^2\\\\\n   \\sum_{j=1}^p (z_j)^2  / (c^2\\delta_j^2) &=& 1.\n\\end{eqnarray*}\nThe last equation is the equation of an ellipse with axes parallel to the basis of $(z_1,\\ldots, z_p)$ and with half axis lengths $c\\sqrt{\\lambda_j}=c\\delta_j$ with $\\lambda_j$ the $j$th eigen value of $\\boldsymbol{\\Sigma}$.\n\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\npIris +\n  stat_ellipse() +\n  stat_ellipse(level=.68) +\n  stat_ellipse(level=.1)\n```\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-54-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\nThis graphs shows $n=50$ data points on $p=2$ dimensions.  The two ellipses are constant density ellipses for three different values of $c$ (i.e. three different constant densities). The inner ellipse corresponds to the largest constant density and the outer to the smallest constant density. The arrows show the two eigen vectors /  singular vectors and they are scaled according to the square root of the eigen values and they form the axes of the constant density ellipses. It is clear that the first axis is pointing to the larger variance.\n\n## Biplot\n\n-  Because of the close connection between PCA and the SVD, the biplot as discussed before is still meaningful, with the first axis pointing into the direction of largest variance.\n\n## Ovarian Cancer Example\n\nThe ovarian cancer data set consists of proteomics data for 216 patients, 121 of whom have ovarian cancer, and 95 of whom do not. For each subject, the expression of 4000 spectral features is assessed.\nThe first 121 rows consist of data for the cancer patients.\n\n### Importing the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\novarian <- read_csv(\n  \"https://raw.githubusercontent.com/statOmics/HDA2020/data/ovarian.csv\",\n  col_names = FALSE,\n  col_types = cols()\n)\ngrid.arrange(\n  qplot(1:4000,\n    ovarian[1,] |> unlist(),\n    geom=\"line\",\n    ylab=\"centered intensity\",\n    xlab=\"\",main=\"cancer\",\n    ylim=range(ovarian[c(1,2,200,201),])),\n  qplot(1:4000,\n    ovarian[2,] |> unlist(),\n    geom=\"line\",\n    ylab=\"centered intensity\",\n    xlab=\"\",main=\"cancer\",\n    ylim=range(ovarian[c(1,2,200,201),])),\n  qplot(1:4000,\n    ovarian[200,] |> unlist(),\n    geom=\"line\",\n    ylab=\"centered intensity\",\n    xlab=\"\",main=\"Normal\",\n    ylim=range(ovarian[c(1,2,200,201),])),\n  qplot(1:4000,\n    ovarian[200,] |> unlist(),\n    geom=\"line\",\n    ylab=\"centered intensity\",\n    xlab=\"\",main=\"Normal\",\n    ylim=range(ovarian[c(1,2,200,201),])),\n  ncol=1\n  )\n```\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-55-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nCentering\n\n\n::: {.cell}\n\n```{.r .cell-code}\novarian <-  scale(ovarian, scale=FALSE)\ngrid.arrange(\n  qplot(1:4000,\n    ovarian[1,],\n    geom=\"line\",\n    ylab=\"centered intensity\",\n    xlab=\"\",main=\"cancer\",\n    ylim=range(ovarian[c(1,2,200,201),])),\n  qplot(1:4000,\n    ovarian[2,],\n    geom=\"line\",\n    ylab=\"centered intensity\",\n    xlab=\"\",main=\"cancer\",\n    ylim=range(ovarian[c(1,2,200,201),])),\n  qplot(1:4000,\n    ovarian[200,],\n    geom=\"line\",\n    ylab=\"centered intensity\",\n    xlab=\"\",main=\"Normal\",\n    ylim=range(ovarian[c(1,2,200,201),])),\n  qplot(1:4000,\n    ovarian[201,],\n    geom=\"line\",\n    ylab=\"centered intensity\",\n    xlab=\"\",main=\"Normal\",\n    ylim=range(ovarian[c(1,2,200,201),])),\n  ncol=1\n  )\n```\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-56-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n### SVD Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsvdOvarian <- svd(ovarian)\n\nnOvarian <- nrow(ovarian)\nr <- ncol(svdOvarian$v)\n\ntotVar <- sum(svdOvarian$d^2)/(nOvarian-1)\nvars <- data.frame(comp=1:r,var=svdOvarian$d^2/(nOvarian-1)) |>\n  mutate(propVar=var/totVar,cumVar=cumsum(var/totVar))\n\npVar2 <- vars |>\n  ggplot(aes(x=comp:r,y=propVar)) +\n  geom_point() +\n  geom_line() +\n  xlab(\"Component\") +\n  ylab(\"Proportion of Total Variance\")\n\npVar3 <- vars |>\n  ggplot(aes(x=comp:r,y=cumVar)) +\n  geom_point() +\n  geom_line() +\n  xlab(\"Component\") +\n  ylab(\"Cum. prop. of tot. var.\")\n\ngrid.arrange(pVar2, pVar3, nrow=1)\n```\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-57-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nWe see that we can explain a lot of the variability using a few PC's!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nZk <- svdOvarian$u[,1:6]%*%diag(svdOvarian$d[1:6])\ncolnames(Zk) <- paste0(\"Z\",1:6)\nVk <- svdOvarian$v[,1:6]\ncolnames(Vk) <- paste0(\"V\",1:6)\nreduced <- data.frame(Zk,cancer=c(rep(1,121),rep(2,95)))\n\npOv1 <- reduced |>\n  ggplot(aes(x=Z1,y=Z2,col=cancer)) +\n  geom_point()  +\n  theme(legend.position = \"none\")\n\npOv2 <- Vk |>\n  as.data.frame() |>\n  ggplot(aes(x=1:4000,y=V1)) +\n  geom_line() +\n  xlab(\"\")\n\npOv3 <- Vk |>\n  as.data.frame() |>\n  ggplot(aes(x=1:4000,y=V2)) +\n  geom_line() +\n  xlab(\"\")\n\ngrid.arrange(pOv1,pOv2,pOv3,layout_matrix = rbind(c(1,3),c(2,NA)))\n```\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-58-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\nReconstruction of profiles:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ni <- 1\npOv4 <- qplot(1:4000,\n  ovarian[i,],\n  geom=\"line\",\n  ylab=\"centered intensity\",\n  xlab=\"\",main=\"Cancer\",\n  ylim=range(ovarian[c(1,2,200,201),]))\n\npOv5 <- qplot(1:4000,\n  Vk[,1:2] %*%Zk[i,1:2],\n  geom=\"line\",\n  ylab=\"centered intensity\",\n  xlab=\"\",main=\"Reconstructed\",\n  ylim=range(ovarian[c(1,2,200,201),]))\n\n\n\ngrid.arrange(\n  pOv1 +\n    annotate(\"point\", x = reduced[i,1], y = reduced[i,2], colour = \"red\",cex=3),\n  pOv2,\n  pOv3,\n  pOv4,\n  pOv5,\n  layout_matrix = rbind(c(1,2,3),c(4,5,NA)))\n```\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-59-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ni <- 3\npOv4 <- qplot(1:4000,\n  ovarian[i,],\n  geom=\"line\",\n  ylab=\"centered intensity\",\n  xlab=\"\",main=\"Cancer\",\n  ylim=range(ovarian[c(1,2,200,201),]))\n\npOv5 <- qplot(1:4000,\n  Vk[,1:2] %*%Zk[i,1:2],\n  geom=\"line\",\n  ylab=\"centered intensity\",\n  xlab=\"\",main=\"Reconstructed\",\n  ylim=range(ovarian[c(1,2,200,201),]))\n\n\n\ngrid.arrange(\n  pOv1 +\n    annotate(\"point\", x = reduced[i,1], y = reduced[i,2], colour = \"red\",cex=3),\n  pOv2,\n  pOv3,\n  pOv4,\n  pOv5,\n  layout_matrix = rbind(c(1,2,3),c(4,5,NA)))\n```\n\n::: {.cell-output-display}\n![](svd_files/figure-pdf/unnamed-chunk-60-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n# Acknowledgement {-}\n\n- Olivier Thas for sharing his materials of Analysis of High Dimensional Data 2019-2020, which I used as the starting point for this chapter.\n\n- Steven Brunton & Nathan Kutz (2017). Data Driven Science & Engineering - Machine Learning, Dynamical Systems, and Control. Chapter 1: Singular Value Decomposition. [databook.pdf](http://databookuw.com/databook.pdf)\n\n\n# Session info {-}\n\n<details><summary>Session info</summary>\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] \"2026-09-16 09:43:25 CEST\"\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> - Session info ---------------------------------------------------------------\n#>  setting  value\n#>  version  R version 4.6.1 (2026-06-24)\n#>  os       macOS Tahoe 26.1\n#>  system   aarch64, darwin23\n#>  ui       X11\n#>  language (EN)\n#>  collate  nl_BE.UTF-8\n#>  ctype    nl_BE.UTF-8\n#>  tz       Europe/Brussels\n#>  date     2026-09-16\n#>  pandoc   3.10.2 @ /opt/homebrew/bin/ (via rmarkdown)\n#>  quarto   1.9.37 @ /usr/local/bin/quarto\n#> \n#> - Packages -------------------------------------------------------------------\n#>  package      * version    date (UTC) lib source\n#>  assertthat     0.2.1      2019-03-21 [1] CRAN (R 4.6.0)\n#>  bit            4.6.0      2025-03-06 [1] CRAN (R 4.6.0)\n#>  bit64          4.8.2      2026-05-19 [1] CRAN (R 4.6.0)\n#>  bitops         1.0-9      2024-10-03 [1] CRAN (R 4.6.0)\n#>  bmp            0.3.1      2025-09-22 [1] CRAN (R 4.6.0)\n#>  chromote       0.5.1      2025-04-24 [1] CRAN (R 4.6.0)\n#>  cli            3.6.6      2026-04-09 [1] CRAN (R 4.6.0)\n#>  crayon         1.5.3      2024-06-20 [1] CRAN (R 4.6.0)\n#>  crosstalk      1.2.2      2025-08-26 [1] CRAN (R 4.6.0)\n#>  curl           7.1.0      2026-04-22 [1] CRAN (R 4.6.0)\n#>  data.table     1.18.4     2026-05-06 [1] CRAN (R 4.6.0)\n#>  digest         0.6.39     2025-11-19 [1] CRAN (R 4.6.0)\n#>  downloader   * 0.4.1      2025-03-26 [1] CRAN (R 4.6.0)\n#>  dplyr        * 1.2.1      2026-04-03 [1] CRAN (R 4.6.0)\n#>  emo            0.0.0.9000 2026-09-15 [1] Github (hadley/emo@3f03b11)\n#>  evaluate       1.0.5      2025-08-27 [1] CRAN (R 4.6.0)\n#>  farver         2.1.2      2024-05-13 [1] CRAN (R 4.6.0)\n#>  fastmap        1.2.0      2024-05-15 [1] CRAN (R 4.6.0)\n#>  forcats      * 1.0.1      2025-09-25 [1] CRAN (R 4.6.0)\n#>  generics       0.1.4      2025-05-09 [1] CRAN (R 4.6.0)\n#>  ggmap        * 4.0.2      2025-09-11 [1] CRAN (R 4.6.0)\n#>  ggplot2      * 4.0.3      2026-04-22 [1] CRAN (R 4.6.0)\n#>  glue           1.8.1      2026-04-17 [1] CRAN (R 4.6.0)\n#>  gridExtra    * 2.3.1      2026-06-25 [1] CRAN (R 4.6.1)\n#>  gtable         0.3.6      2024-10-25 [1] CRAN (R 4.6.0)\n#>  hms            1.1.4      2025-10-17 [1] CRAN (R 4.6.0)\n#>  htmltools      0.5.9      2025-12-04 [1] CRAN (R 4.6.0)\n#>  htmlwidgets    1.6.4      2023-12-06 [1] CRAN (R 4.6.0)\n#>  httr           1.4.8      2026-02-13 [1] CRAN (R 4.6.0)\n#>  igraph         2.3.3      2026-06-26 [1] CRAN (R 4.6.1)\n#>  imager       * 1.0.8      2025-12-23 [1] CRAN (R 4.6.0)\n#>  jpeg           0.1-11     2025-03-21 [1] CRAN (R 4.6.0)\n#>  jsonlite       2.0.0      2025-03-27 [1] CRAN (R 4.6.0)\n#>  knitr          1.51       2025-12-20 [1] CRAN (R 4.6.0)\n#>  labeling       0.4.3      2023-08-29 [1] CRAN (R 4.6.0)\n#>  later          1.4.8      2026-03-05 [1] CRAN (R 4.6.0)\n#>  lazyeval       0.2.3      2026-04-04 [1] CRAN (R 4.6.0)\n#>  lifecycle      1.0.5      2026-01-08 [1] CRAN (R 4.6.0)\n#>  lubridate    * 1.9.5      2026-02-04 [1] CRAN (R 4.6.0)\n#>  magrittr     * 2.0.5      2026-04-04 [1] CRAN (R 4.6.0)\n#>  MASS           7.3-65     2025-02-28 [1] CRAN (R 4.6.1)\n#>  otel           0.2.0      2025-08-29 [1] CRAN (R 4.6.0)\n#>  pillar         1.11.1     2025-09-17 [1] CRAN (R 4.6.0)\n#>  pixmap       * 0.4-14     2025-07-26 [1] CRAN (R 4.6.0)\n#>  pkgconfig      2.0.3      2019-09-22 [1] CRAN (R 4.6.0)\n#>  plotly       * 4.12.0     2026-01-24 [1] CRAN (R 4.6.0)\n#>  plyr           1.8.9      2023-10-02 [1] CRAN (R 4.6.0)\n#>  png            0.1-9      2026-03-15 [1] CRAN (R 4.6.0)\n#>  processx       3.9.0      2026-04-22 [1] CRAN (R 4.6.0)\n#>  promises       1.5.0      2025-11-01 [1] CRAN (R 4.6.0)\n#>  purrr        * 1.2.2      2026-04-10 [1] CRAN (R 4.6.0)\n#>  R6             2.6.1      2025-02-15 [1] CRAN (R 4.6.0)\n#>  RColorBrewer   1.1-3      2022-04-03 [1] CRAN (R 4.6.0)\n#>  Rcpp           1.1.1-1.1  2026-04-24 [1] CRAN (R 4.6.0)\n#>  readbitmap     0.1.5      2018-06-27 [1] CRAN (R 4.6.0)\n#>  readr        * 2.2.0      2026-02-19 [1] CRAN (R 4.6.0)\n#>  rlang          1.2.0      2026-04-06 [1] CRAN (R 4.6.0)\n#>  rmarkdown      2.31       2026-03-26 [1] CRAN (R 4.6.0)\n#>  S7             0.2.2      2026-04-22 [1] CRAN (R 4.6.0)\n#>  scales         1.4.0      2025-04-24 [1] CRAN (R 4.6.0)\n#>  sessioninfo    1.2.4      2026-06-04 [1] CRAN (R 4.6.0)\n#>  stringi        1.8.7      2025-03-27 [1] CRAN (R 4.6.0)\n#>  stringr      * 1.6.0      2025-11-04 [1] CRAN (R 4.6.0)\n#>  tibble       * 3.3.1      2026-01-11 [1] CRAN (R 4.6.0)\n#>  tidyr        * 1.3.2      2025-12-19 [1] CRAN (R 4.6.0)\n#>  tidyselect     1.2.1      2024-03-11 [1] CRAN (R 4.6.0)\n#>  tidyverse    * 2.0.0      2023-02-22 [1] CRAN (R 4.6.0)\n#>  tiff           0.1-12     2023-11-28 [1] CRAN (R 4.6.0)\n#>  timechange     0.4.0      2026-01-29 [1] CRAN (R 4.6.0)\n#>  tzdb           0.5.0      2025-03-15 [1] CRAN (R 4.6.0)\n#>  vctrs          0.7.3      2026-04-11 [1] CRAN (R 4.6.0)\n#>  viridisLite    0.4.3      2026-02-04 [1] CRAN (R 4.6.0)\n#>  vroom          1.7.1      2026-03-31 [1] CRAN (R 4.6.0)\n#>  webshot2       0.1.2      2025-04-23 [1] CRAN (R 4.6.0)\n#>  websocket      1.4.4      2025-04-10 [1] CRAN (R 4.6.0)\n#>  withr          3.0.3      2026-06-19 [1] CRAN (R 4.6.0)\n#>  xfun           0.59       2026-06-19 [1] CRAN (R 4.6.0)\n#>  yaml           2.3.12     2025-12-10 [1] CRAN (R 4.6.0)\n#> \n#>  [1] /Library/Frameworks/R.framework/Versions/4.6/Resources/library\n#>  * -- Packages attached to the search path.\n#> \n#> ------------------------------------------------------------------------------\n```\n\n\n:::\n:::\n\n\n</details>\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}