{
  "hash": "fed757a9c1c9a31dbc2b4e45dd067750",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"1. Introduction to High Dimensional Data Analysis\"\nauthor: \"Lieven Clement\"\ndate: \"statOmics, Ghent University (https://statomics.github.io)\"\nformat:\n  html: default\n  pdf: default\n---\n\n\n\n\n# Introduction\n\n\n\n- We live in a big data era\n- Massive Datasets on our location, surfing behavior, consumer data, social media, ...\n- Life Sciences: advent of high throughput technologies has enabled us to measure brain activity (brain images) as well as the expression of thousands of genes, proteins, ... for each subject or even single cell.\n- Industry: process control with many sensors that follow process in real time...\n- Data drive journalism\n- ...\n\nChallenge: We have to learn from high dimensional data!\n\n---\n\n## What are high dimensional data?\n\n- We typically observe multiple variables/features (p) for each subject/experimental unit $i=1,\\ldots,n$ i.e.\n\\[ \\mathbf{x}_i^T=[x_{i1},\\ldots,x_{ip}]\\]\n\n- Multivariate statistics have a long history, but were designed for the $n>>>p$ case,\n\n- Nowadays many high throughput technologies generate multivariate data with many variables (large $p$) as compared to the number of independent replicates or samples (sample size $n$), resulting in **{high-dimensional data}**, which is characterised by\n  \\[\n     p >>> n.\n  \\]\n\n-  New statistical methods for dealing with the $p >>> n$ case have been developed in the last 20 years.  Some of them are adaptations of multivariate methods.\n\n---\n\nIssues with high-dimensional data:\n\n- *Computational problems*: large matrices, numerical accuracy of computers become an issue\n- *Classical asymptotic theory does not hold* for $p\\rightarrow\\infty$ as $n \\rightarrow \\infty$\n- *Model (or feature) selection* requires specialised methods to deal with the enormous number of possible models. (e.g. in linear regression with p potential predictors: $2^p$ possible models)\n- Models that can potentially depend on large-p predictors are vulnerable to *huge overfitting*.\n- In searching for associations between an outcome and large p potential exploratory variables, we are at risk to make *many false discoveries*\n\n- The *Curse of Dimensionality* may cause a prediction model to become useless. ($n$ data points become sparse in large-$p$ dimensional space)\n\n---\n\n# Important tasks in high dimensional data analysis?\n\n## Example:   Kang et al. (2018)’s droplet-based scRNA-seq data of PBMCs cells from 8 lupus patients measured before and after 6h-treatment with INF-$\\beta$ (16 samples in total).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\n## Packages to load and visualize the single-cell data\nlibrary(ExperimentHub)\nlibrary(scater)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Load Kang single-cell data from ExperimentHub\neh <- ExperimentHub()\n```\n\n```{.r .cell-code}\nsce <- eh[[\"EH2259\"]]\n\nsce\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> class: SingleCellExperiment \n#> dim: 35635 29065 \n#> metadata(0):\n#> assays(1): counts\n#> rownames(35635): MIR1302-10 FAM138A ... MT-ND6 MT-CYB\n#> rowData names(2): ENSEMBL SYMBOL\n#> colnames(29065): AAACATACAATGCC-1 AAACATACATTTCC-1 ... TTTGCATGGTTTGG-1\n#>   TTTGCATGTCTTAC-1\n#> colData names(5): ind stim cluster cell multiplets\n#> reducedDimNames(1): TSNE\n#> mainExpName: NULL\n#> altExpNames(0):\n```\n\n\n:::\n:::\n\n\n- Data on gene expression of 35635 genes of 29065 cells.\n\n\n## Data exploration and dimensionality reduction\n\n- Visualisation is a first essential step to learn from data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounts(sce)[18990:19000,9:20]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> 11 x 12 sparse Matrix of class \"dgCMatrix\"\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>                                                    \n#> RP11-467L20.10   . .   . . .   .  .  .  . .   .   .\n#> MYRF             . .   . . .   .  .  .  . .   .   .\n#> TMEM258          . .   3 . .   .  1  1  . .   .   .\n#> FEN1             . .   . . .   .  .  .  . .   .   .\n#> FADS2            . .   . . .   .  .  .  . .   .   .\n#> FADS1            . .   . . .   .  .  .  . .   .   .\n#> FADS3            . .   . . .   .  .  .  . .   .   .\n#> RAB3IL1          . .   . . .   .  .  .  . .   .   .\n#> BEST1            1 .   . . .   .  1  .  . .   1   1\n#> FTH1           163 8 271 4 5 174 38 58 31 3 663 612\n#> AP003733.1       . .   . . .   .  .  .  . .   .   .\n```\n\n\n:::\n:::\n\n\n- It is impossible to learn about the structure in the data by staring at the data matrix.\n- We should be able to explore the data in a low dimensional projection\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplotReducedDim(sce, dimred=\"TSNE\", colour_by=\"cell\")\n```\n\n::: {.cell-output-display}\n![](intro_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n\n```{.r .cell-code}\nplotReducedDim(sce, dimred=\"TSNE\", colour_by=\"stim\")\n```\n\n::: {.cell-output-display}\n![](intro_files/figure-html/unnamed-chunk-4-2.png){width=672}\n:::\n:::\n\n\n- Note, that we see huge effect of treatment. If I see this I am always on my guard!\n- We contacted the authors and learned that all control cells were sequenced in a first run and all stimulated cells were on a second sequencing run. So the large effect might be an effect of batch!\n\n## Prediction\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplotReducedDim(sce, dimred=\"TSNE\", colour_by=\"cell\")\n```\n\n::: {.cell-output-display}\n![](intro_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n- In single cell analysis it is key to identify cell types in scRNA-seq data sets before in-depth investigations of their functional and pathological roles.\n\n- Use models that were build based on reference data sets to predict cell types in new data sets based on their gene expression pattern\n\n- Problem: we have 35635 genes at our disposal to build this prediction model!\n\n- Other examples\n\n  - Prediction of risk on mortality is used on a daily basis in intensive care units to prioritise patient care.\n\n  - Facebook: predict the identity of the faces of people that are on an new image that is uploaded.\n\n  - Netflix: Suggest movies that you would like\n\n## Large scale hypothesis testing\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplotReducedDim(sce, dimred=\"TSNE\", colour_by=\"cell\", shape_by=\"stim\")\n```\n\n::: {.cell-output-display}\n![](intro_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n- Which genes are differentially expressed between control and stimulated treatment  (assess in each cell type)\n- For which genes we see that the differential expression according to treatment is changing according to the cell type (interaction)\n- We have to model the gene expression for each gene\n\n$$\n\\left \\{\n\\begin{array}{lcl}\ny_{ig} &\\sim& NB(\\mu_{ig}, \\phi_{g})\\\\\nE[y_{ig}] &=& \\mu_{ig}\\\\\n\\log(\\mu_{ig}) &=& \\eta_{ig}\\\\\n\\eta_{ig} &=& \\beta_{0,g} + \\sum\\limits_{c=2}^C \\beta_{c,g} X_{ic} + \\beta_{s,g} X_{is} + \\sum\\limits_{c=2}^C \\beta_{c:s,g} X_{ic} X_{is}  + \\sum\\limits_{e=2}^E \\beta_{e,g} X_{ie} + \\alpha_{ig}\n\\end{array} \\right.\n$$\n\nWith\n\n- Cell type $c=2\\ldots C$ and $X_{ic}$ is a dummy variable that $X_{ic}=1$ if cell $i$ is of cell type c and $X_{ic}=0$ otherwise. Note that cell type $c=1$ is the reference cell type\n\n- Indicator $X_{is}$ indicates if cell $i$ was stimulated $X_{is}=1$ or not $X_{is}=0$. So the control treatment is the reference treatment.\n\n- Experimental unit $e=2\\ldots E$ and $X_{ie}$ a dummy variable that $X_{ie}=1$ if cell $i$ originates of experimental unit (subject) $e$ and $X_{ie}=0$ otherwise. Note that cell type $e=1$ is the reference experimental unit. \n\n- $\\alpha_{ig}$ a cell specific and gene specific normalisation factor\n\n\nSuppose we want to test if the effect of the stimulus (average difference in expression between stimulated and non stimulated cells) is different in cell type c than in the reference cell type 1?\n\n- $H_0: \\beta_{c:s,g} = 0$\n- $H_1: \\beta_{c:s,g} \\neq 0$\n\n\n- We have to assess this for 35635 genes!\n- If we assess each test at the 5% level we can expect 0.05 * 35635 = 1782 false positives.\n\n$\\rightarrow$ massive multiple testing problem!\n\n\nNote, that we cannot differentiate between batch and treatment because of the flaw in the experimental design!\n\nOther examples\n\n- Find regions (voxels) in the brain (on brain image) that are associated with a certain condition/treatment\n- Evaluation of trading rules\n\n\n\n---\n\n\n# Linear regression\n\n- Linear regression is a very important statistical tool to study the association between variables and to build prediction models.\n\n## Toy-Data\n\nConsider the following toy-dataset with 3 observation (X,Y):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\ndata <- data.frame(x=1:3,y=c(1,2,2))\ndata\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>   x y\n#> 1 1 1\n#> 2 2 2\n#> 3 3 2\n```\n\n\n:::\n:::\n\n\n## Model\n\n### Scalar form\n\n- Consider a vector of predictors $\\mathbf{x}=(x_1,\\ldots,x_p)$ and\n- a real-valued response $Y$\n- then the linear regression model can be written as\n\\[\nY=f(\\mathbf{x}) +\\epsilon=\\beta_0+\\sum\\limits_{j=1}^p x_j\\beta_j + \\epsilon\n\\]\nwith i.i.d. $\\epsilon\\sim N(0,\\sigma^2)$\n- We will often work on mean centered variables: $Y_c = Y-\\bar{Y}$ and $X_c = X - \\bar{X}$, then the intercept is dropped from the model:\n\\[\nY_c=f(\\mathbf{x}_c) +\\epsilon=\\sum\\limits_{j=1}^p x_{cj}\\beta_j + \\epsilon\n\\]\n\n### Scalar model for the toy dataset\n\n$$\ny_i=\\beta_0+\\beta_1x + \\epsilon_i\n$$\n\nIf we write the model for each observation:\n\n$$\n\\begin{array} {lcl}\n1 &=& \\beta_0+\\beta_1 1  + \\epsilon_1 \\\\\n2 &=& \\beta_0 + \\beta_1 2 + \\epsilon_2 \\\\\n2 &=& \\beta_0+\\beta_1 3+ \\epsilon_3 \\\\\n\\end{array}\n$$\n\n\n### Vector/Matrix form\n\n- $n$ observations $(\\mathbf{x}_1,y_1) \\ldots (\\mathbf{x}_n,y_n)$ with $\\mathbf{x}_1^T=[\\begin{array}{cccc} 1& x_1& \\ldots& x_p\\end{array}]$\n- Regression in matrix notation\n\\[\\mathbf{Y}=\\mathbf{X\\beta} + \\mathbf{\\epsilon}\\]\nwith $\\mathbf{Y}=\\left[\\begin{array}{c}y_1\\\\ \\vdots\\\\y_n\\end{array}\\right]$,\n$\\mathbf{X}=\\left[\\begin{array}{cccc} 1&x_{11}&\\ldots&x_{1p}\\\\\n\\vdots&\\vdots&&\\vdots\\\\\n1&x_{n1}&\\ldots&x_{np}\n\\end{array}\\right]$ or $\\mathbf{X}=\\left[\\begin{array}{c} \\mathbf{x}_1^T\\\\\\vdots\\\\\\mathbf{x}_n^T\\end{array}\\right]$,\n$\\boldsymbol{\\beta}=\\left[\\begin{array}{c}\\beta_0\\\\ \\vdots\\\\ \\beta_p\\end{array}\\right]$ and\n$\\mathbf{\\epsilon}=\\left[\\begin{array}{c} \\epsilon_1 \\\\ \\vdots \\\\ \\epsilon_n\\end{array}\\right]$\n\nNote, that upon centering of $\\mathbf{X}$ and $\\mathbf{Y}$ the 1 is dropped from each $\\mathbf{x}_i$ and thus the column of 1 is dropped in $\\mathbf{X}_c$\n\n### Matrix form for toy dataset\n\nWe can also write this in matrix form\n\n$$\n\\mathbf{Y} = \\mathbf{X}\\boldsymbol{\\beta}+\\boldsymbol{\\epsilon}\n$$\n\nwith\n\n$$\n\\mathbf{Y}=\\left[\n\\begin{array}{c}\n1\\\\\n2\\\\\n2\\\\\n\\end{array}\\right],\n\\quad\n\\mathbf{X}= \\left[\n\\begin{array}{cc}\n1&1\\\\\n1&2\\\\\n1&3\\\\\n\\end{array}\n\\right],\n\\quad \\boldsymbol{\\beta} = \\left[\n\\begin{array}{c}\n\\beta_0\\\\\n\\beta_1\\\\\n\\end{array}\n\\right]\n\\quad\n\\text{and}\n\\quad\n\\boldsymbol{\\epsilon}=\n\\left[\n\\begin{array}{c}\n\\epsilon_1\\\\\n\\epsilon_2\\\\\n\\epsilon_3\n\\end{array}\n\\right]\n$$\n\n\n\n\n\n---\n\n## Interpretation\n\nFrom the linear regression we get\n\\[\n  E[Y \\mid \\mathbf{x}] = \\mathbf{x}^T\\boldsymbol{\\beta} .\n\\]\n\n- Hence, the $\\beta$ parameters relate the predictor $\\mathbf{x}$ to the mean outcome.\n- If we know the covariate pattern $\\mathbf{x}$ we can use the model to\npredict $Y$.\n\nFor a model with a single predictor we obtain\n\n\\[\nE[Y \\mid x] = \\beta_0 + \\beta_1 x\n\\]\nand\n\\[\n \\beta_1 = E[Y\\mid x+1] - E[Y\\mid x] = \\beta_0 + \\beta_1 (x+1) - \\beta_0 - \\beta_1 x.\n\\]\n\nIn this course we will typically center Y and X and then we get the following\n\n\\[\n  E[Y_c \\mid x_c] = \\beta_1 x_c\n\\]\nand\n\\[\n \\beta_1 = E[Y_c\\mid x_c+1] - E[Y_c\\mid x_c] .\n\\]\n\nNote, that the estimator for $\\beta_1$ will be exactly same when estimated based on the models with/or without centering.\n\n- The parameter  $\\beta_1$ has an interpretation as the average difference in the outcome between subjects that differ with one unit for the predictor.\n\n- The parameter  $\\beta_1$  does not say much about individual outcomes. The residual variance $\\sigma^2$ determines how much individual outcomes vary about the mean outcome.\n\nThe $\\beta$ parameters are used to measure association, but a $\\beta \\neq 0$ does not necessarily mean that the model will give good predictions.\n\n$$\n\\hat Y = \\mathbf{x}^T \\hat \\beta\n$$\n- In Chapter 3 will we will discuss the prediction problem for high dimensional data\n\nModel fit and predictions based on the toy dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm1 <- lm(y~x,data)\ndata$yhat <- lm1$fitted\n\ndata |>\n  ggplot(aes(x,y)) +\n  geom_point() +\n  ylim(0,4) +\n  xlim(0,4) +\n  stat_smooth(method = \"lm\", color = \"red\", fullrange = TRUE) +\n  geom_point(aes(x=x, y =yhat), pch = 2, size = 3, color = \"red\") +\n  geom_segment(data = data, aes(x = x, xend = x, y = y, yend = yhat), lty = 2 )\n```\n\n::: {.cell-output-display}\n![](intro_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n---\n\n\n- In a Chapter 6 we will discuss the problem of large scale hypothesis testing: testing many hypotheses in a single study (ten to hundred thousands of hypotheses).\n\n    - A statistical test is constructed to control the type I error rate at the significance level $\\alpha$ to assess the null hypothesis that there is no association between a predictor and the outcome vs the alternative hypothesis that there is an association between a predictor and the outcome.\n\n    $$\n    H_0: \\beta_1 = 0 \\text{ vs }H_1:\\beta_1 \\neq 0.\n    $$\n\n    - However, when many hypotheses are to be tested in a single study, the probability to find false associations is no longer controlled if p-values are compared to the significance level $\\alpha$.\n\n    - We will later introduce the concept of false discovery rates to overcome the problem.\n\n## Least Squares (LS)\n\n- Minimize the residual sum of squares\n\\begin{eqnarray*}\nRSS(\\boldsymbol{\\beta})&=&\\sum\\limits_{i=1}^n e^2_i\\\\\\\\\n&=&\\sum\\limits_{i=1}^n \\left(y_i-\\beta_0-\\sum\\limits_{j=1}^p x_{ij}\\beta_j\\right)^2\n\\end{eqnarray*}\n\n- or in matrix notation\n\\begin{eqnarray*}\nRSS(\\boldsymbol{\\beta})&=&\\mathbf{e}^T\\mathbf{e}\\\\\\\\\n&=& \\left[\\begin{array}{ccc} e_1 &\\ldots& e_n \\end{array}\\right]\\left[\\begin{array}{c}e_1\\\\\\vdots\\\\e_n\\end{array}\\right]\\\\\n&=& e_1^2 + e_2^2 + \\ldots + e_n^2\\\\\\\\\n&=&(\\mathbf{Y}-\\mathbf{X\\beta})^T(\\mathbf{Y}-\\mathbf{X\\beta})\\\\\\\\\n&=&\\Vert \\mathbf{Y}-\\mathbf{X\\beta}\\Vert^2_2\\\\\n\\end{eqnarray*}\nwith the $L_2$-norm of a $p$-dim. vector $v$ $\\Vert \\mathbf{v} \\Vert_2=\\sqrt{v_1^2+\\ldots+v_p^2}$\n$\\rightarrow$ $\\hat{\\boldsymbol{\\beta}}=\\text{argmin}_\\beta \\Vert \\mathbf{Y}-\\mathbf{X\\beta}\\Vert^2_2$\n\n\n---\n\n### Minimize RSS\n\\[\n\\begin{array}{ccc}\n\\frac{\\partial RSS}{\\partial \\boldsymbol{\\beta}}&=&\\mathbf{0}\\\\\\\\\n\\frac{(\\mathbf{Y}-\\mathbf{X\\beta})^T(\\mathbf{Y}-\\mathbf{X}\\boldsymbol{\\beta})}{\\partial \\boldsymbol{\\beta}}&=&\\mathbf{0}\\\\\\\\\n-2\\mathbf{X}^T(\\mathbf{Y}-\\mathbf{X}\\boldsymbol{\\beta})&=&\\mathbf{0}\\\\\\\\\n\\mathbf{X}^T\\mathbf{X\\beta}&=&\\mathbf{X}^T\\mathbf{Y}\\\\\\\\\n\\hat{\\boldsymbol{\\beta}}&=&(\\mathbf{X}^T\\mathbf{X})^{-1}\\mathbf{X}^T\\mathbf{Y}\n\\end{array}\n\\]\n\nIt can be shown that the estimator is unbiased:\n\n$$\nE[\\hat{\\boldsymbol{\\beta}}]=\\boldsymbol{\\beta}\n$$\n\n\n---\n\n\n### Projection\n\nThere is also another picture to regression:\n\n- Instead of plotting each observation $i= 1 \\ldots n$ as a data-point in $\\mathbb{R}^p$ with dimensions $1 \\ldots p$ for every variable/feature that is recorded for each observation\n\n- We can also plot $\\mathbf{Y}$, $\\hat{\\mathbf{Y}}$ and each column of $\\mathbf{X}$: $\\mathbf{X}_j$ with $j=1 \\ldots p$ as a vector in $\\mathbb{R}^n$ with dimensions $1 \\ldots n$ for every observation.\n\n- In this representation linear regression can be interpreted as a projection of the vector $\\mathbf{Y}$ onto the subspace of $\\mathbb{R}^n$ that is spanned by the vectors for the predictors $\\mathbf{X}_1 \\ldots \\mathbf{X}_p$.\n\n- The space $\\mathbf{X}_1 \\ldots \\mathbf{X}_p$ is also referred to as the column space of $\\mathbf{X}$, the space that consists of all linear combinations of the vectors of the predictors or columns $\\mathbf{X}_1 \\ldots \\mathbf{X}_p$.\n\n\n#### Intermezzo: Projection of vector on X  and Y axis\n\n$$\n\\mathbf{e}=\\left[\\begin{array}{c} e_1\\\\e_2\\end{array}\\right], \\mathbf{u}_1 =  \\left[\\begin{array}{c} 1\\\\0\\end{array}\\right], \\mathbf{u}_2 =  \\left[\\begin{array}{c} 0\\\\1\\end{array}\\right]\n$$\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](intro_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n\n1. Projection of error on x-axis\n\n\\begin{eqnarray*}\n\\mathbf{u}_1^T \\mathbf{e} &=& \\Vert \\mathbf{u}_1\\Vert_2  \\Vert \\mathbf{e}_1\\Vert_2 \\cos <\\mathbf{u}_1,\\mathbf{e}_1>\\\\\n&=&\\left[\\begin{array}{cc} 1&0\\end{array}\\right] \\left[\\begin{array}{c} e_1\\\\e_2\\end{array}\\right]\\\\ &=& 1\\times e_1 + 0 \\times e_2 \\\\\n&=& e_1\\\\\n\\end{eqnarray*}\n\n2. Projection of error on y-axis\n\n\\begin{eqnarray*}\n\\mathbf{u}_2^T \\mathbf{e} &=& \\left[\\begin{array}{cc} 0&1\\end{array}\\right] \\left[\\begin{array}{c} e_1\\\\e_2\\end{array}\\right]\\\\ &=& 0\\times e_1 + 1 \\times e_2 \\\\\n&=& e_2\n\\end{eqnarray*}\n\n3. Projection of error on itself\n\n\n\\begin{eqnarray*}\n\\mathbf{e}^T \\mathbf{e} &=&\\left[\\begin{array}{cc} e_1&e_2\\end{array}\\right] \\left[\\begin{array}{c} e_1\\\\e_2\\end{array}\\right]\\\\\n&=&e_1^2+e_2^2\\\\\n&=&\\Vert e \\Vert^2_2 \\rightarrow \\text{ Pythagorean theorem}\n\\end{eqnarray*}\n\n---\n\n#### Interpretation of least squares as a projection\n\nFitted values:\n\n$$\n\\begin{array}{lcl}\n\\hat{\\mathbf{Y}} &=& \\mathbf{X}\\hat{\\boldsymbol{\\beta}}\\\\\n&=& \\mathbf{X} (\\mathbf{X}^T\\mathbf{X})^{-1}\\mathbf{X}^T\\mathbf{Y}\\\\\n&=& \\mathbf{HY}\n\\end{array}\n$$\nwith $\\mathbf{H}$ the projection matrix also referred to as the hat matrix.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nX <- model.matrix(~x,data)\nX\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>   (Intercept) x\n#> 1           1 1\n#> 2           1 2\n#> 3           1 3\n#> attr(,\"assign\")\n#> [1] 0 1\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nXtX <- t(X)%*%X\nXtX\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>             (Intercept)  x\n#> (Intercept)           3  6\n#> x                     6 14\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nXtXinv <- solve(t(X)%*%X)\nXtXinv\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>             (Intercept)    x\n#> (Intercept)    2.333333 -1.0\n#> x             -1.000000  0.5\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nH <- X %*% XtXinv %*% t(X)\nH\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>            1         2          3\n#> 1  0.8333333 0.3333333 -0.1666667\n#> 2  0.3333333 0.3333333  0.3333333\n#> 3 -0.1666667 0.3333333  0.8333333\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nY <- data$y\nYhat <- H%*%Y\nYhat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>       [,1]\n#> 1 1.166667\n#> 2 1.666667\n#> 3 2.166667\n```\n\n\n:::\n:::\n\n\n\n- We can also interpret the fit as the projection of the $n\\times 1$ vector $\\mathbf{Y}$ on the column space of the matrix $\\mathbf{X}$.\n\n- So each column in $\\mathbf{X}$ is also an $n\\times 1$ vector.\n\n- For the toy example n=3 and p=2.\n  The other picture to linear regression is to consider $X_0$, $X_1$ and $Y$ as vectors in the space of the data $\\mathbb{R}^n$, here $\\mathbb{R}^3$ because we have three data points.\nSo the column space of X is a plane in the three dimensional space.\n\n\\[\n\\hat{\\mathbf{Y}} = \\mathbf{X} (\\mathbf{X}^T\\mathbf{X})^{-1} \\mathbf{X}^T \\mathbf{Y}\n\\]\n\n1. Plane spanned by column space:\nThe other picture to linear regression is to consider $X_0$, $X_1$ and $Y$ as vectors in the space of the data $\\mathbb{R}^n$, here $\\mathbb{R}^3$ because we have three data points.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\noriginRn <- data.frame(X1=0,X2=0,X3=0)\ndata$x0 <- 1\ndataRn <- data.frame(t(data))\n\nlibrary(plotly)\n\np1 <- plot_ly(\n    originRn,\n    x = ~ X1,\n    y = ~ X2,\n    z= ~ X3, name=\"origin\") |>\n  add_markers(type=\"scatter3d\") |>\n  layout(\n    scene = list(\n      aspectmode=\"cube\",\n      xaxis = list(range=c(-4,4)), yaxis = list(range=c(-4,4)), zaxis = list(range=c(-4,4))\n      )\n    )\np1 <- p1 |>\n  add_trace(\n    x = c(0,1),\n    y = c(0,0),\n    z = c(0,0),\n    mode = \"lines\",\n    line = list(width = 5, color = \"grey\"),\n    type=\"scatter3d\",\n    name = \"obs1\") |>\n  add_trace(\n    x = c(0,0),\n    y = c(0,1),\n    z = c(0,0),\n    mode = \"lines\",\n    line = list(width = 5, color = \"grey\"),\n    type=\"scatter3d\",\n    name = \"obs2\") |>\n  add_trace(\n    x = c(0,0),\n    y = c(0,0),\n    z = c(0,1),\n    mode = \"lines\",\n    line = list(width = 5, color = \"grey\"),\n    type=\"scatter3d\",\n    name = \"obs3\") |>\n  add_trace(\n    x = c(0,1),\n    y = c(0,1),\n    z = c(0,1),\n    mode = \"lines\",\n    line = list(width = 5, color = \"black\"),\n    type=\"scatter3d\",\n    name = \"X1\") |>\n    add_trace(\n    x = c(0,1),\n    y = c(0,2),\n    z = c(0,3),\n    mode = \"lines\",\n    line = list(width = 5, color = \"black\"),\n    type=\"scatter3d\",\n    name = \"X2\")\np1\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-c9c3675095e18e085bce\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-c9c3675095e18e085bce\">{\"x\":{\"visdat\":{\"1375e3a121d4c\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"1375e3a121d4c\",\"attrs\":{\"1375e3a121d4c\":{\"x\":{},\"y\":{},\"z\":{},\"name\":\"origin\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter3d\",\"mode\":\"markers\",\"inherit\":true},\"1375e3a121d4c.1\":{\"x\":[0,1],\"y\":[0,0],\"z\":[0,0],\"name\":\"obs1\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"grey\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.2\":{\"x\":[0,0],\"y\":[0,1],\"z\":[0,0],\"name\":\"obs2\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"grey\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.3\":{\"x\":[0,0],\"y\":[0,0],\"z\":[0,1],\"name\":\"obs3\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"grey\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.4\":{\"x\":[0,1],\"y\":[0,1],\"z\":[0,1],\"name\":\"X1\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"black\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.5\":{\"x\":[0,1],\"y\":[0,2],\"z\":[0,3],\"name\":\"X2\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"black\"},\"type\":\"scatter3d\",\"inherit\":true}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"scene\":{\"aspectmode\":\"cube\",\"xaxis\":{\"range\":[-4,4],\"title\":\"X1\"},\"yaxis\":{\"range\":[-4,4],\"title\":\"X2\"},\"zaxis\":{\"range\":[-4,4],\"title\":\"X3\"}},\"hovermode\":\"closest\",\"showlegend\":true},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"x\":[0],\"y\":[0],\"z\":[0],\"name\":\"origin\",\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"rgba(31,119,180,1)\",\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,0],\"z\":[0,0],\"name\":\"obs1\",\"mode\":\"lines\",\"line\":{\"color\":\"grey\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(255,127,14,1)\",\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[0,0],\"y\":[0,1],\"z\":[0,0],\"name\":\"obs2\",\"mode\":\"lines\",\"line\":{\"color\":\"grey\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(44,160,44,1)\",\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[0,0],\"y\":[0,0],\"z\":[0,1],\"name\":\"obs3\",\"mode\":\"lines\",\"line\":{\"color\":\"grey\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(214,39,40,1)\",\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,1],\"z\":[0,1],\"name\":\"X1\",\"mode\":\"lines\",\"line\":{\"color\":\"black\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(148,103,189,1)\",\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,2],\"z\":[0,3],\"name\":\"X2\",\"mode\":\"lines\",\"line\":{\"color\":\"black\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(140,86,75,1)\",\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n2. Vector of Y:\n\nActual values of $\\mathbf{Y}$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata$y\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 1 2 2\n```\n\n\n:::\n:::\n\n\n\\[\n\\mathbf{Y}=\\left[\\begin{array}{c}\n1 \\\\\n2 \\\\\n2\n\\end{array}\\right]\n\\]\n\n\n::: {.cell}\n\n```{.r .cell-code}\np2 <- p1 |>\n  add_trace(\n    x = c(0,Y[1]),\n    y = c(0,Y[2]),\n    z = c(0,Y[3]),\n    mode = \"lines\",\n    line = list(width = 5, color = \"red\"),\n    type=\"scatter3d\",\n    name = \"Y\")\np2\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-e499df8ffbd3dc8ec9dc\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-e499df8ffbd3dc8ec9dc\">{\"x\":{\"visdat\":{\"1375e3a121d4c\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"1375e3a121d4c\",\"attrs\":{\"1375e3a121d4c\":{\"x\":{},\"y\":{},\"z\":{},\"name\":\"origin\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter3d\",\"mode\":\"markers\",\"inherit\":true},\"1375e3a121d4c.1\":{\"x\":[0,1],\"y\":[0,0],\"z\":[0,0],\"name\":\"obs1\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"grey\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.2\":{\"x\":[0,0],\"y\":[0,1],\"z\":[0,0],\"name\":\"obs2\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"grey\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.3\":{\"x\":[0,0],\"y\":[0,0],\"z\":[0,1],\"name\":\"obs3\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"grey\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.4\":{\"x\":[0,1],\"y\":[0,1],\"z\":[0,1],\"name\":\"X1\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"black\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.5\":{\"x\":[0,1],\"y\":[0,2],\"z\":[0,3],\"name\":\"X2\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"black\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.6\":{\"x\":[0,1],\"y\":[0,2],\"z\":[0,2],\"name\":\"Y\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"red\"},\"type\":\"scatter3d\",\"inherit\":true}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"scene\":{\"aspectmode\":\"cube\",\"xaxis\":{\"range\":[-4,4],\"title\":\"X1\"},\"yaxis\":{\"range\":[-4,4],\"title\":\"X2\"},\"zaxis\":{\"range\":[-4,4],\"title\":\"X3\"}},\"hovermode\":\"closest\",\"showlegend\":true},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"x\":[0],\"y\":[0],\"z\":[0],\"name\":\"origin\",\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"rgba(31,119,180,1)\",\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,0],\"z\":[0,0],\"name\":\"obs1\",\"mode\":\"lines\",\"line\":{\"color\":\"grey\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(255,127,14,1)\",\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[0,0],\"y\":[0,1],\"z\":[0,0],\"name\":\"obs2\",\"mode\":\"lines\",\"line\":{\"color\":\"grey\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(44,160,44,1)\",\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[0,0],\"y\":[0,0],\"z\":[0,1],\"name\":\"obs3\",\"mode\":\"lines\",\"line\":{\"color\":\"grey\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(214,39,40,1)\",\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,1],\"z\":[0,1],\"name\":\"X1\",\"mode\":\"lines\",\"line\":{\"color\":\"black\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(148,103,189,1)\",\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,2],\"z\":[0,3],\"name\":\"X2\",\"mode\":\"lines\",\"line\":{\"color\":\"black\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(140,86,75,1)\",\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,2],\"z\":[0,2],\"name\":\"Y\",\"mode\":\"lines\",\"line\":{\"color\":\"red\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(227,119,194,1)\",\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n3. Projection of Y onto column space\n\nActual values of fitted values $\\mathbf{\\hat{Y}}$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata$yhat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 1.166667 1.666667 2.166667\n```\n\n\n:::\n:::\n\n\n\\[\n\\mathbf{Y}=\\left[\\begin{array}{c}\n1.1666667 \\\\\n1.6666667 \\\\\n2.1666667\n\\end{array}\\right]\n\\]\n\n\n::: {.cell}\n\n```{.r .cell-code}\np2 <- p2 |>\n  add_trace(\n    x = c(0,Yhat[1]),\n    y = c(0,Yhat[2]),\n    z = c(0,Yhat[3]),\n    mode = \"lines\",\n    line = list(width = 5, color = \"orange\"),\n    type=\"scatter3d\",\n    name=\"Yhat\") |>\n    add_trace(\n    x = c(Y[1],Yhat[1]),\n    y = c(Y[2],Yhat[2]),\n    z = c(Y[3],Yhat[3]),\n    mode = \"lines\",\n    line = list(width = 5, color = \"red\", dash=\"dash\"),\n    type=\"scatter3d\",\n    name=\"Y -> Yhat\"\n    )\np2\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-51061db0ea07695d23ab\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-51061db0ea07695d23ab\">{\"x\":{\"visdat\":{\"1375e3a121d4c\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"1375e3a121d4c\",\"attrs\":{\"1375e3a121d4c\":{\"x\":{},\"y\":{},\"z\":{},\"name\":\"origin\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter3d\",\"mode\":\"markers\",\"inherit\":true},\"1375e3a121d4c.1\":{\"x\":[0,1],\"y\":[0,0],\"z\":[0,0],\"name\":\"obs1\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"grey\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.2\":{\"x\":[0,0],\"y\":[0,1],\"z\":[0,0],\"name\":\"obs2\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"grey\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.3\":{\"x\":[0,0],\"y\":[0,0],\"z\":[0,1],\"name\":\"obs3\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"grey\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.4\":{\"x\":[0,1],\"y\":[0,1],\"z\":[0,1],\"name\":\"X1\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"black\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.5\":{\"x\":[0,1],\"y\":[0,2],\"z\":[0,3],\"name\":\"X2\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"black\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.6\":{\"x\":[0,1],\"y\":[0,2],\"z\":[0,2],\"name\":\"Y\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"red\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.7\":{\"x\":[0,1.1666666666666674],\"y\":[0,1.6666666666666674],\"z\":[0,2.1666666666666674],\"name\":\"Yhat\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"orange\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.8\":{\"x\":[1,1.1666666666666674],\"y\":[2,1.6666666666666674],\"z\":[2,2.1666666666666674],\"name\":\"Y -> Yhat\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"red\",\"dash\":\"dash\"},\"type\":\"scatter3d\",\"inherit\":true}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"scene\":{\"aspectmode\":\"cube\",\"xaxis\":{\"range\":[-4,4],\"title\":\"X1\"},\"yaxis\":{\"range\":[-4,4],\"title\":\"X2\"},\"zaxis\":{\"range\":[-4,4],\"title\":\"X3\"}},\"hovermode\":\"closest\",\"showlegend\":true},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"x\":[0],\"y\":[0],\"z\":[0],\"name\":\"origin\",\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"rgba(31,119,180,1)\",\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,0],\"z\":[0,0],\"name\":\"obs1\",\"mode\":\"lines\",\"line\":{\"color\":\"grey\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(255,127,14,1)\",\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[0,0],\"y\":[0,1],\"z\":[0,0],\"name\":\"obs2\",\"mode\":\"lines\",\"line\":{\"color\":\"grey\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(44,160,44,1)\",\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[0,0],\"y\":[0,0],\"z\":[0,1],\"name\":\"obs3\",\"mode\":\"lines\",\"line\":{\"color\":\"grey\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(214,39,40,1)\",\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,1],\"z\":[0,1],\"name\":\"X1\",\"mode\":\"lines\",\"line\":{\"color\":\"black\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(148,103,189,1)\",\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,2],\"z\":[0,3],\"name\":\"X2\",\"mode\":\"lines\",\"line\":{\"color\":\"black\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(140,86,75,1)\",\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,2],\"z\":[0,2],\"name\":\"Y\",\"mode\":\"lines\",\"line\":{\"color\":\"red\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(227,119,194,1)\",\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[0,1.1666666666666674],\"y\":[0,1.6666666666666674],\"z\":[0,2.1666666666666674],\"name\":\"Yhat\",\"mode\":\"lines\",\"line\":{\"color\":\"orange\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(127,127,127,1)\",\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[1,1.1666666666666674],\"y\":[2,1.6666666666666674],\"z\":[2,2.1666666666666674],\"name\":\"Y -> Yhat\",\"mode\":\"lines\",\"line\":{\"color\":\"red\",\"width\":5,\"dash\":\"dash\"},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(188,189,34,1)\",\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n$\\mathbf{Y}$ is projected in the column space of $\\mathbf{X}$! spanned by the columns.\n\n#### How does this projection works?\n\n$$\n\\begin{array}{lcl}\n\\hat{\\mathbf{Y}} &=& \\mathbf{X} (\\mathbf{X}^T\\mathbf{X})^{-1}\\mathbf{X}^T\\mathbf{Y}\\\\\n&=& \\mathbf{X}(\\mathbf{X}^T\\mathbf{X})^{-1/2}(\\mathbf{X}^T\\mathbf{X})^{-1/2}\\mathbf{X}^T\\mathbf{Y}\\\\\n&=& \\mathbf{U}\\mathbf{U}^T\\mathbf{Y}\n\\end{array}\n$$\n\n\n- $\\mathbf{U}$ is a new orthonormal basis in $\\mathbb{R}^2$, a subspace of $\\mathbb{R}^3$\n\n- The space spanned by U and X is the column space of X, e.g. it contains all possible linear combinations of X.\n$\\mathbf{U}^t\\mathbf{Y}$ is the projection of Y on this new orthonormal basis\n\n\n::: {.cell}\n\n```{.r .cell-code}\neigenXtX <- eigen(XtX)\nXtXinvSqrt <- eigenXtX$vectors %*%diag(1/eigenXtX$values^.5)%*%t(eigenXtX$vectors)\nU <- X %*% XtXinvSqrt\n```\n:::\n\n\n\n- $\\mathbf{U}$ orthonormal basis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nU\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>         [,1]        [,2]\n#> 1  0.9116067 -0.04802616\n#> 2  0.3881706  0.42738380\n#> 3 -0.1352655  0.90279376\n```\n\n\n:::\n\n```{.r .cell-code}\nt(U)%*%U\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>              [,1]         [,2]\n#> [1,] 1.000000e+00 2.915205e-16\n#> [2,] 2.915205e-16 1.000000e+00\n```\n\n\n:::\n:::\n\n\n- $\\mathbf{UU}^T$ equals projection matrix\n\n\n::: {.cell}\n\n```{.r .cell-code}\nU%*%t(U)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>            1         2          3\n#> 1  0.8333333 0.3333333 -0.1666667\n#> 2  0.3333333 0.3333333  0.3333333\n#> 3 -0.1666667 0.3333333  0.8333333\n```\n\n\n:::\n\n```{.r .cell-code}\nH\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>            1         2          3\n#> 1  0.8333333 0.3333333 -0.1666667\n#> 2  0.3333333 0.3333333  0.3333333\n#> 3 -0.1666667 0.3333333  0.8333333\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np3 <- p1 |>\n  add_trace(\n    x = c(0,U[1,1]),\n    y = c(0,U[2,1]),\n    z = c(0,U[3,1]),\n    mode = \"lines\",\n    line = list(width = 5, color = \"blue\"),\n    type=\"scatter3d\",\n    name = \"U1\") |>\n  add_trace(\n    x = c(0,U[1,2]),\n    y = c(0,U[2,2]),\n    z = c(0,U[3,2]),\n    mode = \"lines\",\n    line = list(width = 5, color = \"blue\"),\n    type=\"scatter3d\",\n    name = \"U2\")\n\np3\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-9923059b4028d5b69efc\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-9923059b4028d5b69efc\">{\"x\":{\"visdat\":{\"1375e3a121d4c\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"1375e3a121d4c\",\"attrs\":{\"1375e3a121d4c\":{\"x\":{},\"y\":{},\"z\":{},\"name\":\"origin\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter3d\",\"mode\":\"markers\",\"inherit\":true},\"1375e3a121d4c.1\":{\"x\":[0,1],\"y\":[0,0],\"z\":[0,0],\"name\":\"obs1\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"grey\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.2\":{\"x\":[0,0],\"y\":[0,1],\"z\":[0,0],\"name\":\"obs2\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"grey\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.3\":{\"x\":[0,0],\"y\":[0,0],\"z\":[0,1],\"name\":\"obs3\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"grey\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.4\":{\"x\":[0,1],\"y\":[0,1],\"z\":[0,1],\"name\":\"X1\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"black\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.5\":{\"x\":[0,1],\"y\":[0,2],\"z\":[0,3],\"name\":\"X2\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"black\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.6\":{\"x\":[0,0.91160672519099273],\"y\":[0,0.38817060670267134],\"z\":[0,-0.13526551178565005],\"name\":\"U1\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"blue\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.7\":{\"x\":[0,-0.048026158704263522],\"y\":[0,0.42738380107979446],\"z\":[0,0.90279376086385243],\"name\":\"U2\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"blue\"},\"type\":\"scatter3d\",\"inherit\":true}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"scene\":{\"aspectmode\":\"cube\",\"xaxis\":{\"range\":[-4,4],\"title\":\"X1\"},\"yaxis\":{\"range\":[-4,4],\"title\":\"X2\"},\"zaxis\":{\"range\":[-4,4],\"title\":\"X3\"}},\"hovermode\":\"closest\",\"showlegend\":true},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"x\":[0],\"y\":[0],\"z\":[0],\"name\":\"origin\",\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"rgba(31,119,180,1)\",\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,0],\"z\":[0,0],\"name\":\"obs1\",\"mode\":\"lines\",\"line\":{\"color\":\"grey\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(255,127,14,1)\",\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[0,0],\"y\":[0,1],\"z\":[0,0],\"name\":\"obs2\",\"mode\":\"lines\",\"line\":{\"color\":\"grey\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(44,160,44,1)\",\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[0,0],\"y\":[0,0],\"z\":[0,1],\"name\":\"obs3\",\"mode\":\"lines\",\"line\":{\"color\":\"grey\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(214,39,40,1)\",\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,1],\"z\":[0,1],\"name\":\"X1\",\"mode\":\"lines\",\"line\":{\"color\":\"black\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(148,103,189,1)\",\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,2],\"z\":[0,3],\"name\":\"X2\",\"mode\":\"lines\",\"line\":{\"color\":\"black\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(140,86,75,1)\",\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[0,0.91160672519099273],\"y\":[0,0.38817060670267134],\"z\":[0,-0.13526551178565005],\"name\":\"U1\",\"mode\":\"lines\",\"line\":{\"color\":\"blue\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(227,119,194,1)\",\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[0,-0.048026158704263522],\"y\":[0,0.42738380107979446],\"z\":[0,0.90279376086385243],\"name\":\"U2\",\"mode\":\"lines\",\"line\":{\"color\":\"blue\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(127,127,127,1)\",\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n- $\\mathbf{U}^T\\mathbf{Y}$ is the projection of $\\mathbf{Y}$ in the space spanned by $\\mathbf{U}$.\n- Indeed $\\mathbf{U}_1^T\\mathbf{Y}$\n\n\n::: {.cell}\n\n```{.r .cell-code}\np4 <- p3 |>\n  add_trace(\n    x = c(0,Y[1]),\n    y = c(0,Y[2]),\n    z = c(0,Y[3]),\n    mode = \"lines\",\n    line = list(width = 5, color = \"red\"),\n    type=\"scatter3d\",\n    name = \"Y\") |>\n  add_trace(\n    x = c(0,U[1,1]*(U[,1]%*%Y)),\n    y = c(0,U[2,1]*(U[,1]%*%Y)),\n    z = c(0,U[3,1]*(U[,1]%*%Y)),\n    mode = \"lines\",\n    line = list(width = 5, color = \"red\",dash=\"dash\"),\n    type=\"scatter3d\",\n    name=\"Y -> U1\") |> add_trace(\n    x = c(Y[1],U[1,1]*(U[,1]%*%Y)),\n    y = c(Y[2],U[2,1]*(U[,1]%*%Y)),\n    z = c(Y[3],U[3,1]*(U[,1]%*%Y)),\n    mode = \"lines\",\n    line = list(width = 5, color = \"red\", dash=\"dash\"),\n    type=\"scatter3d\",\n    name=\"Y -> U1\")\np4\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-6b5b8c817f86a93ab9ac\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-6b5b8c817f86a93ab9ac\">{\"x\":{\"visdat\":{\"1375e3a121d4c\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"1375e3a121d4c\",\"attrs\":{\"1375e3a121d4c\":{\"x\":{},\"y\":{},\"z\":{},\"name\":\"origin\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter3d\",\"mode\":\"markers\",\"inherit\":true},\"1375e3a121d4c.1\":{\"x\":[0,1],\"y\":[0,0],\"z\":[0,0],\"name\":\"obs1\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"grey\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.2\":{\"x\":[0,0],\"y\":[0,1],\"z\":[0,0],\"name\":\"obs2\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"grey\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.3\":{\"x\":[0,0],\"y\":[0,0],\"z\":[0,1],\"name\":\"obs3\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"grey\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.4\":{\"x\":[0,1],\"y\":[0,1],\"z\":[0,1],\"name\":\"X1\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"black\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.5\":{\"x\":[0,1],\"y\":[0,2],\"z\":[0,3],\"name\":\"X2\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"black\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.6\":{\"x\":[0,0.91160672519099273],\"y\":[0,0.38817060670267134],\"z\":[0,-0.13526551178565005],\"name\":\"U1\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"blue\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.7\":{\"x\":[0,-0.048026158704263522],\"y\":[0,0.42738380107979446],\"z\":[0,0.90279376086385243],\"name\":\"U2\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"blue\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.8\":{\"x\":[0,1],\"y\":[0,2],\"z\":[0,2],\"name\":\"Y\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"red\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.9\":{\"x\":[0,1.292126792136292],\"y\":[0,0.55019958385589673],\"z\":[0,-0.19172762442449864],\"name\":\"Y -> U1\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"red\",\"dash\":\"dash\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.10\":{\"x\":[1,1.292126792136292],\"y\":[2,0.55019958385589673],\"z\":[2,-0.19172762442449864],\"name\":\"Y -> U1\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"red\",\"dash\":\"dash\"},\"type\":\"scatter3d\",\"inherit\":true}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"scene\":{\"aspectmode\":\"cube\",\"xaxis\":{\"range\":[-4,4],\"title\":\"X1\"},\"yaxis\":{\"range\":[-4,4],\"title\":\"X2\"},\"zaxis\":{\"range\":[-4,4],\"title\":\"X3\"}},\"hovermode\":\"closest\",\"showlegend\":true},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"x\":[0],\"y\":[0],\"z\":[0],\"name\":\"origin\",\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"rgba(31,119,180,1)\",\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,0],\"z\":[0,0],\"name\":\"obs1\",\"mode\":\"lines\",\"line\":{\"color\":\"grey\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(255,127,14,1)\",\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[0,0],\"y\":[0,1],\"z\":[0,0],\"name\":\"obs2\",\"mode\":\"lines\",\"line\":{\"color\":\"grey\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(44,160,44,1)\",\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[0,0],\"y\":[0,0],\"z\":[0,1],\"name\":\"obs3\",\"mode\":\"lines\",\"line\":{\"color\":\"grey\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(214,39,40,1)\",\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,1],\"z\":[0,1],\"name\":\"X1\",\"mode\":\"lines\",\"line\":{\"color\":\"black\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(148,103,189,1)\",\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,2],\"z\":[0,3],\"name\":\"X2\",\"mode\":\"lines\",\"line\":{\"color\":\"black\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(140,86,75,1)\",\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[0,0.91160672519099273],\"y\":[0,0.38817060670267134],\"z\":[0,-0.13526551178565005],\"name\":\"U1\",\"mode\":\"lines\",\"line\":{\"color\":\"blue\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(227,119,194,1)\",\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[0,-0.048026158704263522],\"y\":[0,0.42738380107979446],\"z\":[0,0.90279376086385243],\"name\":\"U2\",\"mode\":\"lines\",\"line\":{\"color\":\"blue\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(127,127,127,1)\",\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,2],\"z\":[0,2],\"name\":\"Y\",\"mode\":\"lines\",\"line\":{\"color\":\"red\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(188,189,34,1)\",\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[0,1.292126792136292],\"y\":[0,0.55019958385589673],\"z\":[0,-0.19172762442449864],\"name\":\"Y -> U1\",\"mode\":\"lines\",\"line\":{\"color\":\"red\",\"width\":5,\"dash\":\"dash\"},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(23,190,207,1)\",\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[1,1.292126792136292],\"y\":[2,0.55019958385589673],\"z\":[2,-0.19172762442449864],\"name\":\"Y -> U1\",\"mode\":\"lines\",\"line\":{\"color\":\"red\",\"width\":5,\"dash\":\"dash\"},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(31,119,180,1)\",\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n- and $\\mathbf{U}_2^T\\mathbf{Y}$\n\n::: {.cell}\n\n```{.r .cell-code}\np5 <- p4 |>\n  add_trace(\n    x = c(0,U[1,2]*(U[,2]%*%Y)),\n    y = c(0,U[2,2]*(U[,2]%*%Y)),\n    z = c(0,U[3,2]*(U[,2]%*%Y)),\n    mode = \"lines\",\n    line = list(width = 5, color = \"red\",dash=\"dash\"),\n    type=\"scatter3d\",\n    name=\"Y -> U2\") |> add_trace(\n    x = c(Y[1],U[1,2]*(U[,2]%*%Y)),\n    y = c(Y[2],U[2,2]*(U[,2]%*%Y)),\n    z = c(Y[3],U[3,2]*(U[,2]%*%Y)),\n    mode = \"lines\",\n    line = list(width = 5, color = \"red\", dash=\"dash\"),\n    type=\"scatter3d\",\n    name=\"Y -> U2\")\np5\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-d9e5160c7b54e1d67e7e\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-d9e5160c7b54e1d67e7e\">{\"x\":{\"visdat\":{\"1375e3a121d4c\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"1375e3a121d4c\",\"attrs\":{\"1375e3a121d4c\":{\"x\":{},\"y\":{},\"z\":{},\"name\":\"origin\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter3d\",\"mode\":\"markers\",\"inherit\":true},\"1375e3a121d4c.1\":{\"x\":[0,1],\"y\":[0,0],\"z\":[0,0],\"name\":\"obs1\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"grey\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.2\":{\"x\":[0,0],\"y\":[0,1],\"z\":[0,0],\"name\":\"obs2\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"grey\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.3\":{\"x\":[0,0],\"y\":[0,0],\"z\":[0,1],\"name\":\"obs3\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"grey\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.4\":{\"x\":[0,1],\"y\":[0,1],\"z\":[0,1],\"name\":\"X1\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"black\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.5\":{\"x\":[0,1],\"y\":[0,2],\"z\":[0,3],\"name\":\"X2\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"black\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.6\":{\"x\":[0,0.91160672519099273],\"y\":[0,0.38817060670267134],\"z\":[0,-0.13526551178565005],\"name\":\"U1\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"blue\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.7\":{\"x\":[0,-0.048026158704263522],\"y\":[0,0.42738380107979446],\"z\":[0,0.90279376086385243],\"name\":\"U2\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"blue\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.8\":{\"x\":[0,1],\"y\":[0,2],\"z\":[0,2],\"name\":\"Y\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"red\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.9\":{\"x\":[0,1.292126792136292],\"y\":[0,0.55019958385589673],\"z\":[0,-0.19172762442449864],\"name\":\"Y -> U1\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"red\",\"dash\":\"dash\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.10\":{\"x\":[1,1.292126792136292],\"y\":[2,0.55019958385589673],\"z\":[2,-0.19172762442449864],\"name\":\"Y -> U1\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"red\",\"dash\":\"dash\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.11\":{\"x\":[0,-0.12546012546962471],\"y\":[0,1.1164670828107695],\"z\":[0,2.3583942910911637],\"name\":\"Y -> U2\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"red\",\"dash\":\"dash\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.12\":{\"x\":[1,-0.12546012546962471],\"y\":[2,1.1164670828107695],\"z\":[2,2.3583942910911637],\"name\":\"Y -> U2\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"red\",\"dash\":\"dash\"},\"type\":\"scatter3d\",\"inherit\":true}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"scene\":{\"aspectmode\":\"cube\",\"xaxis\":{\"range\":[-4,4],\"title\":\"X1\"},\"yaxis\":{\"range\":[-4,4],\"title\":\"X2\"},\"zaxis\":{\"range\":[-4,4],\"title\":\"X3\"}},\"hovermode\":\"closest\",\"showlegend\":true},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"x\":[0],\"y\":[0],\"z\":[0],\"name\":\"origin\",\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"rgba(31,119,180,1)\",\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,0],\"z\":[0,0],\"name\":\"obs1\",\"mode\":\"lines\",\"line\":{\"color\":\"grey\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(255,127,14,1)\",\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[0,0],\"y\":[0,1],\"z\":[0,0],\"name\":\"obs2\",\"mode\":\"lines\",\"line\":{\"color\":\"grey\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(44,160,44,1)\",\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[0,0],\"y\":[0,0],\"z\":[0,1],\"name\":\"obs3\",\"mode\":\"lines\",\"line\":{\"color\":\"grey\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(214,39,40,1)\",\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,1],\"z\":[0,1],\"name\":\"X1\",\"mode\":\"lines\",\"line\":{\"color\":\"black\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(148,103,189,1)\",\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,2],\"z\":[0,3],\"name\":\"X2\",\"mode\":\"lines\",\"line\":{\"color\":\"black\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(140,86,75,1)\",\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[0,0.91160672519099273],\"y\":[0,0.38817060670267134],\"z\":[0,-0.13526551178565005],\"name\":\"U1\",\"mode\":\"lines\",\"line\":{\"color\":\"blue\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(227,119,194,1)\",\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[0,-0.048026158704263522],\"y\":[0,0.42738380107979446],\"z\":[0,0.90279376086385243],\"name\":\"U2\",\"mode\":\"lines\",\"line\":{\"color\":\"blue\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(127,127,127,1)\",\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,2],\"z\":[0,2],\"name\":\"Y\",\"mode\":\"lines\",\"line\":{\"color\":\"red\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(188,189,34,1)\",\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[0,1.292126792136292],\"y\":[0,0.55019958385589673],\"z\":[0,-0.19172762442449864],\"name\":\"Y -> U1\",\"mode\":\"lines\",\"line\":{\"color\":\"red\",\"width\":5,\"dash\":\"dash\"},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(23,190,207,1)\",\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[1,1.292126792136292],\"y\":[2,0.55019958385589673],\"z\":[2,-0.19172762442449864],\"name\":\"Y -> U1\",\"mode\":\"lines\",\"line\":{\"color\":\"red\",\"width\":5,\"dash\":\"dash\"},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(31,119,180,1)\",\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[0,-0.12546012546962471],\"y\":[0,1.1164670828107695],\"z\":[0,2.3583942910911637],\"name\":\"Y -> U2\",\"mode\":\"lines\",\"line\":{\"color\":\"red\",\"width\":5,\"dash\":\"dash\"},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(255,127,14,1)\",\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[1,-0.12546012546962471],\"y\":[2,1.1164670828107695],\"z\":[2,2.3583942910911637],\"name\":\"Y -> U2\",\"mode\":\"lines\",\"line\":{\"color\":\"red\",\"width\":5,\"dash\":\"dash\"},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(44,160,44,1)\",\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n- Yhat is the resulting vector that lies in the plane spanned by $\\mathbf{U}_1$ and $\\mathbf{U}_2$ and thus also in the column space of $\\mathbf{X}$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np6 <- p5 |>\n  add_trace(\n    x = c(0,Yhat[1]),\n    y = c(0,Yhat[2]),\n    z = c(0,Yhat[3]),\n    mode = \"lines\",\n    line = list(width = 5, color = \"orange\"),\n    type=\"scatter3d\",\n    name = \"Yhat\") |>\n  add_trace(\n    x = c(Y[1],Yhat[1]),\n    y = c(Y[2],Yhat[2]),\n    z = c(Y[3],Yhat[3]),\n    mode = \"lines\",\n    line = list(width = 5, color = \"maroon2\"),\n    type=\"scatter3d\",\n    name = \"e\") |>\n  add_trace(\n    x = c(U[1,1]*(U[,1]%*%Y),Yhat[1]),\n    y = c(U[2,1]*(U[,1]%*%Y),Yhat[2]),\n    z = c(U[3,1]*(U[,1]%*%Y),Yhat[3]),\n    mode = \"lines\",\n    line = list(width = 5, color = \"orange\", dash=\"dash\"),\n    type=\"scatter3d\",\n    name = \"Y -> U\")  |>\n  add_trace(\n    x = c(U[1,2]*(U[,2]%*%Y),Yhat[1]),\n    y = c(U[2,2]*(U[,2]%*%Y),Yhat[2]),\n    z = c(U[3,2]*(U[,2]%*%Y),Yhat[3]),\n    mode = \"lines\",\n    line = list(width = 5, color = \"orange\", dash=\"dash\"),\n    type=\"scatter3d\",\n    name = \"Y -> U\")\np6\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-a272b32e44c6baafdd81\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-a272b32e44c6baafdd81\">{\"x\":{\"visdat\":{\"1375e3a121d4c\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"1375e3a121d4c\",\"attrs\":{\"1375e3a121d4c\":{\"x\":{},\"y\":{},\"z\":{},\"name\":\"origin\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter3d\",\"mode\":\"markers\",\"inherit\":true},\"1375e3a121d4c.1\":{\"x\":[0,1],\"y\":[0,0],\"z\":[0,0],\"name\":\"obs1\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"grey\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.2\":{\"x\":[0,0],\"y\":[0,1],\"z\":[0,0],\"name\":\"obs2\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"grey\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.3\":{\"x\":[0,0],\"y\":[0,0],\"z\":[0,1],\"name\":\"obs3\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"grey\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.4\":{\"x\":[0,1],\"y\":[0,1],\"z\":[0,1],\"name\":\"X1\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"black\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.5\":{\"x\":[0,1],\"y\":[0,2],\"z\":[0,3],\"name\":\"X2\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"black\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.6\":{\"x\":[0,0.91160672519099273],\"y\":[0,0.38817060670267134],\"z\":[0,-0.13526551178565005],\"name\":\"U1\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"blue\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.7\":{\"x\":[0,-0.048026158704263522],\"y\":[0,0.42738380107979446],\"z\":[0,0.90279376086385243],\"name\":\"U2\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"blue\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.8\":{\"x\":[0,1],\"y\":[0,2],\"z\":[0,2],\"name\":\"Y\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"red\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.9\":{\"x\":[0,1.292126792136292],\"y\":[0,0.55019958385589673],\"z\":[0,-0.19172762442449864],\"name\":\"Y -> U1\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"red\",\"dash\":\"dash\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.10\":{\"x\":[1,1.292126792136292],\"y\":[2,0.55019958385589673],\"z\":[2,-0.19172762442449864],\"name\":\"Y -> U1\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"red\",\"dash\":\"dash\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.11\":{\"x\":[0,-0.12546012546962471],\"y\":[0,1.1164670828107695],\"z\":[0,2.3583942910911637],\"name\":\"Y -> U2\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"red\",\"dash\":\"dash\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.12\":{\"x\":[1,-0.12546012546962471],\"y\":[2,1.1164670828107695],\"z\":[2,2.3583942910911637],\"name\":\"Y -> U2\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"red\",\"dash\":\"dash\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.13\":{\"x\":[0,1.1666666666666674],\"y\":[0,1.6666666666666674],\"z\":[0,2.1666666666666674],\"name\":\"Yhat\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"orange\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.14\":{\"x\":[1,1.1666666666666674],\"y\":[2,1.6666666666666674],\"z\":[2,2.1666666666666674],\"name\":\"e\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"maroon2\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.15\":{\"x\":[1.292126792136292,1.1666666666666674],\"y\":[0.55019958385589673,1.6666666666666674],\"z\":[-0.19172762442449864,2.1666666666666674],\"name\":\"Y -> U\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"orange\",\"dash\":\"dash\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.16\":{\"x\":[-0.12546012546962471,1.1666666666666674],\"y\":[1.1164670828107695,1.6666666666666674],\"z\":[2.3583942910911637,2.1666666666666674],\"name\":\"Y -> U\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"orange\",\"dash\":\"dash\"},\"type\":\"scatter3d\",\"inherit\":true}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"scene\":{\"aspectmode\":\"cube\",\"xaxis\":{\"range\":[-4,4],\"title\":\"X1\"},\"yaxis\":{\"range\":[-4,4],\"title\":\"X2\"},\"zaxis\":{\"range\":[-4,4],\"title\":\"X3\"}},\"hovermode\":\"closest\",\"showlegend\":true},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"x\":[0],\"y\":[0],\"z\":[0],\"name\":\"origin\",\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"rgba(31,119,180,1)\",\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,0],\"z\":[0,0],\"name\":\"obs1\",\"mode\":\"lines\",\"line\":{\"color\":\"grey\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(255,127,14,1)\",\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[0,0],\"y\":[0,1],\"z\":[0,0],\"name\":\"obs2\",\"mode\":\"lines\",\"line\":{\"color\":\"grey\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(44,160,44,1)\",\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[0,0],\"y\":[0,0],\"z\":[0,1],\"name\":\"obs3\",\"mode\":\"lines\",\"line\":{\"color\":\"grey\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(214,39,40,1)\",\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,1],\"z\":[0,1],\"name\":\"X1\",\"mode\":\"lines\",\"line\":{\"color\":\"black\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(148,103,189,1)\",\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,2],\"z\":[0,3],\"name\":\"X2\",\"mode\":\"lines\",\"line\":{\"color\":\"black\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(140,86,75,1)\",\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[0,0.91160672519099273],\"y\":[0,0.38817060670267134],\"z\":[0,-0.13526551178565005],\"name\":\"U1\",\"mode\":\"lines\",\"line\":{\"color\":\"blue\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(227,119,194,1)\",\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[0,-0.048026158704263522],\"y\":[0,0.42738380107979446],\"z\":[0,0.90279376086385243],\"name\":\"U2\",\"mode\":\"lines\",\"line\":{\"color\":\"blue\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(127,127,127,1)\",\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,2],\"z\":[0,2],\"name\":\"Y\",\"mode\":\"lines\",\"line\":{\"color\":\"red\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(188,189,34,1)\",\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[0,1.292126792136292],\"y\":[0,0.55019958385589673],\"z\":[0,-0.19172762442449864],\"name\":\"Y -> U1\",\"mode\":\"lines\",\"line\":{\"color\":\"red\",\"width\":5,\"dash\":\"dash\"},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(23,190,207,1)\",\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null},{\"x\":[1,1.292126792136292],\"y\":[2,0.55019958385589673],\"z\":[2,-0.19172762442449864],\"name\":\"Y -> U1\",\"mode\":\"lines\",\"line\":{\"color\":\"red\",\"width\":5,\"dash\":\"dash\"},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(31,119,180,1)\",\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[0,-0.12546012546962471],\"y\":[0,1.1164670828107695],\"z\":[0,2.3583942910911637],\"name\":\"Y -> U2\",\"mode\":\"lines\",\"line\":{\"color\":\"red\",\"width\":5,\"dash\":\"dash\"},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(255,127,14,1)\",\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[1,-0.12546012546962471],\"y\":[2,1.1164670828107695],\"z\":[2,2.3583942910911637],\"name\":\"Y -> U2\",\"mode\":\"lines\",\"line\":{\"color\":\"red\",\"width\":5,\"dash\":\"dash\"},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(44,160,44,1)\",\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[0,1.1666666666666674],\"y\":[0,1.6666666666666674],\"z\":[0,2.1666666666666674],\"name\":\"Yhat\",\"mode\":\"lines\",\"line\":{\"color\":\"orange\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(214,39,40,1)\",\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[1,1.1666666666666674],\"y\":[2,1.6666666666666674],\"z\":[2,2.1666666666666674],\"name\":\"e\",\"mode\":\"lines\",\"line\":{\"color\":\"maroon2\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(148,103,189,1)\",\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[1.292126792136292,1.1666666666666674],\"y\":[0.55019958385589673,1.6666666666666674],\"z\":[-0.19172762442449864,2.1666666666666674],\"name\":\"Y -> U\",\"mode\":\"lines\",\"line\":{\"color\":\"orange\",\"width\":5,\"dash\":\"dash\"},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(140,86,75,1)\",\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[-0.12546012546962471,1.1666666666666674],\"y\":[1.1164670828107695,1.6666666666666674],\"z\":[2.3583942910911637,2.1666666666666674],\"name\":\"Y -> U\",\"mode\":\"lines\",\"line\":{\"color\":\"orange\",\"width\":5,\"dash\":\"dash\"},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(227,119,194,1)\",\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n### Error\n\nNote, that it is also clear from the equation in the derivation of the least squares solution that the residual is orthogonal on the column space:\n\n\\[\n -2 \\mathbf{X}^T(\\mathbf{Y}-\\mathbf{X}\\boldsymbol{\\beta}) = 0\n\\]\n\n\n### Curse of dimensionality?\n\n- Imagine what happens when p approaches n $p=n$ or becomes much larger than p >> n!!!\n\n- Suppose that we add a predictor $\\mathbf{X}_2 = [2,0,1]^T$?\n\n$$\n\\mathbf{Y}=\\left[\n\\begin{array}{c}\n1\\\\\n2\\\\\n2\\\\\n\\end{array}\\right],\n\\quad\n\\mathbf{X}= \\left[\n\\begin{array}{ccc}\n1&1&2\\\\\n1&2&0\\\\\n1&3&1\\\\\n\\end{array}\n\\right],\n\\quad \\boldsymbol{\\beta} = \\left[\n\\begin{array}{c}\n\\beta_0\\\\\n\\beta_1\\\\\n\\beta_2\n\\end{array}\n\\right]\n\\quad\n\\text{and}\n\\quad\n\\boldsymbol{\\epsilon}=\n\\left[\n\\begin{array}{c}\n\\epsilon_1\\\\\n\\epsilon_2\\\\\n\\epsilon_3\n\\end{array}\n\\right]\n$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata$x2 <- c(2,0,1)\nfit <- lm(y~x+x2,data)\n# predict values on regular xy grid\nx1pred <- seq(-1, 4, length.out = 10)\nx2pred <- seq(-1, 4, length.out = 10)\nxy <- expand.grid(x = x1pred,\nx2 = x2pred)\nypred <- matrix (nrow = 30, ncol = 30,\ndata = predict(fit, newdata = data.frame(xy)))\n\nlibrary(plot3D)\n\n\n# fitted points for droplines to surface\nth=20\nph=5\nscatter3D(data$x,\n  data$x2,\n  Y,\n  pch = 16,\n  col=\"darkblue\",\n  cex = 1,\n  theta = th,\n  ticktype = \"detailed\",\n  xlab = \"x1\",\n  ylab = \"x2\",\n  zlab = \"y\",\n  colvar=FALSE,\n  bty = \"g\",\n  xlim=c(-1,3),\n  ylim=c(-1,3),\n  zlim=c(-2,4))\n```\n\n::: {.cell-output-display}\n![](intro_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n\n```{.r .cell-code}\nz.pred3D <- outer(\n  x1pred,\n  x2pred,\n  function(x1,x2)\n  {\n    fit$coef[1] + fit$coef[2]*x1+fit$coef[2]*x2\n  })\n\nx.pred3D <- outer(\n  x1pred,\n  x2pred,\n  function(x,y) x)\n\ny.pred3D <- outer(\n  x1pred,\n  x2pred,\n  function(x,y) y)\n\nscatter3D(data$x,\n  data$x2,\n  data$y,\n  pch = 16,\n  col=\"darkblue\",\n  cex = 1,\n  theta = th,\n  ticktype = \"detailed\",\n  xlab = \"x1\",\n  ylab = \"x2\",\n  zlab = \"y\",\n  colvar=FALSE,\n  bty = \"g\",\n  xlim=c(-1,4),\n  ylim=c(-1,4),\n  zlim=c(-2,4))\n\nsurf3D(\n  x.pred3D,\n  y.pred3D,\n  z.pred3D,\n  col=\"blue\",\n  facets=NA,\n  add=TRUE)\n```\n\n::: {.cell-output-display}\n![](intro_files/figure-html/unnamed-chunk-27-2.png){width=672}\n:::\n:::\n\n\nNote, that the linear regression is now a plane.\n\nHowever, we obtain a perfect fit and all the data points are falling in the plane! 😱\n\nThis is obvious if we look at the column space of X!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nX <- cbind(X,c(2,0,1))\nXtX <- t(X)%*%X\neigenXtX <- eigen(XtX)\nXtXinvSqrt <- eigenXtX$vectors %*%diag(1/eigenXtX$values^.5)%*%t(eigenXtX$vectors)\nU <- X %*% XtXinvSqrt\n\np7 <- p1 |>\n  add_trace(\n    x = c(0,2),\n    y = c(0,0),\n    z = c(0,1),\n    mode = \"lines\",\n    line = list(width = 5, color = \"darkgreen\"),\n    type=\"scatter3d\",\n    name = \"X3\")\np7\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-fb34258af186769b7a4e\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-fb34258af186769b7a4e\">{\"x\":{\"visdat\":{\"1375e3a121d4c\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"1375e3a121d4c\",\"attrs\":{\"1375e3a121d4c\":{\"x\":{},\"y\":{},\"z\":{},\"name\":\"origin\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter3d\",\"mode\":\"markers\",\"inherit\":true},\"1375e3a121d4c.1\":{\"x\":[0,1],\"y\":[0,0],\"z\":[0,0],\"name\":\"obs1\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"grey\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.2\":{\"x\":[0,0],\"y\":[0,1],\"z\":[0,0],\"name\":\"obs2\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"grey\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.3\":{\"x\":[0,0],\"y\":[0,0],\"z\":[0,1],\"name\":\"obs3\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"grey\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.4\":{\"x\":[0,1],\"y\":[0,1],\"z\":[0,1],\"name\":\"X1\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"black\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.5\":{\"x\":[0,1],\"y\":[0,2],\"z\":[0,3],\"name\":\"X2\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"black\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.6\":{\"x\":[0,2],\"y\":[0,0],\"z\":[0,1],\"name\":\"X3\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"darkgreen\"},\"type\":\"scatter3d\",\"inherit\":true}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"scene\":{\"aspectmode\":\"cube\",\"xaxis\":{\"range\":[-4,4],\"title\":\"X1\"},\"yaxis\":{\"range\":[-4,4],\"title\":\"X2\"},\"zaxis\":{\"range\":[-4,4],\"title\":\"X3\"}},\"hovermode\":\"closest\",\"showlegend\":true},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"x\":[0],\"y\":[0],\"z\":[0],\"name\":\"origin\",\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"rgba(31,119,180,1)\",\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,0],\"z\":[0,0],\"name\":\"obs1\",\"mode\":\"lines\",\"line\":{\"color\":\"grey\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(255,127,14,1)\",\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[0,0],\"y\":[0,1],\"z\":[0,0],\"name\":\"obs2\",\"mode\":\"lines\",\"line\":{\"color\":\"grey\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(44,160,44,1)\",\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[0,0],\"y\":[0,0],\"z\":[0,1],\"name\":\"obs3\",\"mode\":\"lines\",\"line\":{\"color\":\"grey\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(214,39,40,1)\",\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,1],\"z\":[0,1],\"name\":\"X1\",\"mode\":\"lines\",\"line\":{\"color\":\"black\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(148,103,189,1)\",\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,2],\"z\":[0,3],\"name\":\"X2\",\"mode\":\"lines\",\"line\":{\"color\":\"black\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(140,86,75,1)\",\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[0,2],\"y\":[0,0],\"z\":[0,1],\"name\":\"X3\",\"mode\":\"lines\",\"line\":{\"color\":\"darkgreen\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(227,119,194,1)\",\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np8 <- p7 |>\n  add_trace(\n    x = c(0,U[1,1]),\n    y = c(0,U[2,1]),\n    z = c(0,U[3,1]),\n    mode = \"lines\",\n    line = list(width = 5, color = \"blue\"),\n    type=\"scatter3d\",\n    name = \"U1\") |>\n  add_trace(\n    x = c(0,U[1,2]),\n    y = c(0,U[2,2]),\n    z = c(0,U[3,2]),\n    mode = \"lines\",\n    line = list(width = 5, color = \"blue\"),\n    type=\"scatter3d\",\n    name = \"U2\") |>\n  add_trace(\n    x = c(0,U[1,3]),\n    y = c(0,U[2,3]),\n    z = c(0,U[3,3]),\n    mode = \"lines\",\n    line = list(width = 5, color = \"blue\"),\n    type=\"scatter3d\",\n    name = \"U3\")\n\np8\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-a8123a4c550e952a3025\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-a8123a4c550e952a3025\">{\"x\":{\"visdat\":{\"1375e3a121d4c\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"1375e3a121d4c\",\"attrs\":{\"1375e3a121d4c\":{\"x\":{},\"y\":{},\"z\":{},\"name\":\"origin\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter3d\",\"mode\":\"markers\",\"inherit\":true},\"1375e3a121d4c.1\":{\"x\":[0,1],\"y\":[0,0],\"z\":[0,0],\"name\":\"obs1\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"grey\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.2\":{\"x\":[0,0],\"y\":[0,1],\"z\":[0,0],\"name\":\"obs2\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"grey\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.3\":{\"x\":[0,0],\"y\":[0,0],\"z\":[0,1],\"name\":\"obs3\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"grey\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.4\":{\"x\":[0,1],\"y\":[0,1],\"z\":[0,1],\"name\":\"X1\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"black\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.5\":{\"x\":[0,1],\"y\":[0,2],\"z\":[0,3],\"name\":\"X2\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"black\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.6\":{\"x\":[0,2],\"y\":[0,0],\"z\":[0,1],\"name\":\"X3\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"darkgreen\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.7\":{\"x\":[0,0.49408047978220171],\"y\":[0,0.81609419390248528],\"z\":[0,-0.29979117094545366],\"name\":\"U1\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"blue\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.8\":{\"x\":[0,-0.077673605149894021],\"y\":[0,0.38487400381411052],\"z\":[0,0.91969495608658969],\"name\":\"U2\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"blue\"},\"type\":\"scatter3d\",\"inherit\":true},\"1375e3a121d4c.9\":{\"x\":[0,0.86593954209356305],\"y\":[0,-0.43111746411709106],\"z\":[0,0.25354771064247333],\"name\":\"U3\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"mode\":\"lines\",\"line\":{\"width\":5,\"color\":\"blue\"},\"type\":\"scatter3d\",\"inherit\":true}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"scene\":{\"aspectmode\":\"cube\",\"xaxis\":{\"range\":[-4,4],\"title\":\"X1\"},\"yaxis\":{\"range\":[-4,4],\"title\":\"X2\"},\"zaxis\":{\"range\":[-4,4],\"title\":\"X3\"}},\"hovermode\":\"closest\",\"showlegend\":true},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"x\":[0],\"y\":[0],\"z\":[0],\"name\":\"origin\",\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"rgba(31,119,180,1)\",\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,0],\"z\":[0,0],\"name\":\"obs1\",\"mode\":\"lines\",\"line\":{\"color\":\"grey\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(255,127,14,1)\",\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"frame\":null},{\"x\":[0,0],\"y\":[0,1],\"z\":[0,0],\"name\":\"obs2\",\"mode\":\"lines\",\"line\":{\"color\":\"grey\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(44,160,44,1)\",\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"frame\":null},{\"x\":[0,0],\"y\":[0,0],\"z\":[0,1],\"name\":\"obs3\",\"mode\":\"lines\",\"line\":{\"color\":\"grey\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(214,39,40,1)\",\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,1],\"z\":[0,1],\"name\":\"X1\",\"mode\":\"lines\",\"line\":{\"color\":\"black\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(148,103,189,1)\",\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"frame\":null},{\"x\":[0,1],\"y\":[0,2],\"z\":[0,3],\"name\":\"X2\",\"mode\":\"lines\",\"line\":{\"color\":\"black\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(140,86,75,1)\",\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"frame\":null},{\"x\":[0,2],\"y\":[0,0],\"z\":[0,1],\"name\":\"X3\",\"mode\":\"lines\",\"line\":{\"color\":\"darkgreen\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(227,119,194,1)\",\"line\":{\"color\":\"rgba(227,119,194,1)\"}},\"error_y\":{\"color\":\"rgba(227,119,194,1)\"},\"error_x\":{\"color\":\"rgba(227,119,194,1)\"},\"frame\":null},{\"x\":[0,0.49408047978220171],\"y\":[0,0.81609419390248528],\"z\":[0,-0.29979117094545366],\"name\":\"U1\",\"mode\":\"lines\",\"line\":{\"color\":\"blue\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(127,127,127,1)\",\"line\":{\"color\":\"rgba(127,127,127,1)\"}},\"error_y\":{\"color\":\"rgba(127,127,127,1)\"},\"error_x\":{\"color\":\"rgba(127,127,127,1)\"},\"frame\":null},{\"x\":[0,-0.077673605149894021],\"y\":[0,0.38487400381411052],\"z\":[0,0.91969495608658969],\"name\":\"U2\",\"mode\":\"lines\",\"line\":{\"color\":\"blue\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(188,189,34,1)\",\"line\":{\"color\":\"rgba(188,189,34,1)\"}},\"error_y\":{\"color\":\"rgba(188,189,34,1)\"},\"error_x\":{\"color\":\"rgba(188,189,34,1)\"},\"frame\":null},{\"x\":[0,0.86593954209356305],\"y\":[0,-0.43111746411709106],\"z\":[0,0.25354771064247333],\"name\":\"U3\",\"mode\":\"lines\",\"line\":{\"color\":\"blue\",\"width\":5},\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(23,190,207,1)\",\"line\":{\"color\":\"rgba(23,190,207,1)\"}},\"error_y\":{\"color\":\"rgba(23,190,207,1)\"},\"error_x\":{\"color\":\"rgba(23,190,207,1)\"},\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n- The column space now spans the entire  $\\mathbb{R}^3$!\n\n- With the intercept and the two predictors we can thus fit every dataset that only has 3 observations for the predictors and the response.\n\n- So the model can no longer be used to generalise the patterns seen in the data towards the population (new observations).\n\n- Problem of overfitting!!!\n\n- If $p >> n$ then the problem gets even worse! Then there is even no longer a unique solution to the least squares problem...\n\n- Indeed, then we have more vectors/dimensions/columns in X  than datapoints!\n\n\n## Variance Estimator?\n\\[\n\\begin{array}{ccl}\n\\hat{\\boldsymbol{\\Sigma}}_{\\hat{\\boldsymbol{\\beta}}}\n&=&\\text{var}\\left[(\\mathbf{X}^T\\mathbf{X})^{-1}\\mathbf{X}^T\\mathbf{Y}\\right]\\\\\\\\\n&=&(\\mathbf{X}^T\\mathbf{X})^{-1}\\mathbf{X}^T\\text{var}\\left[\\mathbf{Y}\\right]\\mathbf{X}(\\mathbf{X}^T\\mathbf{X})^{-1} \\text{(*)}\\\\\\\\\n&=&(\\mathbf{X}^T\\mathbf{X})^{-1}\\mathbf{X}^T(\\mathbf{I}\\sigma^2)\\mathbf{X}(\\mathbf{X}^T\\mathbf{X})^{-1}\n\\\\\\\\\n&=&(\\mathbf{X}^T\\mathbf{X})^{-1}\\mathbf{X}^T\\mathbf{I}\\quad\\mathbf{X}(\\mathbf{X}^T\\mathbf{X})^{-1}\\sigma^2\\\\\\\\\n%\\hat{\\boldmath{\\Sigma}}_{\\hat{\\boldsymbol{\\beta}}}&=&(\\mathbf{X}^T\\mathbf{X})^{-1}\\mathbf{X}^T \\text{var}\\left[\\mathbf{Y}\\right](\\mathbf{X}^T\\mathbf{X})^{-1}\\mathbf{X}\\\\\n&=&(\\mathbf{X}^T\\mathbf{X})^{-1}\\mathbf{X}^T\\mathbf{X}(\\mathbf{X}^T\\mathbf{X})^{-1}\\sigma^2\\\\\\\\\n&=&(\\mathbf{X}^T\\mathbf{X})^{-1}\\sigma^2\n\\end{array}\n\\]\n\n(*) Under assumption that all observations $\\mathbf{Y}$ are independent and identically distributed.\n\nThe fact that $\\hat{\\boldsymbol{\\beta}}$ is unbiased and has a variance of $(\\mathbf{X}^T\\mathbf{X})^{-1}\\sigma^2$ will be important when assessing association!\n\n---\n\n## Prediction error\n\nLeast squares estimators are unbiased and consistent, but these properties are not very important for prediction models.\n\nA prediction model is considered good if it can predict well outcomes.\n\nThe **prediction error** for a prediction at predictor $\\mathbf{x}$ is given by\n\n$$\n   \\hat{Y}(\\mathbf{x}) - Y^*,\n$$\n\nwhere\n\n-  $\\hat{Y}(\\mathbf{x})=\\mathbf{x}^T\\hat{\\boldsymbol{\\beta}}$ is the prediction at $\\mathbf{x}$\n\n-  $Y^*$ is an outcome at predictor $\\mathbf{x}$\n\n Since prediction is typically used to predict an outcome before it is observed, the outcome $Y^*$ is not observed yet. Hence, the prediction error cannot be computed.\n\n ---\n\n The problem of unobservable prediction errors is partly solved by the **expected conditional test error** (sometimes referred to as the mean squared error, MSE)\n\\[\n  \\text{Err}(\\mathbf{x})=E[(\\hat{Y}(\\mathbf{x}) - Y^*)^2].\n\\]\n\nWith (suppressing the dependence on $\\mathbf{x}$)\n\\[\n  \\mu = E[\\hat{Y}] \\text{ and } \\mu^*=E[Y^*]\n\\]\nthe error can be expressed as\n\\begin{eqnarray*}\n  \\text{Err}\n    &=&E\\left\\{\\left[(\\hat{Y} -\\mu)-(Y^*-\\mu^*)-(\\mu^*-\\mu)\\right]^2\\right\\} \\\\\n    &=& E[(\\hat{Y} -\\mu)^2]+E[(Y^*-\\mu^*)^2]+E[(\\mu^*-\\mu)^2] \\\\\n    &=& \\text{var}[\\hat{Y}] +\\text{var}[Y^*] +\\text{bias}^2\n\\end{eqnarray*}\n\n The term $\\text{var}[Y^*]$ (irreducible error) does not depend on the model and may therefore be ignored when $\\text{Err}$ is used for comparing prediction models.\n\n ---\n\n\nIn this introductory chapter we only aim to give a rough discussion on prediction errors. Later definitions will be refined and the notation will be more accurate. Also a more detailed discussion on the bias-variance trade-off will follow. For the moment it is sufficient to vaguely know that:\n\n- the expected conditional test error is introduced to circumvent the problem that the prediction error cannot be observed. In later chapters we will look at estimators of the expected error.\n\n- the expected conditional test error  is in some literature also known as the *mean squared error* (MSE), but we do not adopt this terminology because MSE is also commonly used to refer to SSE divided by the residual degrees of freedom in a linear regression model.\n\n- The identity $\\text{Err}=\\text{var}[\\hat{Y}] +\\text{var}[Y] +\\text{bias}^2$ is known as the bias-variance trade-off. It shows that a good prediction model (i.e. a model resulting in a small Err), can be obtained by a model that shows a small bias as long as this bias is compensated with a large reduction of the variance or the predictions. A more detailed discussion will follow in later chapters.\n\n- For prediction models with a large number of predictors we will therefore introduce penalized regression. This will induce some bias in the estimation, but will allow us to reduce the variance considerably.\n\n\n# Session info {-}\n\n<details><summary>Session info</summary>\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] \"2026-09-16 09:40:24 CEST\"\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> ─ Session info ───────────────────────────────────────────────────────────────\n#>  setting  value\n#>  version  R version 4.6.1 (2026-06-24)\n#>  os       macOS Tahoe 26.1\n#>  system   aarch64, darwin23\n#>  ui       X11\n#>  language (EN)\n#>  collate  nl_BE.UTF-8\n#>  ctype    nl_BE.UTF-8\n#>  tz       Europe/Brussels\n#>  date     2026-09-16\n#>  pandoc   3.10.2 @ /opt/homebrew/bin/ (via rmarkdown)\n#>  quarto   1.9.37 @ /usr/local/bin/quarto\n#> \n#> ─ Packages ───────────────────────────────────────────────────────────────────\n#>  package              * version    date (UTC) lib source\n#>  abind                  1.4-8      2024-09-12 [1] CRAN (R 4.6.0)\n#>  AnnotationDbi          1.74.0     2026-04-28 [1] Bioconductor 3.23 (R 4.6.0)\n#>  AnnotationHub        * 4.2.1      2026-06-15 [1] https://bioc-release.r-universe.dev (R 4.6.0)\n#>  assertthat             0.2.1      2019-03-21 [1] CRAN (R 4.6.0)\n#>  beachmat               2.28.0     2026-04-28 [1] Bioconductor 3.23 (R 4.6.0)\n#>  beeswarm               0.4.0      2021-06-01 [1] CRAN (R 4.6.0)\n#>  Biobase              * 2.72.0     2026-04-28 [1] Bioconductor 3.23 (R 4.6.0)\n#>  BiocFileCache        * 3.2.0      2026-04-28 [1] Bioconductor 3.23 (R 4.6.0)\n#>  BiocGenerics         * 0.58.1     2026-05-14 [1] https://bioc-release.r-universe.dev (R 4.6.0)\n#>  BiocManager            1.30.27    2025-11-14 [1] CRAN (R 4.6.0)\n#>  BiocNeighbors          2.6.0      2026-04-28 [1] Bioconductor 3.23 (R 4.6.0)\n#>  BiocParallel           1.46.0     2026-04-28 [1] Bioconductor 3.23 (R 4.6.0)\n#>  BiocSingular           1.28.0     2026-04-28 [1] Bioconductor 3.23 (R 4.6.0)\n#>  BiocVersion            3.23.1     2025-10-30 [1] https://bioc.r-universe.dev (R 4.6.0)\n#>  Biostrings             2.80.1     2026-05-22 [1] https://bioc-release.r-universe.dev (R 4.6.0)\n#>  bit                    4.6.0      2025-03-06 [1] CRAN (R 4.6.0)\n#>  bit64                  4.8.2      2026-05-19 [1] CRAN (R 4.6.0)\n#>  blob                   1.3.0      2026-01-14 [1] CRAN (R 4.6.0)\n#>  cachem                 1.1.0      2024-05-16 [1] CRAN (R 4.6.0)\n#>  cli                    3.6.6      2026-04-09 [1] CRAN (R 4.6.0)\n#>  codetools              0.2-20     2024-03-31 [1] CRAN (R 4.6.1)\n#>  cowplot                1.2.0      2025-07-07 [1] CRAN (R 4.6.0)\n#>  crayon                 1.5.3      2024-06-20 [1] CRAN (R 4.6.0)\n#>  crosstalk              1.2.2      2025-08-26 [1] CRAN (R 4.6.0)\n#>  curl                   7.1.0      2026-04-22 [1] CRAN (R 4.6.0)\n#>  data.table             1.18.4     2026-05-06 [1] CRAN (R 4.6.0)\n#>  DBI                    1.3.0      2026-02-25 [1] CRAN (R 4.6.0)\n#>  dbplyr               * 2.6.0      2026-06-17 [1] CRAN (R 4.6.0)\n#>  DelayedArray           0.38.2     2026-05-26 [1] https://bioc-release.r-universe.dev (R 4.6.0)\n#>  digest                 0.6.39     2025-11-19 [1] CRAN (R 4.6.0)\n#>  dplyr                * 1.2.1      2026-04-03 [1] CRAN (R 4.6.0)\n#>  emo                    0.0.0.9000 2026-09-15 [1] Github (hadley/emo@3f03b11)\n#>  evaluate               1.0.5      2025-08-27 [1] CRAN (R 4.6.0)\n#>  ExperimentHub        * 3.2.0      2026-04-28 [1] Bioconductor 3.23 (R 4.6.0)\n#>  farver                 2.1.2      2024-05-13 [1] CRAN (R 4.6.0)\n#>  fastmap                1.2.0      2024-05-15 [1] CRAN (R 4.6.0)\n#>  filelock               1.0.3      2023-12-11 [1] CRAN (R 4.6.0)\n#>  forcats              * 1.0.1      2025-09-25 [1] CRAN (R 4.6.0)\n#>  generics             * 0.1.4      2025-05-09 [1] CRAN (R 4.6.0)\n#>  GenomicRanges        * 1.64.0     2026-04-28 [1] Bioconductor 3.23 (R 4.6.0)\n#>  ggbeeswarm             0.7.3      2025-11-29 [1] CRAN (R 4.6.0)\n#>  ggplot2              * 4.0.3      2026-04-22 [1] CRAN (R 4.6.0)\n#>  ggrepel                0.9.8      2026-03-17 [1] CRAN (R 4.6.0)\n#>  glue                   1.8.1      2026-04-17 [1] CRAN (R 4.6.0)\n#>  gridExtra              2.3.1      2026-06-25 [1] CRAN (R 4.6.1)\n#>  gtable                 0.3.6      2024-10-25 [1] CRAN (R 4.6.0)\n#>  hms                    1.1.4      2025-10-17 [1] CRAN (R 4.6.0)\n#>  htmltools              0.5.9      2025-12-04 [1] CRAN (R 4.6.0)\n#>  htmlwidgets            1.6.4      2023-12-06 [1] CRAN (R 4.6.0)\n#>  httr                   1.4.8      2026-02-13 [1] CRAN (R 4.6.0)\n#>  httr2                  1.2.3      2026-06-23 [1] CRAN (R 4.6.1)\n#>  IRanges              * 2.46.0     2026-04-28 [1] Bioconductor 3.23 (R 4.6.0)\n#>  irlba                  2.3.7      2026-01-30 [1] CRAN (R 4.6.0)\n#>  jsonlite               2.0.0      2025-03-27 [1] CRAN (R 4.6.0)\n#>  KEGGREST               1.52.0     2026-04-28 [1] Bioconductor 3.23 (R 4.6.0)\n#>  knitr                  1.51       2025-12-20 [1] CRAN (R 4.6.0)\n#>  labeling               0.4.3      2023-08-29 [1] CRAN (R 4.6.0)\n#>  lattice                0.22-9     2026-02-09 [1] CRAN (R 4.6.1)\n#>  lazyeval               0.2.3      2026-04-04 [1] CRAN (R 4.6.0)\n#>  lifecycle              1.0.5      2026-01-08 [1] CRAN (R 4.6.0)\n#>  lubridate            * 1.9.5      2026-02-04 [1] CRAN (R 4.6.0)\n#>  magrittr               2.0.5      2026-04-04 [1] CRAN (R 4.6.0)\n#>  Matrix                 1.7-5      2026-03-21 [1] CRAN (R 4.6.1)\n#>  MatrixGenerics       * 1.24.0     2026-04-28 [1] Bioconductor 3.23 (R 4.6.0)\n#>  matrixStats          * 1.5.0      2025-01-07 [1] CRAN (R 4.6.0)\n#>  memoise                2.0.1      2021-11-26 [1] CRAN (R 4.6.0)\n#>  mgcv                   1.9-4      2025-11-07 [1] CRAN (R 4.6.1)\n#>  misc3d                 0.9-2      2026-01-28 [1] CRAN (R 4.6.0)\n#>  nlme                   3.1-169    2026-03-27 [1] CRAN (R 4.6.1)\n#>  otel                   0.2.0      2025-08-29 [1] CRAN (R 4.6.0)\n#>  pillar                 1.11.1     2025-09-17 [1] CRAN (R 4.6.0)\n#>  pkgconfig              2.0.3      2019-09-22 [1] CRAN (R 4.6.0)\n#>  plot3D               * 1.4.2      2025-07-25 [1] CRAN (R 4.6.0)\n#>  plotly               * 4.12.0     2026-01-24 [1] CRAN (R 4.6.0)\n#>  png                    0.1-9      2026-03-15 [1] CRAN (R 4.6.0)\n#>  purrr                * 1.2.2      2026-04-10 [1] CRAN (R 4.6.0)\n#>  R6                     2.6.1      2025-02-15 [1] CRAN (R 4.6.0)\n#>  rappdirs               0.3.4      2026-01-17 [1] CRAN (R 4.6.0)\n#>  RColorBrewer           1.1-3      2022-04-03 [1] CRAN (R 4.6.0)\n#>  Rcpp                   1.1.1-1.1  2026-04-24 [1] CRAN (R 4.6.0)\n#>  readr                * 2.2.0      2026-02-19 [1] CRAN (R 4.6.0)\n#>  rlang                  1.2.0      2026-04-06 [1] CRAN (R 4.6.0)\n#>  rmarkdown              2.31       2026-03-26 [1] CRAN (R 4.6.0)\n#>  RSQLite                3.53.2     2026-06-17 [1] CRAN (R 4.6.0)\n#>  rsvd                   1.0.5      2021-04-16 [1] CRAN (R 4.6.0)\n#>  S4Arrays               1.12.0     2026-04-28 [1] Bioconductor 3.23 (R 4.6.0)\n#>  S4Vectors            * 0.50.1     2026-05-03 [1] https://bioc-release.r-universe.dev (R 4.6.0)\n#>  S7                     0.2.2      2026-04-22 [1] CRAN (R 4.6.0)\n#>  ScaledMatrix           1.20.0     2026-04-28 [1] Bioconductor 3.23 (R 4.6.0)\n#>  scales                 1.4.0      2025-04-24 [1] CRAN (R 4.6.0)\n#>  scater               * 1.40.1     2026-05-20 [1] https://bioc-release.r-universe.dev (R 4.6.0)\n#>  scuttle              * 1.22.0     2026-04-28 [1] Bioconductor 3.23 (R 4.6.0)\n#>  Seqinfo              * 1.2.0      2026-04-28 [1] Bioconductor 3.23 (R 4.6.0)\n#>  sessioninfo            1.2.4      2026-06-04 [1] CRAN (R 4.6.0)\n#>  SingleCellExperiment * 1.34.0     2026-04-28 [1] Bioconductor 3.23 (R 4.6.0)\n#>  SparseArray            1.12.2     2026-05-01 [1] Bioconductor 3.23 (R 4.6.0)\n#>  stringi                1.8.7      2025-03-27 [1] CRAN (R 4.6.0)\n#>  stringr              * 1.6.0      2025-11-04 [1] CRAN (R 4.6.0)\n#>  SummarizedExperiment * 1.42.0     2026-04-28 [1] Bioconductor 3.23 (R 4.6.0)\n#>  tibble               * 3.3.1      2026-01-11 [1] CRAN (R 4.6.0)\n#>  tidyr                * 1.3.2      2025-12-19 [1] CRAN (R 4.6.0)\n#>  tidyselect             1.2.1      2024-03-11 [1] CRAN (R 4.6.0)\n#>  tidyverse            * 2.0.0      2023-02-22 [1] CRAN (R 4.6.0)\n#>  timechange             0.4.0      2026-01-29 [1] CRAN (R 4.6.0)\n#>  tzdb                   0.5.0      2025-03-15 [1] CRAN (R 4.6.0)\n#>  vctrs                  0.7.3      2026-04-11 [1] CRAN (R 4.6.0)\n#>  vipor                  0.4.7      2023-12-18 [1] CRAN (R 4.6.0)\n#>  viridis                0.6.5      2024-01-29 [1] CRAN (R 4.6.0)\n#>  viridisLite            0.4.3      2026-02-04 [1] CRAN (R 4.6.0)\n#>  withr                  3.0.3      2026-06-19 [1] CRAN (R 4.6.0)\n#>  xfun                   0.59       2026-06-19 [1] CRAN (R 4.6.0)\n#>  XVector                0.52.0     2026-04-28 [1] Bioconductor 3.23 (R 4.6.0)\n#>  yaml                   2.3.12     2025-12-10 [1] CRAN (R 4.6.0)\n#> \n#>  [1] /Library/Frameworks/R.framework/Versions/4.6/Resources/library\n#>  * ── Packages attached to the search path.\n#> \n#> ──────────────────────────────────────────────────────────────────────────────\n```\n\n\n:::\n:::\n\n\n</details>\n",
    "supporting": [
      "intro_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"site_libs/plotly-binding-4.12.0/plotly.js\"></script>\n<script src=\"site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n<link href=\"site_libs/plotly-htmlwidgets-css-2.25.2/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/plotly-main-2.25.2/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}