{
  "hash": "740539a3c36a7c8571890cf850fa1a3e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 2: Principal Component Analysis\"\nsubtitle: \"High Dimensional Data Analysis practicals\"\nauthor: \"Adapted by Milan Malfait\"\ndate: \"10 Feb 2022 <br/> (Last updated: 2022-02-10)\"\nformat:\n  html: default\n---\n\n\n\n### [Change log](https://github.com/statOmics/HDDA/commits/master/Lab2-PCA.Rmd) {-}\n\n***\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n## Install necessary packages with:\n# install.packages(\"tidyverse\")\n# install.packages(\"ggrepel\")\n# if (!requireNamespace(\"remotes\", quietly = TRUE)) {\n#     install.packages(\"remotes\")\n# }\n# remotes::install_github(\"statOmics/HDDAData\")\n# remotes::install_github(\"vqv/ggbiplot\")\n\nlibrary(tidyverse)\ntheme_set(theme_light())\n\nlibrary(ggbiplot)\nlibrary(ggrepel)\nlibrary(HDDAData)\n```\n:::\n\n\n# Introduction\n\nThe first part of this lab demonstrates the influence of standardizing the data (i.e. working on the\ncorrelation matrix vs. working on the covariance matrix). Pay attention to what the output looks\nlike and how it links to the biplot.)\n\n# PCA demonstration\n\n## Data prep\n\nWe will load the `trees` dataset (from base `R`, see `?trees` for more info) that contains the\nheight of a tree (in *feet*), the girth (or diameter in *inches*) and the volume (in *cubic feet*)\nof the tree. For the purpose of this exercise, we will convert the continuous *volume* variable to a\ncategorical variable (a `factor` in R lingo). A tree will be considered large if its volume is\nbigger than 25 cubic feet, and small otherwise.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Load data\ndata(trees)\n\n# Convert volume to factor\ntrees$vol_fac <- as.factor(ifelse(trees$Volume > 25, \"large\", \"small\"))\n\n# Preview data\nhead(trees)\n#>   Girth Height Volume vol_fac\n#> 1   8.3     70   10.3   small\n#> 2   8.6     65   10.3   small\n#> 3   8.8     63   10.2   small\n#> 4  10.5     72   16.4   small\n#> 5  10.7     81   18.8   small\n#> 6  10.8     83   19.7   small\nsummary(trees)\n#>      Girth           Height       Volume       vol_fac  \n#>  Min.   : 8.30   Min.   :63   Min.   :10.20   large:14  \n#>  1st Qu.:11.05   1st Qu.:72   1st Qu.:19.40   small:17  \n#>  Median :12.90   Median :76   Median :24.20             \n#>  Mean   :13.25   Mean   :76   Mean   :30.17             \n#>  3rd Qu.:15.25   3rd Qu.:80   3rd Qu.:37.30             \n#>  Max.   :20.60   Max.   :87   Max.   :77.00\n```\n:::\n\n\nNow suppose that the height was actually measured in **miles** instead of feet.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n## Create new column in trees with height in miles\ntrees$height_miles <- trees$Height / 5280\n\n# Create matrix using height_miles and Girth variables\ntree_mx <- cbind(\"height_miles\" = trees$height_miles, \"girth\" = trees$Girth)\nhead(tree_mx)\n#>      height_miles girth\n#> [1,]   0.01325758   8.3\n#> [2,]   0.01231061   8.6\n#> [3,]   0.01193182   8.8\n#> [4,]   0.01363636  10.5\n#> [5,]   0.01534091  10.7\n#> [6,]   0.01571970  10.8\n```\n:::\n\n\nAlways good to visualize the data. Here we plot the height (in miles) vs. the girth for each tree\nand size the dots according to their volume. We also use a color aesthetic to distinguish \"large\"\nand \"small\" trees.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntrees_plot <- ggplot(trees) +\n  geom_point(aes(Girth, height_miles, size = Volume, col = vol_fac),\n             alpha = 0.6) +\n  labs(x = \"Girth (inches)\", y = \"Height (miles)\",\n       color = \"Volume class\")\n\ntrees_plot +\n  ggtitle(\"Visualizing the original trees data\")\n```\n\n::: {.cell-output-display}\n![](Lab2-PCA_files/figure-html/trees-plot-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nPay attention to the units on the axis and the (very) different orders of the units.\n\n> Q: looking at this plot, can you make a guess in which direction the largest variation lies, i.e.\n> in which direction the first principal component would lie?\n\nTo help with visualization of the PCs later on, we also make the plot using the **centered and\nscaled** data. The `scale` function can be used for this, so that all variables have mean 0 and unit\nvariance.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n## Center and scale data\ntrees_scaled <- scale(tree_mx, center = TRUE, scale = TRUE)\n\ntrees_scaled_plot <- trees_scaled |>\n  ## Convert to data.frame and re-add Volume columns for plotting\n  data.frame(Volume = trees$Volume, vol_fac = trees$vol_fac) |>\n  ggplot() +\n  geom_point(aes(girth, height_miles, size = Volume, col = vol_fac),\n             alpha = 0.6) +\n  labs(x = \"Girth (inches), standardized\", y = \"Height (miles), standardized\",\n       color = \"\")\n\ntrees_scaled_plot +\n  ggtitle(\"Visualizing the scaled trees data\") +\n  coord_equal(xlim = c(-2.3, 2.3), ylim = c(-2.3, 2.3))\n```\n\n::: {.cell-output-display}\n![](Lab2-PCA_files/figure-html/unnamed-chunk-3-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n## Run PCA\n\nWe run PCA on the *height (in miles)* and *girth* variables and inspect the results.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Run PCA with prcomp function, which uses SVD internally (see ?prcomp)\n# Note that prcomp centers the matrix internally by default but does not scale it\n# (center = TRUE, scale. = FALSE)\ntree_pca <- prcomp(tree_mx)\nsummary(tree_pca)\n#> Importance of components:\n#>                          PC1      PC2\n#> Standard deviation     3.138 0.001031\n#> Proportion of Variance 1.000 0.000000\n#> Cumulative Proportion  1.000 1.000000\n```\n:::\n\n\n**Note:** The first component explains almost 100% of the variability in the data.\n\nThe **loadings** of the PCA are stored in the `$rotation` slot of the `prcomp` result, while the\n`$sdev` slot contains the standard deviations of the principal components.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntree_pca$rotation\n#>                       PC1           PC2\n#> height_miles 0.0001996911 -0.9999999801\n#> girth        0.9999999801  0.0001996911\ntree_pca$sdev\n#> [1] 3.138138679 0.001031321\n```\n:::\n\n\nRemember that the Principal Components are **linear combinations** of the original variables. The\nloadings tell you what the contribution (or weight) of each variable is to the PC. Here we see that\nthe first PC is completely dominated by the girth variable, while the second component is basically\n(the negative) height variable. Since the PCs are ordered by the amount of variance they retain from\nthe original data, we would conclude that most of the variance in the data comes from the girth\nvariable.\n\n> Q: Is this in line with what you expected from the original plot? Why not? (Think about the units\n> we are using here!)\n\nThe result from `prcomp` also contains an `$x` slot, which contains the projected values of the\noriginal data matrix onto the principal components (also called the *PC scores*). This is what we\nwill use to construct the PCA plot.\n\n### Visualize Principal Components\n\nScale the PC loadings by their standard deviations (singular values) to project them back to the\noriginal data space. We also transpose the `rotation` matrix so that the variables are in columns\nand PCs in the rows, so that we can overlay them on the original trees plot.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n## Transpose the loadings so that the PCs are in the rows, for plotting\npc_loadings <- t(tree_pca$rotation) * tree_pca$sdev\n\n## Reuse plot from before and add PCs\ntrees_scaled_plot +\n  geom_segment(\n    data = data.frame(pc_loadings),\n    aes(x = 0, xend = girth, y = 0, yend = height_miles),\n    arrow = arrow(length=unit(0.1,\"cm\"))\n  ) +\n  geom_text(\n    data = data.frame(pc_loadings),\n    aes(x = girth, y = height_miles, label = rownames(pc_loadings)),\n    vjust = 1.5\n  ) +\n  ggtitle(\"Trees data overlayed with PCs\",\n          subtitle = \"Based on PCA on non-standardized data\")\n```\n\n::: {.cell-output-display}\n![](Lab2-PCA_files/figure-html/tree-plot-PC-loadings-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nFrom this plot we see that the PCs are not in the directions we expected. PC1 should point in the\ndirection of greatest variability.\n\n### Visualize PCA with biplot\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggbiplot(tree_pca, groups = trees$vol_fac, alpha = 0) +\n  ## Add points layer to color and size points\n  geom_point(aes(col = trees$vol_fac, size = trees$Volume), alpha = 0.6) +\n  labs(size = \"Volume\", col = \"\") +\n  theme(aspect.ratio = 0.6) +\n  ggtitle(\"Biplot for the PCA on non-standardized data\")\n```\n\n::: {.cell-output-display}\n![](Lab2-PCA_files/figure-html/tree-pca-biplot-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nWe see that trees high in volume tend to have a high tree girth, but the height does not give any\ninformation on tree volume. This is likely wrong, since we know that the height of a tree should\nhave at least some influence on its volume. The problem here is that because of the 2 very different\nunit measures (*miles* and *inches*), the influence of the girth is inflated just because the order\nof the scale is much larger.\n\nThis is also reflected in the variances of these variables:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nround(diag(cov(tree_mx)), 8)\n#> height_miles        girth \n#>   0.00000146   9.84791398\n```\n:::\n\n\nWe see that the variance of the *girth* variable is several orders of magnitude larger than that of\nthe height (again, because of the different units) and this is reflected in the PCA.\n\nWe could use the same units, or we could standardize the variables by dividing by their standard\ndeviations. Both will lead to a more balanced picture of the variability. Of course in this case one\ncan argue that the variables should have the same unit but not be standardized, which may be a valid\nargument, were it not that we are measuring two different things (the height and the diameter). So\neven if we used the same units, it is recommended to also standardize the variables.\n\nImagine if we would be measuring the mass ($kg$) of the tree and the girth ($m$) of the tree, the\nscale on which both should be measured is no longer clear, since neither kilograms can be converted\nto meters nor meters converted to kilograms. In this case we have a clear argument to work on the\nstandardized variables.\n\n## Redo PCA on standardized variables\n\nWe will leave the *height* on the *miles* scale, but now we will standardize the variables before\nperforming the PCA. I.e. in addition to *centering* the matrix (subtracting the column means), we\nalso divide it by its column standard deviations. Note that these operations can be done in one go\nwith the `prcomp` function by specifying `center = TRUE` and `scale. = TRUE` (note the `.`!).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n## Compute PCA on centered and scaled matrix\ntree_pca_scaled <- prcomp(tree_mx, center = TRUE, scale. = TRUE)\nsummary(tree_pca_scaled)\n#> Importance of components:\n#>                           PC1    PC2\n#> Standard deviation     1.2326 0.6933\n#> Proportion of Variance 0.7596 0.2404\n#> Cumulative Proportion  0.7596 1.0000\ntree_pca_scaled$rotation\n#>                    PC1        PC2\n#> height_miles 0.7071068 -0.7071068\n#> girth        0.7071068  0.7071068\ntree_pca_scaled$sdev\n#> [1] 1.2325908 0.6933397\n```\n:::\n\n\nWe will again plot the original data, but this time using the **scaled and centered** values, and\noverlay the plot with the PCs.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npc_scaled_loadings <- t(tree_pca_scaled$rotation) * tree_pca_scaled$sdev\n\n## Reuse plot from before and add PCs\ntrees_scaled_plot +\n  geom_segment(\n    data = data.frame(pc_scaled_loadings),\n    aes(x = 0, xend = girth, y = 0, yend = height_miles),\n    arrow = arrow(length=unit(0.2,\"cm\"))\n  ) +\n  geom_text(\n    data = data.frame(pc_scaled_loadings),\n    aes(x = girth, y = height_miles, label = rownames(pc_scaled_loadings)),\n    nudge_x = 0.1, nudge_y = 0.2\n  ) +\n  coord_equal(xlim = c(-2.3, 2.3), ylim = c(-2.1, 2.1)) +\n  ggtitle(\"Trees data overlayed with PCs\",\n          subtitle = \"Based on PCA on standardized data\")\n```\n\n::: {.cell-output-display}\n![](Lab2-PCA_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nThis is more in line with our expectations. PC1 point in the direction of greatest variability, with\nPC2 orthogonal and pointing in the direction of second greatest variability.\n\nAlso note from the lengths of the PC vectors that the contributions of height and girth are equal to\nboth PCs.\n\nThe biplot:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggbiplot(tree_pca_scaled, groups = trees$vol_fac, alpha = 0) +\n  ## Add points layer to color and size points\n  geom_point(aes(col = trees$vol_fac, size = trees$Volume), alpha = 0.6) +\n  labs(size = \"Volume\", col = \"\") +\n  theme(aspect.ratio = 0.5) +\n  ggtitle(\"Biplot for the PCA on standardized data\")\n```\n\n::: {.cell-output-display}\n![](Lab2-PCA_files/figure-html/tree-scaled-pca-biplot-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nWe now get a much more realistic result, where the *height* and *girth* variables have more equal\ncontributions to the PCs.\n\nPC1 can be interpreted as separating small and large volume trees. A potential explanation of PC2\nwould be the separation between trees that have a similar volume but differ in their height-to-girth\nratios, i.e. short wide trees and long thin trees.\n\nNote that we would get the exact same result (apart maybe from the signs) if we used *height* on the\noriginal *feet* scale. Since the conversion is just a multiplication by a constant, scaling the\ncolumn by its standard deviation will give the same result. (You can verify this for yourself by\nredoing the PCA using the original height column from `trees`, without converting it to miles.)\n\n# Exercises\n\n## Heavy metals near the Schelde\n\n### Data prep {.unnumbered}\n\nAt the department of analytical and physical chemistry, researchers wanted to investigate the\npollution of grasslands in the vicinity of the river Schelde. Concentrations of 8 heavy metals were\nmeasured on 19 different locations, each time at a depth of 5 cm and at a depth of 20 cm; the data\nset is called heavymetals. Vicinity to the river was 0 (far) or 1 (close).\n\nLoad in the data as follows:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndata(\"heavymetals\")\n\n## Recode the \"river\" variable\nheavymetals$river <- ifelse(heavymetals$river, \"close\", \"far\")\n\nheavymetals\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>    location       Cd5      Cd20      Cr5      Cr20       Cu5      Cu20      Fe5\n#> 1         1 11.985549 10.248267 222.6264 201.70411  53.07369  47.12797 21082.42\n#> 2         2 18.879780 21.305590 380.8352 472.99684  87.10535  98.22006 26086.57\n#> 3         3 18.596573 25.293862 367.9316 471.08007  85.19597  99.34696 26505.51\n#> 4         4 29.266197 28.375580 509.7210 536.50892  81.33271 107.37870 26227.87\n#> 5         5 27.338299 16.642950 459.4522 374.88307  80.17195  89.43576 26673.33\n#> 6         6 26.754830 16.872317 446.9164 284.42600  75.38131  90.20572 27968.35\n#> 7         7 11.548973  7.609503 230.0818 163.21621  65.51117  52.95518 23758.23\n#> 8         8 17.179219 21.849109 395.0488 489.85391  91.93017 107.53452 28797.24\n#> 9         9 39.296271 26.904142 975.0546 650.84050  99.04384 116.65499 35077.03\n#> 10       10 33.078424 15.413639 693.1379 340.65207 101.80054 103.67347 32274.35\n#> 11       11  6.025691  6.669548 130.4749 142.14971  31.31797  34.49430 17239.35\n#> 12       12 18.786014  8.640800 384.9590 200.85500  70.54322  51.86600 28172.60\n#> 13       13 11.140970  6.368913 235.0636 146.69533  51.67892  38.86111 23737.33\n#> 14       14  4.869685  3.532557 118.4342  92.62302  33.22111  25.55361 21606.80\n#> 15       15  5.575173 19.845155 124.4373 100.48102  32.20866  26.33616 19375.48\n#> 16       16  9.117976  6.556471 186.8250 141.16237  46.04302  38.48612 26650.03\n#> 17       17 16.317868 10.160500 309.2241 196.85500  66.06039  50.70850 27213.95\n#> 18       18  9.269442  5.417358 180.3484 116.94314  43.98123  31.59838 22358.66\n#> 19       19 23.604106 10.588875 426.6221 209.51487  79.50164  63.06590 30781.75\n#>        Fe20      Mn5     Mn20      Ni5     Ni20       Pb5      Pb20       Zn5\n#> 1  21115.64 560.6947 539.5100 26.56467 28.18578 125.56169 110.01663  669.7809\n#> 2  27674.42 585.1739 439.7220 30.23035 31.93281 228.32679 249.61578 1308.6743\n#> 3  28401.95 496.1380 492.5562 29.31519 32.59391 242.45428 271.70865 1338.8758\n#> 4  31017.35 507.9277 445.9943 29.81537 35.30271 220.86275 283.04297 1311.1743\n#> 5  25223.07 492.9521 375.1916 30.20944 30.45378 240.26792 256.05533 1356.3598\n#> 6  28081.93 646.2482 519.3165 32.63791 33.31600 216.51083 268.10021 1217.5930\n#> 7  24895.19 488.3403 537.3528 27.50150 28.15083 155.99441 131.08405  815.9884\n#> 8  30719.77 532.7157 501.3108 31.76529 34.90394 232.54632 283.72023 1329.7470\n#> 9  33646.19 683.7433 513.3080 37.15136 37.86172 255.22714 305.49330 1654.5990\n#> 10 27464.41 517.5853 482.9268 35.32560 32.34196 298.29949 308.11349 1901.8439\n#> 11 17701.78 570.2983 574.1755 19.54255 21.29522  74.04669  83.98861  345.4588\n#> 12 24931.33 750.8904 582.5500 29.43778 28.38950 194.00760 135.62000 1024.9100\n#> 13 23093.02 534.2837 520.5979 28.19243 27.44826 146.21498 106.96930  668.7661\n#> 14 25633.13 563.2516 699.2398 25.27164 27.79606  82.46223  65.77015  323.4784\n#> 15 19469.80 440.3721 464.0460 23.44553 23.39211  95.35361  78.96503  368.7073\n#> 16 25138.14 561.3135 621.4999 30.49157 28.06870 132.47829 108.52806  569.7508\n#> 17 25112.00 632.5467 623.7700 32.36776 29.77600 195.13049 145.42000  921.7745\n#> 18 21950.63 551.4425 556.1507 27.40042 25.61757 131.76600  88.06935  574.9027\n#> 19 25662.81 627.9179 546.5369 33.74514 29.87649 226.45271 173.39196 1190.1724\n#>         Zn20 river\n#> 1   566.8739 close\n#> 2  1500.2075 close\n#> 3  1579.7562 close\n#> 4  1696.8871 close\n#> 5  1399.9071 close\n#> 6  1247.8162 close\n#> 7   580.0426 close\n#> 8  1656.1937 close\n#> 9  1771.6964 close\n#> 10 1452.4971 close\n#> 11  386.6180   far\n#> 12  606.7100   far\n#> 13  434.7465   far\n#> 14  241.3849   far\n#> 15  281.4119   far\n#> 16  431.9553   far\n#> 17  639.3400   far\n#> 18  356.8335   far\n#> 19  738.3789 close\n```\n\n\n:::\n\n```{.r .cell-code}\ndim(heavymetals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 19 18\n```\n\n\n:::\n:::\n\n\nNote that there are 2 columns per heavy metal, one for the measurement at 5 cm depth and one at 20\ncm depth.\n\n### Tasks {.unnumbered}\n\n##### 1. Conduct a PCA using *standardized variables*. How many PCs would you retain? Motivate the answer/interpret. {.unnumbered}\n\nThink about which columns you need from the original data!\n\n<details>\n\n<summary> Solution </summary>\n\nFirst do the PCA, excluding the `location` and `river` columns.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n## Remove 'location' and 'river' columns when creating matrix\nheavymetals_mx <- dplyr::select(heavymetals, -location, -river) |>\n  as.matrix()\n\n## Run PCA on centered and scaled data\nheavymetals_pca <- prcomp(heavymetals_mx, center = TRUE, scale. = TRUE)\nsummary(heavymetals_pca)\n#> Importance of components:\n#>                           PC1    PC2     PC3     PC4     PC5    PC6     PC7\n#> Standard deviation     3.4784 1.4209 0.83048 0.71075 0.50170 0.4020 0.31765\n#> Proportion of Variance 0.7562 0.1262 0.04311 0.03157 0.01573 0.0101 0.00631\n#> Cumulative Proportion  0.7562 0.8824 0.92549 0.95706 0.97279 0.9829 0.98920\n#>                            PC8     PC9    PC10   PC11    PC12    PC13    PC14\n#> Standard deviation     0.26517 0.19480 0.18158 0.1324 0.08871 0.06573 0.04041\n#> Proportion of Variance 0.00439 0.00237 0.00206 0.0011 0.00049 0.00027 0.00010\n#> Cumulative Proportion  0.99359 0.99597 0.99803 0.9991 0.99961 0.99988 0.99999\n#>                           PC15     PC16\n#> Standard deviation     0.01510 0.003029\n#> Proportion of Variance 0.00001 0.000000\n#> Cumulative Proportion  1.00000 1.000000\n```\n:::\n\n\nTo choose the number of PCs to retain, we look at the proportion of variance that each PC explains.\nThis can be visualized using what is known as a *scree plot*.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n## Calculate total variance by summing the PC variances (sdev's squared)\ntot_var <- sum(heavymetals_pca$sdev^2)\n\n## Create data.frame of the proportion of variance explained by each PC\nheavymetals_prop_var <- data.frame(\n  PC = 1:ncol(heavymetals_pca$x),\n  var = heavymetals_pca$sdev^2\n) |>\n  ## Using `mutate` to calculate prop. var and cum. prop. var\n  mutate(\n    prop_var = var / tot_var,\n    cum_prop_var = cumsum(var / tot_var)\n  )\n\nhead(heavymetals_prop_var)\n#>   PC        var   prop_var cum_prop_var\n#> 1  1 12.0990592 0.75619120    0.7561912\n#> 2  2  2.0190598 0.12619123    0.8823824\n#> 3  3  0.6897008 0.04310630    0.9254887\n#> 4  4  0.5051614 0.03157259    0.9570613\n#> 5  5  0.2517061 0.01573163    0.9727930\n#> 6  6  0.1615962 0.01009976    0.9828927\n\n## Plot the proportion of variance explained by each PC\nggplot(heavymetals_prop_var, aes(PC, prop_var)) +\n  geom_point() +\n  geom_line() +\n  geom_vline(xintercept = 2.5, col = \"firebrick\") +\n  scale_x_continuous(breaks = 1:ncol(heavymetals_pca$x)) +\n  labs(y = \"Proportion of variance\") +\n  ggtitle(\"Proportion of variance explained by each PC\",\n          subtitle = \"Heavy metals data\")\n```\n\n::: {.cell-output-display}\n![](Lab2-PCA_files/figure-html/heavymetals-pca-screeplot-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n\n## Plot the cumulative proportion of variance explained by each PC\nggplot(heavymetals_prop_var, aes(PC, cum_prop_var)) +\n  geom_point() +\n  geom_line() +\n  geom_vline(xintercept = 2.5, col = \"firebrick\") +\n  scale_x_continuous(breaks = 1:ncol(heavymetals_pca$x)) +\n  labs(y = \"Proportion of variance\") +\n  ggtitle(\"Cumulative proportion of variance explained by each PC\",\n          subtitle = \"Heavy metals data\")\n```\n\n::: {.cell-output-display}\n![](Lab2-PCA_files/figure-html/heavymetals-pca-screeplot-2.png){fig-align='center' width=100%}\n:::\n:::\n\n\nWe decide to keep the first 2 PCs (indicated by the red vertical line), as this coincides with the\n\"elbow\" in the scree plot. This leaves us with 88% of the total variance from the original data,\nwhich is not bad at all given that we went from 16 to only 2 dimensions! Other common cutoffs are to\nkeep e.g. 90%, 95% or 99% of the original variance. Which would give us 3, 4 or 7 PCs respectively.\nHowever, for the purpose of this exercise, the first 2 will be enough.\n\n</details>\n\n##### 2. Make a biplot using the retained PCs and interpret. Is there a relationship between vicinity to the river and pollution with certain metals? {.unnumbered}\n\n**Hint**: Try to color or label the data points by their vicinity to the river (using the `river`\nvariable) to aid with interpretation.\n\n<details>\n\n<summary> Solution </summary>\n\nMaking the biplot for the first 2 PCs.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggbiplot(heavymetals_pca, groups = heavymetals$river) +\n  labs(color = \"Vicinity to river\") +\n  ggtitle(\"Biplot for the heavy metals PCA\")\n```\n\n::: {.cell-output-display}\n![](Lab2-PCA_files/figure-html/heavymetals-pca-biplot-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nThe distinction that is immediately clear is that the levels of Manganese (Mn) seem to be higher in\nthe areas far from the river (at both depths), compared to all other metals.\n\nWe can also see this from the loadings, where Mn20 is the only measurement that is negatively\ncorrelated with PC1, while Mn5 is barely correlated with PC1.\n\nA potential hypothesis would be that as we move farther away from the river, the concentration of Mn\nincreases with depth.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheavymetals_pca$rotation[, 1:2]\n#>              PC1         PC2\n#> Cd5   0.26720624  0.08778802\n#> Cd20  0.22392129 -0.32389630\n#> Cr5   0.26244938  0.13211704\n#> Cr20  0.26172408 -0.15414563\n#> Cu5   0.27742726  0.03099257\n#> Cu20  0.27837188 -0.12633948\n#> Fe5   0.24752720  0.30864106\n#> Fe20  0.25426152  0.10817270\n#> Mn5   0.05295412  0.58384522\n#> Mn20 -0.15735932  0.49103123\n#> Ni5   0.23967596  0.30017207\n#> Ni20  0.26890893  0.06795434\n#> Pb5   0.27211702  0.03660204\n#> Pb20  0.27863288 -0.11559441\n#> Zn5   0.27807226  0.01288582\n#> Zn20  0.27271722 -0.17524279\n```\n:::\n\n\n</details>\n\n##### 3. Calculate the loadings and scores of the PCA using the SVD (function `svd`). Verify that the loadings and scores obtained using the SVD approach are equal to those obtained using the `prcomp` function. {.unnumbered}\n\n<details>\n\n<summary> Solution </summary>\n\nFirst perform the SVD. Remember to **center and scale** the data matrix!\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheavymetals_scaled <- scale(heavymetals_mx)\nheavymetals_svd <- svd(heavymetals_scaled)\n```\n:::\n\n\nNow compare the PC loadings with the right singular vectors $\\mathbf{V}$ and the scores with the\nprojections $\\mathbf{Z_k} = \\mathbf{XV_k}$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n## Remove dimnames for comparison\nall.equal(unname(heavymetals_pca$rotation), heavymetals_svd$v)\n#> [1] TRUE\n\n## Calculate projections\nheavymetals_Zk <- heavymetals_scaled %*% heavymetals_svd$v\nheavymetals_scores <- unname(heavymetals_pca$x)\n\nall.equal(heavymetals_Zk, heavymetals_scores)\n#> [1] TRUE\n```\n:::\n\n\nThis again shows that PCA is nothing more than an SVD on the (centered and scaled) data matrix!\n\n</details>\n\n## Employment by industry in European countries\n\nUsing the same data as in [Lab\n1](./Lab1-Intro-SVD.html#32_Exercise:_employment_by_industry_in_European_countries).\n\n### Data prep {.unnumbered}\n\nThe `\"industries\"` dataset contains data on the distribution of employment between 9 industrial\nsectors, in 26 European countries. The dataset stems from the Cold-War era; the data are expressed\nas percentages. Load the data and explore its contents.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n## Load 'industries' data from the HDDAData package\ndata(\"industries\")\n\n# Explore contents\nindustries\n#>           country agriculture mining manufacturing power.supply construction\n#> 1         Belgium         3.3    0.9          27.6          0.9          8.2\n#> 2         Denmark         9.2    0.1          21.8          0.6          8.3\n#> 3          France        10.8    0.8          27.5          0.9          8.9\n#> 4      W. Germany         6.7    1.3          35.8          0.9          7.3\n#> 5         Ireland        23.2    1.0          20.7          1.3          7.5\n#> 6           Italy        15.9    0.6          27.6          0.5         10.0\n#> 7      Luxembourg         7.7    3.1          30.8          0.8          9.2\n#> 8     Netherlands         6.3    0.1          22.5          1.0          9.9\n#> 9              UK         2.7    1.4          30.2          1.4          6.9\n#> 10        Austria        12.7    1.1          30.2          1.4          9.0\n#> 11        Finland        13.0    0.4          25.9          1.3          7.4\n#> 12         Greece        41.4    0.6          17.6          0.6          8.1\n#> 13         Norway         9.0    0.5          22.4          0.8          8.6\n#> 14       Portugal        27.8    0.3          24.5          0.6          8.4\n#> 15          Spain        22.9    0.8          28.5          0.7         11.5\n#> 16         Sweden         6.1    0.4          25.9          0.8          7.2\n#> 17    Switzerland         7.7    0.2          37.8          0.8          9.5\n#> 18         Turkey        66.8    0.7           7.9          0.1          2.8\n#> 19       Bulgaria        23.6    1.9          32.3          0.6          7.9\n#> 20 Czechoslovakia        16.5    2.9          35.5          1.2          8.7\n#> 21     E. Germany         4.2    2.9          41.2          1.3          7.6\n#> 22        Hungary        21.7    3.1          29.6          1.9          8.2\n#> 23         Poland        31.1    2.5          25.7          0.9          8.4\n#> 24        Romania        34.7    2.1          30.1          0.6          8.7\n#> 25           USSR        23.7    1.4          25.8          0.6          9.2\n#> 26     Yugoslavia        48.7    1.5          16.8          1.1          4.9\n#>    services finance social.sector transport\n#> 1      19.1     6.2          26.6       7.2\n#> 2      14.6     6.5          32.2       7.1\n#> 3      16.8     6.0          22.6       5.7\n#> 4      14.4     5.0          22.3       6.1\n#> 5      16.8     2.8          20.8       6.1\n#> 6      18.1     1.6          20.1       5.7\n#> 7      18.5     4.6          19.2       6.2\n#> 8      18.0     6.8          28.5       6.8\n#> 9      16.9     5.7          28.3       6.4\n#> 10     16.8     4.9          16.8       7.0\n#> 11     14.7     5.5          24.3       7.6\n#> 12     11.5     2.4          11.0       6.7\n#> 13     16.9     4.7          27.6       9.4\n#> 14     13.3     2.7          16.7       5.7\n#> 15      9.7     8.5          11.8       5.5\n#> 16     14.4     6.0          32.4       6.8\n#> 17     17.5     5.3          15.4       5.7\n#> 18      5.2     1.1          11.9       3.2\n#> 19      8.0     0.7          18.2       6.7\n#> 20      9.2     0.9          17.9       7.0\n#> 21     11.2     1.2          22.1       8.4\n#> 22      9.4     0.9          17.2       8.0\n#> 23      7.5     0.9          16.1       6.9\n#> 24      5.9     1.3          11.7       5.0\n#> 25      6.1     0.5          23.6       9.3\n#> 26      6.4    11.3           5.3       4.0\nsummary(industries)\n#>       country    agriculture        mining      manufacturing  \n#>  Length   :26   Min.   : 2.70   Min.   :0.100   Min.   : 7.90  \n#>  N.unique :26   1st Qu.: 7.70   1st Qu.:0.525   1st Qu.:23.00  \n#>  N.blank  : 0   Median :14.45   Median :0.950   Median :27.55  \n#>  Min.nchar: 2   Mean   :19.13   Mean   :1.254   Mean   :27.01  \n#>  Max.nchar:14   3rd Qu.:23.68   3rd Qu.:1.800   3rd Qu.:30.20  \n#>                 Max.   :66.80   Max.   :3.100   Max.   :41.20  \n#>   power.supply     construction       services        finance      \n#>  Min.   :0.1000   Min.   : 2.800   Min.   : 5.20   Min.   : 0.500  \n#>  1st Qu.:0.6000   1st Qu.: 7.525   1st Qu.: 9.25   1st Qu.: 1.225  \n#>  Median :0.8500   Median : 8.350   Median :14.40   Median : 4.650  \n#>  Mean   :0.9077   Mean   : 8.165   Mean   :12.96   Mean   : 4.000  \n#>  3rd Qu.:1.1750   3rd Qu.: 8.975   3rd Qu.:16.88   3rd Qu.: 5.925  \n#>  Max.   :1.9000   Max.   :11.500   Max.   :19.10   Max.   :11.300  \n#>  social.sector     transport    \n#>  Min.   : 5.30   Min.   :3.200  \n#>  1st Qu.:16.25   1st Qu.:5.700  \n#>  Median :19.65   Median :6.700  \n#>  Mean   :20.02   Mean   :6.546  \n#>  3rd Qu.:24.12   3rd Qu.:7.075  \n#>  Max.   :32.40   Max.   :9.400\n```\n:::\n\n\n### Tasks {.unnumbered}\n\n##### 1. Perform a PCA. How many PCs would you retain? Explain. {.unnumbered}\n\n<details>\n\n<summary> Solution </summary>\n\nPerform the PCA on the centered and scaled data matrix, after removing the `country` column.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nindustries_pca <- prcomp(industries[, -1], scale. = TRUE)\nsummary(industries_pca)\n#> Importance of components:\n#>                           PC1    PC2    PC3    PC4     PC5    PC6     PC7\n#> Standard deviation     1.8674 1.4595 1.0483 0.9972 0.73703 0.6192 0.47514\n#> Proportion of Variance 0.3875 0.2367 0.1221 0.1105 0.06036 0.0426 0.02508\n#> Cumulative Proportion  0.3875 0.6241 0.7462 0.8568 0.91711 0.9597 0.98480\n#>                           PC8      PC9\n#> Standard deviation     0.3699 0.006755\n#> Proportion of Variance 0.0152 0.000010\n#> Cumulative Proportion  1.0000 1.000000\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n## Calculate total variance by summing the PC variances (sdev's squared)\ntot_var <- sum(industries_pca$sdev^2)\n\n## Create data.frame of the proportion of variance explained by each PC\nindustries_prop_var <- data.frame(\n  PC = 1:ncol(industries_pca$x),\n  var = industries_pca$sdev^2\n) |>\n  ## Using `mutate` to calculate prop. var and cum. prop. var\n  mutate(\n    prop_var = var / tot_var,\n    cum_prop_var = cumsum(var / tot_var)\n  )\n\nindustries_prop_var\n#>   PC          var     prop_var cum_prop_var\n#> 1  1 3.4871512725 3.874613e-01    0.3874613\n#> 2  2 2.1301731410 2.366859e-01    0.6241472\n#> 3  3 1.0989576113 1.221064e-01    0.7462536\n#> 4  4 0.9944829778 1.104981e-01    0.8567517\n#> 5  5 0.5432177255 6.035753e-02    0.9171092\n#> 6  6 0.3834276658 4.260307e-02    0.9597123\n#> 7  7 0.2257540553 2.508378e-02    0.9847960\n#> 8  8 0.1367899257 1.519888e-02    0.9999949\n#> 9  9 0.0000456251 5.069456e-06    1.0000000\n\n## Plot the proportion of variance explained by each PC\nggplot(industries_prop_var, aes(PC, prop_var)) +\n  geom_point() +\n  geom_line() +\n  geom_vline(xintercept = 5.5, col = \"firebrick\") +\n  scale_x_continuous(breaks = 1:ncol(industries_pca$x)) +\n  labs(y = \"Proportion of variance\") +\n  ggtitle(\"Proportion of variance explained by each PC\",\n          subtitle = \"Industries data\")\n```\n\n::: {.cell-output-display}\n![](Lab2-PCA_files/figure-html/industries-pca-screeplot-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n\n## Plot the cumulative proportion of variance explained by each PC\nggplot(industries_prop_var, aes(PC, cum_prop_var)) +\n  geom_point() +\n  geom_line() +\n  geom_vline(xintercept = 5.5, col = \"firebrick\") +\n  scale_x_continuous(breaks = 1:ncol(industries_pca$x)) +\n  labs(y = \"Proportion of variance\") +\n  ggtitle(\"Cumulative proportion of variance explained by each PC\",\n          subtitle = \"Industries data\")\n```\n\n::: {.cell-output-display}\n![](Lab2-PCA_files/figure-html/industries-pca-screeplot-2.png){fig-align='center' width=100%}\n:::\n:::\n\n\nIn this case, retaining the first 5-7 PCs would be more appropriate.\n\n</details>\n\n##### 2. What could you say about e.g. Denmark based on the biplot? {.unnumbered}\n\n<details>\n\n<summary> Solution </summary>\n\nConstruct the biplot. We don't really have a grouping variable to color the points, but we can add\nlabels with the country names.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nindustries_biplot <- ggbiplot(industries_pca,\n  labels = industries$country, labels.size = 2\n) +\n  ggtitle(\"Biplot for the industries PCA\") +\n  xlim(c(-3.4, 3.4)) +\n  ylim(c(-2.2, 2.2))\nindustries_biplot\n```\n\n::: {.cell-output-display}\n![](Lab2-PCA_files/figure-html/industries-pca-biplot-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nThe biplot shows how the work forces of the countries are distributed among the different\nindustries.\n\nThe employment in Denmark seems to be mainly concentrated in the finance, services and social\nsectors.\n\n</details>\n\n##### 3. Try to interpret the first 2 PCs. {.unnumbered}\n\n<details>\n\n<summary> Solution </summary>\n\nWe can use the biplot and loadings to interpret the PCs. The biplot is given above, while the\nloadings can be accessed from the `$rotation` slot:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nindustries_pca$rotation[, 1:2]\n#>                        PC1         PC2\n#> agriculture    0.523790989  0.05359389\n#> mining         0.001323458  0.61780714\n#> manufacturing -0.347495131  0.35505360\n#> power.supply  -0.255716182  0.26109606\n#> construction  -0.325179319  0.05128845\n#> services      -0.378919663 -0.35017206\n#> finance       -0.074373583 -0.45369785\n#> social.sector -0.387408806 -0.22152120\n#> transport     -0.366822713  0.20259185\n```\n:::\n\n\nThe first PC seems to be largely driven by the *agriculture* industry, i.e. it is separating\ncountries mostly based on their employment in agriculture () Thus, countries situated on the\npositive side of PC1 will likely have a *higher-than-average* employment in agriculture. On the\nother hand, countries on the negative side of PC1 are less agriculture-based economies and have\nhigher employments in e.g. the social sector.\n\nIndeed, if we rank the countries by their agriculture employment, we largely recover the order of\nthe countries along PC1, with Turkey clearly being the most agriculture-focused (remember that this\ndata is from the Cold War era)!\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n## Show ranking of agriculture industry\nindustries |>\n  dplyr::select(country, agriculture, social.sector, mining, finance) |>\n  arrange(desc(agriculture))\n#>           country agriculture social.sector mining finance\n#> 1          Turkey        66.8          11.9    0.7     1.1\n#> 2      Yugoslavia        48.7           5.3    1.5    11.3\n#> 3          Greece        41.4          11.0    0.6     2.4\n#> 4         Romania        34.7          11.7    2.1     1.3\n#> 5          Poland        31.1          16.1    2.5     0.9\n#> 6        Portugal        27.8          16.7    0.3     2.7\n#> 7            USSR        23.7          23.6    1.4     0.5\n#> 8        Bulgaria        23.6          18.2    1.9     0.7\n#> 9         Ireland        23.2          20.8    1.0     2.8\n#> 10          Spain        22.9          11.8    0.8     8.5\n#> 11        Hungary        21.7          17.2    3.1     0.9\n#> 12 Czechoslovakia        16.5          17.9    2.9     0.9\n#> 13          Italy        15.9          20.1    0.6     1.6\n#> 14        Finland        13.0          24.3    0.4     5.5\n#> 15        Austria        12.7          16.8    1.1     4.9\n#> 16         France        10.8          22.6    0.8     6.0\n#> 17        Denmark         9.2          32.2    0.1     6.5\n#> 18         Norway         9.0          27.6    0.5     4.7\n#> 19     Luxembourg         7.7          19.2    3.1     4.6\n#> 20    Switzerland         7.7          15.4    0.2     5.3\n#> 21     W. Germany         6.7          22.3    1.3     5.0\n#> 22    Netherlands         6.3          28.5    0.1     6.8\n#> 23         Sweden         6.1          32.4    0.4     6.0\n#> 24     E. Germany         4.2          22.1    2.9     1.2\n#> 25        Belgium         3.3          26.6    0.9     6.2\n#> 26             UK         2.7          28.3    1.4     5.7\n```\n:::\n\n\nWe could say that the first PC separates agriculture-based economies from non-agriculture-based. The\nfact that most other industries are negatively correlated with the first PC, seems to indicate that\ncountries either have a large agriculture industry or distribute their work force more equally among\nthe other industries.\n\nThe 2 main exceptions are the mining and finance industries, which are (almost) perpendicular to\nPC1.\n\nThe second PC is mostly driven by the difference between more services-based (on the negative side)\nand more industry-based (positive PC) economies. With the main drivers being the *mining* and\n*finance* sectors.\n\nKeep in mind however that these 2 PCs \"only\" explain 38.7% and 23.7% of the total variance,\nrespectively. So there are likely still many patterns we are missing.\n\n</details>\n\n\n#### **Extra**: the average country {.unnumbered}\n\nWhere would a country with average employment across all industries lie on the biplot?\n\n<details>\n\n<summary> Solution </summary>\n\nFirst calculate the \"average\" country by computing the means of each variable\nin the `industries` data. But remember, we **centered and scaled** the data\nbefore calculating the PCA (through the `center = TRUE` and `scale. = TRUE`\narguments in `prcomp`). So we have to do the same procedure with our new country.\nOf course, subtracting the averages from the average country results in all 0's.\nSo we can represent our average country by a vector of 0's for each feature.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\navg_country <- rep(0, ncol(industries) - 1) # -1 for the 'country' column\n```\n:::\n\n\nNext, we project our new country on to the PCA space, using\n\n$$ Z = XV_{k}$$\n\nwhere $V$ are the PC *loadings* (or right singular vectors in SVD terms) and $k$\nare the chosen number of dimensions (2 in this case).\n\nOf course, since $X$ here consists entirely of zeros, the resulting projection\nwill also be 0 everywhere, and you can see why the average country will lie in\nthe center of the biplot!\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(avg_country_pc <- avg_country %*% industries_pca$rotation)\n#>      PC1 PC2 PC3 PC4 PC5 PC6 PC7 PC8 PC9\n#> [1,]   0   0   0   0   0   0   0   0   0\n## Reformat a bit to make it consistent with the data in the biplot\navg_country_biplot <- data.frame(\n  xvar = avg_country_pc[, \"PC1\"],\n  yvar = avg_country_pc[, \"PC2\"],\n  labels = \"AVERAGE\", row.names = NULL\n)\n\n## Add the average country to the biplot\nindustries_biplot +\n  geom_point(\n    data = avg_country_biplot, size = 3,\n    shape = 23, fill = \"dodgerblue\"\n  ) +\n  geom_label_repel(\n    data = avg_country_biplot, aes(label = labels),\n    nudge_x = 1, nudge_y = 0.5, size = 4,\n    color = \"dodgerblue\"\n  ) + labs(subtitle = \"Average country highlighted\")\n```\n\n::: {.cell-output-display}\n![](Lab2-PCA_files/figure-html/unnamed-chunk-14-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n</details>\n\n\n# Further reading\n\nHere are some further resources that can help with the interpretation of the PCA and its link with\nthe SVD:\n\n-   <https://setosa.io/ev/principal-component-analysis/>\n-   <https://stats.stackexchange.com/a/134283/264768>\n-   <https://twitter.com/allison_horst/status/1288904459490213888?s=20>\n\n<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">...that looks like this. I get to see them pretend to be whale sharks, we talk a bit about how to get as many krill as possible in the fewest passes you&#39;re gonna tilt your face, then we get into PCA. <a href=\"https://t.co/8P0NZk7elO\">pic.twitter.com/8P0NZk7elO</a></p>&mdash; Allison Horst (@allison_horst) <a href=\"https://twitter.com/allison_horst/status/1288904464527572992?ref_src=twsrc%5Etfw\">July 30, 2020</a></blockquote> <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>\n\n\n\n# Session info {-}\n\n<details><summary>Session info</summary>\n\n\n::: {.cell layout-align=\"center\"}\n\n```\n#> [1] \"2026-09-16 09:41:06 CEST\"\n#> ─ Session info ───────────────────────────────────────────────────────────────\n#>  setting  value\n#>  version  R version 4.6.1 (2026-06-24)\n#>  os       macOS Tahoe 26.1\n#>  system   aarch64, darwin23\n#>  ui       X11\n#>  language (EN)\n#>  collate  nl_BE.UTF-8\n#>  ctype    nl_BE.UTF-8\n#>  tz       Europe/Brussels\n#>  date     2026-09-16\n#>  pandoc   3.10.2 @ /opt/homebrew/bin/ (via rmarkdown)\n#>  quarto   1.9.37 @ /usr/local/bin/quarto\n#> \n#> ─ Packages ───────────────────────────────────────────────────────────────────\n#>  package      * version   date (UTC) lib source\n#>  cli            3.6.6     2026-04-09 [1] CRAN (R 4.6.0)\n#>  digest         0.6.39    2025-11-19 [1] CRAN (R 4.6.0)\n#>  dplyr        * 1.2.1     2026-04-03 [1] CRAN (R 4.6.0)\n#>  evaluate       1.0.5     2025-08-27 [1] CRAN (R 4.6.0)\n#>  farver         2.1.2     2024-05-13 [1] CRAN (R 4.6.0)\n#>  fastmap        1.2.0     2024-05-15 [1] CRAN (R 4.6.0)\n#>  forcats      * 1.0.1     2025-09-25 [1] CRAN (R 4.6.0)\n#>  generics       0.1.4     2025-05-09 [1] CRAN (R 4.6.0)\n#>  ggbiplot     * 0.6.2     2024-01-08 [1] CRAN (R 4.6.0)\n#>  ggplot2      * 4.0.3     2026-04-22 [1] CRAN (R 4.6.0)\n#>  ggrepel      * 0.9.8     2026-03-17 [1] CRAN (R 4.6.0)\n#>  glue           1.8.1     2026-04-17 [1] CRAN (R 4.6.0)\n#>  gtable         0.3.6     2024-10-25 [1] CRAN (R 4.6.0)\n#>  HDDAData     * 1.0.1     2026-09-15 [1] Github (statOmics/HDDAData@b832c71)\n#>  hms            1.1.4     2025-10-17 [1] CRAN (R 4.6.0)\n#>  htmltools      0.5.9     2025-12-04 [1] CRAN (R 4.6.0)\n#>  htmlwidgets    1.6.4     2023-12-06 [1] CRAN (R 4.6.0)\n#>  jsonlite       2.0.0     2025-03-27 [1] CRAN (R 4.6.0)\n#>  knitr          1.51      2025-12-20 [1] CRAN (R 4.6.0)\n#>  labeling       0.4.3     2023-08-29 [1] CRAN (R 4.6.0)\n#>  lifecycle      1.0.5     2026-01-08 [1] CRAN (R 4.6.0)\n#>  lubridate    * 1.9.5     2026-02-04 [1] CRAN (R 4.6.0)\n#>  magrittr       2.0.5     2026-04-04 [1] CRAN (R 4.6.0)\n#>  otel           0.2.0     2025-08-29 [1] CRAN (R 4.6.0)\n#>  pillar         1.11.1    2025-09-17 [1] CRAN (R 4.6.0)\n#>  pkgconfig      2.0.3     2019-09-22 [1] CRAN (R 4.6.0)\n#>  purrr        * 1.2.2     2026-04-10 [1] CRAN (R 4.6.0)\n#>  R6             2.6.1     2025-02-15 [1] CRAN (R 4.6.0)\n#>  RColorBrewer   1.1-3     2022-04-03 [1] CRAN (R 4.6.0)\n#>  Rcpp           1.1.1-1.1 2026-04-24 [1] CRAN (R 4.6.0)\n#>  readr        * 2.2.0     2026-02-19 [1] CRAN (R 4.6.0)\n#>  rlang          1.2.0     2026-04-06 [1] CRAN (R 4.6.0)\n#>  rmarkdown      2.31      2026-03-26 [1] CRAN (R 4.6.0)\n#>  S7             0.2.2     2026-04-22 [1] CRAN (R 4.6.0)\n#>  scales         1.4.0     2025-04-24 [1] CRAN (R 4.6.0)\n#>  sessioninfo    1.2.4     2026-06-04 [1] CRAN (R 4.6.0)\n#>  stringi        1.8.7     2025-03-27 [1] CRAN (R 4.6.0)\n#>  stringr      * 1.6.0     2025-11-04 [1] CRAN (R 4.6.0)\n#>  tibble       * 3.3.1     2026-01-11 [1] CRAN (R 4.6.0)\n#>  tidyr        * 1.3.2     2025-12-19 [1] CRAN (R 4.6.0)\n#>  tidyselect     1.2.1     2024-03-11 [1] CRAN (R 4.6.0)\n#>  tidyverse    * 2.0.0     2023-02-22 [1] CRAN (R 4.6.0)\n#>  timechange     0.4.0     2026-01-29 [1] CRAN (R 4.6.0)\n#>  tzdb           0.5.0     2025-03-15 [1] CRAN (R 4.6.0)\n#>  vctrs          0.7.3     2026-04-11 [1] CRAN (R 4.6.0)\n#>  withr          3.0.3     2026-06-19 [1] CRAN (R 4.6.0)\n#>  xfun           0.59      2026-06-19 [1] CRAN (R 4.6.0)\n#>  yaml           2.3.12    2025-12-10 [1] CRAN (R 4.6.0)\n#> \n#>  [1] /Library/Frameworks/R.framework/Versions/4.6/Resources/library\n#>  * ── Packages attached to the search path.\n#> \n#> ──────────────────────────────────────────────────────────────────────────────\n```\n:::\n\n\n</details>\n",
    "supporting": [
      "Lab2-PCA_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}