{
  "hash": "1e7fdebcae61f9f1b71f5fd415d7695f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 6: Large Scale Inference\"\nsubtitle: \"High Dimensional Data Analysis practicals\"\nauthor: \"Adapted by Milan Malfait and Leo Fuhrhop\"\ndate: \"21 Feb 2022 <br/> (Last updated: 2025-11-26)\"\nreferences:\n- id: alon1999broad\n  type: article-journal\n  author:\n  - family: Alon\n    given: Uri\n  - family: Barkai\n    given: Naama\n  - family: Notterman\n    given: Daniel A\n  - family: Gish\n    given: Kurt\n  - family: Ybarra\n    given: Suzanne\n  - family: Mack\n    given: Daniel\n  - family: Levine\n    given: Arnold J\n  issued:\n  - year: 1999\n  title: Broad patterns of gene expression revealed by clustering analysis of tumor\n    and normal colon tissues probed by oligonucleotide arrays\n  container-title: Proceedings of the National Academy of Sciences\n  publisher: National Acad Sciences\n  page: 6745-6750\n  volume: '96'\n  issue: '12'\nformat:\n  html: default\n---\n\n\n\n### [Change log](https://github.com/statOmics/HDDA/commits/master/Lab6-Large-Scale-Inference.Rmd) {-}\n\n***\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n## install packages with:\n# if (!requireNamespace(\"remotes\", quietly = TRUE)) {\n#     install.packages(\"remotes\")\n# }\n# remotes::install_github(\"statOmics/HDDAData\")\n\nlibrary(HDDAData)\n```\n:::\n\n\n# Introduction\n\n**In this lab session we will look at the following topics**\n\n  - FWER\n  - FDR\n  - Multiple testing problem in a real dataset\n\n\n## Testing many hypotheses {#testing-hypotheses}\n\nTo demonstrate the ideas we will be working with, we will simulate artificial data.\nNote that since we are doing simulations, we can control everything and also know\nexactly what the underlying \"true\" distribution is (sometimes also called the \"ground truth\").\nHowever, keep in mind that this is an unlikely representation of real-world data.\n\nIn particular, we will simulate data for multiple hypothesis tests where\n__the null hypothesis is always true__. This means that for the $i$-th test, if we let\n$\\mu_{1i}$ and $\\mu_{2i}$ represent the means of the two populations of interest,\nthe null hypothesis for comparing the two means is\n$H_{0i} : \\mu_{1i} = \\mu_{2i}$. Let the alternative hypothesis of this test be\n$H_{1i} : \\mu_{1i} \\neq \\mu_{2i}$, i.e., we perform a *two-tailed* test.\nSuppose we have data collected from both populations, given by $X_{1i}$ and $X_{2i}$\nof size $n_{1i}$ and $n_{2i}$, respectively, and assume that both populations\nhave the same known variance $\\sigma_i^2$. Then we can test this hypothesis by using a\n__Z-test statistic__, given by\n\n$$ Z_i=\\frac{\\bar X_{1i}-\\bar X_{2i}}{\\sigma_i\\sqrt{1/n_{1i}+1/n_{2i}}} \\, .$$\n\nUnder the null hypothesis, the scores will be distributed as a *standard normal*\n$Z_i\\sim N(0,1)$. The null hypothesis is rejected in favor of the alternative if\n$z_i < \\phi_{\\alpha_i/2}$ or $z_i > \\phi_{1-\\alpha_i/2}$, or equivalently if\n$|z_i| > \\phi_{1-\\alpha_i/2}$, where $\\phi_{\\alpha_i/2}$ is the $\\alpha_i/2$th\nquantile of the standard normal distribution.\n\nIn a multiple hypothesis testing setting, we will perform $m$ tests using the\nsame test statistic. If the *null* were true for all hypotheses, we would end up\nwith a sample $z_1,\\ldots,z_m$ from a standard normal distribution.\n\nIn this setting, we can only make one type of error: wrongly rejecting the null\nhypothesis, i.e. a __type 1 error__. The probability of making this error is given\nby\n\n$$ \\alpha_i=\\text{P}\\{\\text{ reject } H_{0i} | H_{0i}\\} $$\n\n(the $| H_{0i}$ part should be read as \"given that the null hypothesis is true\").\n\nIf we now perform $m_0$ such tests (using the 0 subscript to denote that they\nare all hypotheses for which the *null* is true), we can summarise the possible\noutcomes as in the table below:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|         |Accept H_0        |Reject H_0         |Total |\n|:--------|:-----------------|:------------------|:-----|\n|H_0 True |U (True Negative) |V (False Positive) |m_0   |\n\n\n:::\n:::\n\n\n\nHere, $U$ and $V$ represent the total number of true negative and false positive\nresults we get, respectively, out of $m_0$ total tests.\n\nAs an example, let's simulate the scenario above. In the code below, the `replicate`\nfunction is used to repeat the same procedure a number of times.\nEssentially, the following steps are performed :\n\n1. Sample $N = 50$ observations for 2 hypothetical groups from normal distributions\n   with the same mean and known variance.\n2. Calculate Z-test statistics based on the 2 group means.\n3. Repeat steps 1 to 2 `m0` times.\n\nThis mimics performing `m0` hypothesis tests on data for which we know the null\nhypothesis is true.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Set parameters for the simulation\nN <- 50 # samples per group\nm0 <- 1000 # number of hypothesis tests\nmu_1 <- 3 # true mean group 1\nmu_2 <- 3 # true mean group 2\nsigma <- 1 # known variance\ndenom <- sigma * sqrt(2 / N) # denominator for Z-scores\n\nset.seed(987654321) # seed for reproducibility\nz_stats <- replicate(m0, {\n  group1 <- rnorm(N, mean = mu_1, sd = sqrt(sigma))\n  group2 <- rnorm(N, mean = mu_2, sd = sqrt(sigma))\n\n  # Calculate Z-test statistic\n  (mean(group2) - mean(group1)) / denom\n})\n\n# Visualize Z-test statistics\nhist(z_stats, breaks = 50, freq = FALSE, main = \"Z-test statistics under H_0\")\n# Overlay theoretical standard normal\nlines(x <- seq(-5, 5, length.out = 100), dnorm(x), col = \"dodgerblue\", lwd = 3)\n# Draw vertical lines at 2.5 and 97.5th percentiles\nabline(v = qnorm(c(0.025, 0.975)), col = \"firebrick\", lty = 2, lwd = 3)\n```\n\n::: {.cell-output-display}\n![](Lab6-Large-Scale-Inference_files/figure-html/unnamed-chunk-2-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nWe see that the Z-test statistics nicely follow a standard normal distribution.\nThe vertical dashed lines indicate the 2.5th and 97.5th percentiles of the standard\nnormal. The regions outside these lines indicate the Z-scores that we would call\nsignificant if we used a cut-off of $\\alpha = 0.05$ for a *two-tailed* test.\nSo, even though we simulated data under the null hypothesis, our Z-test still\nreturns \"significant\" results for a number of cases just by chance!\n\nLet's calculate the p-values for our hypothesis tests and see what the damage is.\nTo calculate the p-values, we use the `pnorm()` function in this case, which returns\nthe value of the standard normal CDF (i.e. `pnorm(x)` = $P(Z < x)$). Since we consider\na two-tailed test, we take the absolute values of the Z-scores and set the `lower.tail`\nargument in `pnorm` to `FALSE` (by default it's `TRUE`), so that we get\n`pnorm(abs(x), lower.tail = FALSE)` = $P(Z > |x|)$ and multiply this value by 2.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnull_pvals <- 2 * pnorm(abs(z_stats), lower.tail = FALSE)\nalpha <- 0.05\n\nhist(null_pvals, breaks = seq(0, 1, by = 0.05))\nabline(v = alpha, col = \"firebrick\", lwd = 3)\n```\n\n::: {.cell-output-display}\n![](Lab6-Large-Scale-Inference_files/figure-html/unnamed-chunk-3-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n\ncalled <- (null_pvals < alpha)\n\n# V = number of false positives, in this case: all significant tests\n(V <- sum(called))\n#> [1] 51\nmean(called) # V / m0\n#> [1] 0.051\n```\n:::\n\n\nSo we get 51 significant tests (false positives) out of a total of 1000, which is,\nunsurprisingly, approximately equal to our significance cutoff $\\alpha$.\nNote also that the p-values are uniformly distributed under the null hypothesis by definition.\n\nIf we had carried out only a few tests (say 10) it would be very unlikely to observe\na false positive (on average: 0.05 * 10 = 0.5 false positives) at $\\alpha = 0.05$,\nbut since now we're carrying out so many, we're almost guaranteed to get false positives.\nThis is what is known as the __multiple hypothesis testing problem__.\n\nNote that in real-world data the quantities $U$ and $V$ are *unknown* (because\nwe don't know the truth; if we did, we wouldn't have to carry out any hypothesis\ntests in the first place). However, by using simulated data, we do know the truth\nand so we can explore these quantities.\n\n\n## The family-wise error rate\n\nIf we carry out many tests, we're almost guaranteed to get type I errors, just by\nchance. Therefore the type I error rate is no longer a relevant metric.\nInstead, we consider the __Familywise Error Rate (FWER)__, given by\n\n$$\n\\text{FWER}=\\text{P}\\{V > 0\\}\n  = \\text{P}\\{\\text{rejecting at least one } H_{0i}| H_0\\}\n$$\n\nwhere $H_0$ is the intersection of all  partial nulls ($H_{0i}$) $i=1,\\ldots,m_0$.\nIn general, we would prefer testing procedures that keep the FWER under control,\ni.e. correct for the multiplicity problem.\nSo instead of choosing $\\alpha$ to control the probability of getting a false positive\nin each test, we try to control the FWER, i.e. the probability of getting\n*at least* one false positive in our *set* of hypothesis tests.\n\nIn the following exercises, we will explore this idea on some synthetic data. We will\nsimulate performing hypothesis tests for which the null distribution is always true\nfor different values of `m0`.\n\nTo simplify the code, we will directly sample the Z-test statistics from\na standard normal (instead of sampling the individual groups and then performing\nthe test on them, as shown above). We can also skip the p-value calculation and\ncompare our Z-test statistics directly to the $(1 - \\alpha) / 2$th quantile of the standard\nnormal distribution (using the `qnorm()` function).\n\n\n### Tasks {-}\n\n#### 1. Set `m0 = 5` and generate `m0` Z-test statistics by sampling from the standard normal distribution. Check which ones are significant using a cutoff `alpha = 0.05` {-}\n\n#### 2. Calculate $V$, the number of significant tests. {-}\n\n#### 3. Check whether `V > 0` (at least one significant) and store the result in a variable. {-}\n\n#### 4. Repeat steps 1-3 1000 times and keep track of the result in step 3 by storing it in a vector. {-}\n\n#### 5. Now compute the FWER as the proportion of times $V$ was greater than 0. {-}\n\n#### 6. Repeat the same procedure for `m0 = 50` and `m0 = 1000`. Interpret the results. {-}\n\n<details><summary>Solution</summary>\n\nTo avoid repeated code, the simulations over the different values of `m_0` are combined into one code block. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Repeat 1000 times for m0 = 5, 50 and 1000\nset.seed(987654321)\nB <- 1000 # number of simulations\nm0_vec <- c(5, 50, 1000)\nalpha <- 0.05\n# Initialize empty vector to store FWER results\nfwer <- numeric(length = length(m0_vec))\nnames(fwer) <- paste(\"m0 =\", m0_vec)\n\n# Loop over m0 values and simulate test statistics\nfor (i in seq_along(m0_vec)) {\n  # Simulate B times, each time recording V > 0\n  at_least_one_signif <- replicate(B, {\n    null_stats <- rnorm(m0_vec[i], mean = 0, sd = 1) # simulate z-test\n    significant_tests <- abs(null_stats) > qnorm(1 - alpha / 2)\n    sum(significant_tests) > 0\n  })\n  fwer[i] <- mean(at_least_one_signif) # proportion of V >= 1\n}\nfwer\n#>    m0 = 5   m0 = 50 m0 = 1000 \n#>     0.235     0.925     1.000\n```\n:::\n\n\n</details>\n\n# Controlling the FWER\n\nWe saw in the previous exercises that when conducting a large number of hypothesis\ntests the FWER becomes unacceptably large. So what can we do to lower it?\nThe most straightforward way would be to just lower $\\alpha$ (so we get less false positives).\n\nUnder the null hypothesis (so the p-values are uniformly distributed), we can write the FWER\nfor $m$ independent tests as\n\n$$\n\\begin{align}\n\\text{FWER} = P(\\text{at least one rejection}) &= 1 - P(\\text{no rejections}) \\\\\n  &= 1 - \\prod_{i=1}^{m} P(p_i > \\alpha) \\\\\n  &= 1 - \\prod_{i=1}^{m} (1 - \\alpha) \\\\\n  &= 1 - (1 - \\alpha)^{m} \\, ,\n\\end{align}\n$$\n\nwhere $p_i$ is the p-value for the $i$-th test.\n\nŠidák's correction solves the above equation at a given FWER level (e.g., 0.05)\nfor $\\alpha$ to control the FWER using \n\n$$ \\alpha = 1 - (1 - \\text{FWER})^{1/m} \\, .$$\n\nWithout assuming independent tests, the Bonferroni correction uses that\n\n$$\n\\begin{align}\n\\text{FWER} &= P(\\text{at least one rejection}) \\\\\n  &= P(\\cup_{i=1}^m \\{ p_i \\le \\alpha \\}) \\\\\n  &\\le \\sum_{i=1}^{m} P(p_i \\le \\alpha) \\\\\n  &= m \\alpha \\, ,\n\\end{align}\n$$\n\nwhere the inequality follows from the union bound, and solves the equation\nat a given FWER level (e.g., 0.05) for $\\alpha$ to control the FWER with \n\n$$ \\alpha = \\frac{\\text{FWER}}{m} \\, .$$\n\n### Tasks {-}\n\n#### 1. Determine the `alpha` for Šidák's correction at `m0 = 5`, `m0 = 50` and `m0 = 1000`. Use these values to repeat the simulation from the previous exercise, and confirm that the FWER is controlled at 0.05. {-}\n\n<details><summary>Solution</summary>\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Repeat 1000 times for m0 = 5, 50 and 1000\nset.seed(987654321)\nB <- 1000 # number of simulations\nm0_vec <- c(5, 50, 1000)\nalpha_vec <- 1 - (1 - 0.05)^(1 / m0_vec)\nalpha_vec\n#> [1] 1.020622e-02 1.025340e-03 5.129198e-05\n# Initialize empty vector to store FWER results\nfwer <- numeric(length = length(m0_vec))\nnames(fwer) <- paste(\"m0 =\", m0_vec)\n\n# Loop over m0 values and simulate test statistics\nfor (i in seq_along(m0_vec)) {\n  # Simulate B times, each time recording V > 0\n  at_least_one_signif <- replicate(B, {\n    null_stats <- rnorm(m0_vec[i], mean = 0, sd = 1) # simulate z-test\n    significant_tests <- abs(null_stats) > qnorm(1 - alpha_vec[i] / 2)\n    sum(significant_tests) > 0\n  })\n  fwer[i] <- mean(at_least_one_signif) # proportion of V >= 1\n}\nfwer\n#>    m0 = 5   m0 = 50 m0 = 1000 \n#>     0.040     0.053     0.045\n```\n:::\n\n\n</details>\n\n#### 2. Determine the `alpha` for the Bonferroni correction and repeat the simulation one more time. How do the results compare to Šidák's correction? {-}\n\n<details><summary>Solution</summary>\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Repeat 1000 times for m0 = 5, 50 and 1000\nset.seed(987654321)\nB <- 1000 # number of simulations\nm0_vec <- c(5, 50, 1000)\nalpha_vec <- 0.05 / m0_vec\nalpha_vec\n#> [1] 1e-02 1e-03 5e-05\n# Initialize empty vector to store FWER results\nfwer <- numeric(length = length(m0_vec))\nnames(fwer) <- paste(\"m0 =\", m0_vec)\n\n# Loop over m0 values and simulate test statistics\nfor (i in seq_along(m0_vec)) {\n  # Simulate B times, each time recording V > 0\n  at_least_one_signif <- replicate(B, {\n    null_stats <- rnorm(m0_vec[i], mean = 0, sd = 1) # simulate z-test\n    significant_tests <- abs(null_stats) > qnorm(1 - alpha_vec[i] / 2)\n    sum(significant_tests) > 0\n  })\n  fwer[i] <- mean(at_least_one_signif) # proportion of V >= 1\n}\nfwer\n#>    m0 = 5   m0 = 50 m0 = 1000 \n#>     0.039     0.051     0.045\n```\n:::\n\n\n</details>\n\nIn general, controlling the FWER at levels such as 0.05 with Šidák's correction\nor the Bonferroni correction is very conservative, i.e., if there were true alternatives\n(which we did not consider in the simulations), we might miss them.\n\n\n# The False Discovery Rate (FDR)\n\nNow let's consider a situation where we have both true null and true alternative\ncases. In this situation we are prone to two types of errors: false positives\n(type 1, as in the previous case) and false negatives (type 2, i.e. accepting\n$H_0$ while it's actually false).\n\nWe can then extend the table from [before](#testing-hypotheses):\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|         |Accept H_0         |Reject H_0         |Total |\n|:--------|:------------------|:------------------|:-----|\n|H_0 True |U (True Negative)  |V (False Positive) |m_0   |\n|H_1 True |T (False Negative) |S (True Positive)  |m_1   |\n|Total    |W                  |R                  |m     |\n\n\n:::\n:::\n\n\nIn addition to the FWER, another important quantity in multiple hypothesis\ntesting is the __False Discovery Rate (FDR)__:\n\n$$\n\\text{FDR} = E[\\frac{V}{R}] \\, ,\n$$\n\nwhich is the expected proportion of false positives among all positive tests.\nThe ratio $V/R$ is also called the False Discovery Proportion (FDP).\n\nHowever, the only quantities from the table above that are observable\nin real data are $W$, $R$ and $m$. So to illustrate the concept, we will again\nmake use of simulated data.\n\nIn the code below, 1.000 tests are simulated, for which 90% come from cases\nwhere the null is true and the other 10% for which the alternative is true.\nWe assume the *effect size* (difference between the 2 groups) to be equal to 3\nunder the alternative, so that we can sample the test statistics from a normal\ndistribution with mean 3.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm <- 1000 # total number of hypotheses\np0 <- 0.9 # 90% of cases are true null\nm0 <- round(p0 * m)\nm1 <- round((1 - p0) * m)\n\nset.seed(987654321)\nalpha <- 0.05\nnull_stats <- rnorm(m0)\nalt_stats <- rnorm(m1, mean = 3)\nnull_tests <- abs(null_stats) > qnorm(1 - alpha / 2)\nalt_tests <- abs(alt_stats) > qnorm(1 - alpha / 2)\n\n(U <- sum(!null_tests)) # true negatives\n#> [1] 854\n(V <- sum(null_tests)) # false positives\n#> [1] 46\n(S <- sum(alt_tests)) # true positives\n#> [1] 84\n(T <- sum(!alt_tests)) # false negatives\n#> [1] 16\n\nR <- V + S # total number of positives\n\n(FDP <- V / R)\n#> [1] 0.3538462\n```\n:::\n\n\nWe see that 35.38% of the positive cases are actually false positives.\nTo get an idea of the FDR, the expected FDP, we will repeat this procedure a\nnumber of times in the following exercises.\n\n### Tasks {-}\n\n#### 1. Set `m0 = 90` and `m1 = 10` and generate `m = 100` test statistics, `m0` of them from the standard normal distribution $N(0, 1)$ (null distribution) and m1 of them from $N(3, 1)$ (the alternative distribution). {-}\n\n\n#### 2. Test for significance at `alpha = 0.05` by comparing the test statistics to the standard normal, for both sets of tests. {-}\n\n\n#### 3. Calculate the FDP. {-}\n\n\n#### 4. Repeat steps 1-3 1000 times and keep track of the FDP for each iteration. Then estimate the FDR as the mean of the FDPs. Interpret the results. {-}\n\n<details><summary>Solution</summary>\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(987654321)\nB <- 1000 # number of simulations\nm0 <- 90\nm1 <- 10\nalpha <- 0.05\n\n# Simulate B times, each time recording V > 0\nFDP <- replicate(B, {\n  null_stats <- rnorm(m0, mean = 0)\n  alt_stats <- rnorm(m1, mean = 3)\n  null_tests <- abs(null_stats) > qnorm(1 - alpha / 2)\n  alt_tests <- abs(alt_stats) > qnorm(1 - alpha / 2)\n  V <- sum(null_tests) # false positives\n  S <- sum(alt_tests) # true positives\n  R <- V + S\n  # Return V / R\n  if (R == 0) 0 else V / R\n})\n\n(FDR <- mean(FDP))\n#> [1] 0.3304283\n```\n:::\n\n\nThe FDR tells us the expected proportion of positive tests that will be false\npositives.\n\n</details>\n\nAs with the FWER, we can now think of methods to control the FDR. A very popular\nmethod that is widely used in large-scale inference for high-throughput\nsequencing data is the __Benjamini-Hochberg correction__. It *adjusts* the\np-values such that the FDR is controlled at a certain level. Note that this can\nequivalently be formulated as adjusting the significance cut-off $\\alpha$, similarly\nto how we defined the FWER-controlling techniques.\n\n### Tasks {-}\n\n#### 1. Adjust the simulation code from the previous task to estimate the FDR under the Benjamini-Hochberg correction. {-}\nHint: Calculate p-values of the simulated null and alternative test statistics. Concatenate all p-values into a single vector and apply the Benjamini-Hochberg correction using `p.adjust` with `method = \"BH\"`. Compare the resulting adjusted p-values to $\\alpha$ to estimate the FDP and FDR.\n\n<details><summary>Solution</summary>\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(987654321)\nB <- 1000 # number of simulations\nm0 <- 90\nm1 <- 10\nalpha <- 0.05\n\n# Simulate B times, each time recording V > 0\nFDP <- replicate(B, {\n  null_stats <- rnorm(m0, mean = 0)\n  alt_stats <- rnorm(m1, mean = 3)\n  p_null <- (2 * pnorm(-abs(null_stats)))\n  p_alt <- (2 * pnorm(-abs(alt_stats)))\n  p_adj <- p.adjust(c(p_null, p_alt), method = \"BH\")\n  V <- sum(p_adj[1:m0] <= alpha) # false positives\n  S <- sum(p_adj[(m0 + 1):(m0 + m1)] <= alpha) # true positives\n  R <- V + S\n  # Return V / R\n  if (R == 0) 0 else V / R\n})\n\n(FDR <- mean(FDP))\n#> [1] 0.04071404\n```\n:::\n\n\n</details>\n\n#### 2. Repeat the simulation using `method = \"bonferroni\"`. Compare the resulting FDR and interpret. {-}\nNote: The Bonferroni correction can either be formulated as adjusting the significance cut-off to $\\alpha / m$ or, equivalently, as a p-value correction that multiplies each p-value by $m$. \n\n<details><summary>Solution</summary>\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(987654321)\nB <- 1000 # number of simulations\nm0 <- 90\nm1 <- 10\nalpha <- 0.05\n\n# Simulate B times, each time recording V > 0\nFDP <- replicate(B, {\n  null_stats <- rnorm(m0, mean = 0)\n  alt_stats <- rnorm(m1, mean = 3)\n  p_null <- (2 * pnorm(-abs(null_stats)))\n  p_alt <- (2 * pnorm(-abs(alt_stats)))\n  p_adj <- p.adjust(c(p_null, p_alt), method = \"bonferroni\")\n  V <- sum(p_adj[1:m0] <= alpha) # false positives\n  S <- sum(p_adj[(m0 + 1):(m0 + m1)] <= alpha) # true positives\n  R <- V + S\n  # Return V / R\n  if (R == 0) 0 else V / R\n})\n\n(FDR <- mean(FDP))\n#> [1] 0.0106\n```\n:::\n\n\n__Interpretation__: Both the Bonferroni correction and the Benjamini-Hochberg correction control the FDR at the desired level $\\alpha$.\nHowever, the Bonferroni correction is more conservative, resulting in an FDR that is much lower than $\\alpha$. This means that the Bonferroni method results in a larger number of false negatives and could possibly lead to us missing interesting discoveries.\n\n</details>\n\n# Multiple testing on the data by Alon *et al.* (1999)\n\nWe will take another look at the dataset by @alon1999broad on gene expression\nlevels in 40 tumour and 22 normal colon tissue samples.\nWe previously used this data in [Lab 4](./Lab4-Sparse-PCA-LDA.html).\nThis time, we are interested in finding genes that are expressed *significantly*\ndifferent between the tumor and normal samples. In other words, we will perform\nhypothesis tests for each of the __2000 genes__. This is clearly a multiple\ntesting problem.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndata(\"Alon1999\")\nstr(Alon1999[, 1:10]) # first 10 columns\n#> 'data.frame':\t62 obs. of  10 variables:\n#>  $ Y : chr  \"t\" \"n\" \"t\" \"n\" ...\n#>  $ X1: num  8589 9164 3826 6246 3230 ...\n#>  $ X2: num  5468 6720 6970 7824 3694 ...\n#>  $ X3: num  4263 4883 5370 5956 3401 ...\n#>  $ X4: num  4065 3718 4706 3976 3464 ...\n#>  $ X5: num  1998 2015 1167 2003 2181 ...\n#>  $ X6: num  5282 5570 1572 2131 2923 ...\n#>  $ X7: num  2170 3849 1325 1531 2069 ...\n#>  $ X8: num  2773 2793 1472 1715 2949 ...\n#>  $ X9: num  7526 7018 3297 3870 3303 ...\ntable(Alon1999$Y)  # contingency table of tissue types\n#> \n#>  n  t \n#> 22 40\n```\n:::\n\n\nAs a reminder, the data consists of gene expression levels in 40 tumor and 22\nnormal colon tissue samples. The expression on 6500 human genes were measured\nusing the Affymetrix oligonucleotide array.\nAs in @alon1999broad, we use the *2000 genes with the highest minimal intensity*\nacross the samples.\n\nThe dataset contains one variable named `Y` with the values `t` and `n`.\nThis variable indicates whether the sample came from tumourous (`t`) or\nnormal (`n`) tissue.\n\n### Tasks {-}\n\n#### 1. Perform two-sample t-tests for each gene, comparing the tumor and normal tissue groups. Store the p-values and test statistics. {-}\n\nHint: The `t.test()` function computes a two-sample t-test with *unequal variances* ([Welch's t-test][Welch]) by default. The return object contains the elements `p.value` and `statistic`.\n\n<details><summary>Solution</summary>\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Split gene data and grouping variable and convert to matrix\ngene_data <- as.matrix(Alon1999[, -1])\ngroup <- Alon1999$Y\n\n# Use `apply` to perform t-tests over all columns\nt_test_results <- t(apply(gene_data, 2, function(x) {\n  t_test <- t.test(x ~ group)\n  p_val <- t_test$p.value\n  stat <- t_test$statistic\n  c(stat, \"p_val\" = p_val)\n}))\n\nhead(t_test_results)\n#>             t      p_val\n#> X1 -1.6728613 0.10068961\n#> X2 -1.4319967 0.15787615\n#> X3 -2.1292624 0.03758201\n#> X4 -0.9455604 0.34869002\n#> X5 -1.7852252 0.07953894\n#> X6 -1.4214810 0.16143092\n```\n:::\n\n\n</details>\n\n#### 2. Plot a histogram of the p-values and interpret. {-}\n\n<details><summary>Solution</summary>\n\nSetting `breaks` from 0 to 1 with a width of 0.05 makes sense for p-values because\nthe first bar will then represent the number of p-values smaller than 0.05 (which\nwe often use as cutoff).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np_vals <- t_test_results[, \"p_val\"]\nhist(\n  p_vals,\n  breaks = seq(0, 1, by = 0.05), main = \"\", xlab = \"p-value\",\n  ylim = c(0, 500)\n)\n```\n\n::: {.cell-output-display}\n![](Lab6-Large-Scale-Inference_files/figure-html/p_val-hist-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n__Interpretation__: The histogram appears close to a uniform distribution for the larger p-values, but has a lot more small p-values than would be expected under a uniform distribution.\nRecall that if the null hypothesis (the gene expression is the same for tumor and normal tissue) were to hold for all genes, the p-values would be uniformly distributed on $[0, 1]$.\n\n</details>\n\n#### 3. How many discoveries / significant genes do you find when using $\\alpha = 0.05$? {-}\n\n<details><summary>Solution</summary>\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nalpha <- 0.05\nsum(p_vals <= alpha)\n#> [1] 478\n```\n:::\n\n\n</details>\n\n#### 4. Control the FWER at 5% using Šidák's correction. How many genes are significant after the correction? {-}\n\n<details><summary>Solution</summary>\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm <- nrow(t_test_results)\nfwer <- 0.05\nadj_alpha <- 1 - (1 - fwer)^(1 / m)\n\n# Number of significant discoveries\nsum(p_vals <= adj_alpha)\n#> [1] 11\n```\n:::\n\n\nBy rearranging the equation $$ \\alpha = 1 - (1 - \\text{FWER})^{1/m} \\, ,$$\nwe can equivalently adjust the p-values via\n$$1 - (1 - p)^m$$\nand compare them to the cut-off 5\\%:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsidak_p_vals <- 1 - (1 - p_vals)^m\n\n# Number of significant discoveries\nsum(sidak_p_vals <= fwer)\n#> [1] 11\n```\n:::\n\n\n</details>\n\n#### 5. Control the FWER at 5% using the Bonferroni correction. How many genes are significant after the correction? {-}\n\n<details><summary>Solution</summary>\n\nBy adjusting $\\alpha$:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nadj_alpha <- fwer / m\n\n# Number of significant discoveries\nsum(p_vals <= adj_alpha)\n#> [1] 11\n```\n:::\n\n\nOr equivalently, by adjusting the p-values:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbonferroni_p_vals <- p.adjust(p_vals, method = \"bonferroni\")\n\n# Number of significant discoveries\nsum(bonferroni_p_vals <= fwer)\n#> [1] 11\n```\n:::\n\n\n</details>\n\n#### 6. Control the FDR at 5% using the Benjamini-Hochberg method. How many genes are significant after the correction? {-}\n\n<details><summary>Solution</summary>\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbh_p_vals <- p.adjust(p_vals, method = \"BH\")\n\nsum(bh_p_vals < 0.05)\n#> [1] 190\n```\n:::\n\n\n</details>\n\n#### 7. Plot the adjusted p-values from the Benjamini-Hochberg method against the original p-values. What is the effect of the adjustment? {-}\nBonus: Compute the adjusted p-values based on Šidák's correction and the Bonferroni correction. Add them to the plot and compare.\n\n<details><summary>Solution</summary>\n\nVisualize the adjusted p-values for all three methods in the same figure:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncols <- c(\"#9d05f4\", \"#ecd033\", \"#01d9d9\")\n\nplot(\n  p_vals[order(p_vals)], bh_p_vals[order(p_vals)],\n  pch = 19, cex = 0.6, xlab = \"p-value\",\n  ylab = \"Adjusted p-value\", col = cols[1]\n)\npoints(\n  p_vals[order(p_vals)], bonferroni_p_vals[order(p_vals)],\n  pch = 19, cex = 0.6, col = cols[2]\n)\npoints(\n  p_vals[order(p_vals)], sidak_p_vals[order(p_vals)],\n  pch = 19, cex = 0.6, col = cols[3]\n)\nabline(a = 0, b = 1)\nlegend(\"bottomright\",\n  c(\"Benjamini-Hochberg\", \"Bonferroni\", \"Sidak\"),\n  col = cols, pch = 19\n)\n```\n\n::: {.cell-output-display}\n![](Lab6-Large-Scale-Inference_files/figure-html/fdr-adjust-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n__Interpretation__: All three methods adjust the p-values upwards to account for multiple testing. The adjustment is more pronounced for small p-values, while for higher p-values, the curves of the adjusted p-values flatten out. \nThe Benjamini-Hochberg method at a FDR of 5% is less conservative compared to the other two methods. Both Šidák's correction and the Bonferroni correction at an FWER of 5% adjust the majority of p-values to exactly 1 and only a small proportion of p-values that are originally close to zero remains smaller than 1.\n\n</details>\n\n# Further reading {-}\n\n- Chapter 6 of the [Biomedical Data Science](http://genomicsclass.github.io/book/) book\n\n[Welch]:https://en.wikipedia.org/wiki/Welch%27s_t-test\n\n\n# Session info {-}\n\n<details><summary>Session info</summary>\n\n\n::: {.cell layout-align=\"center\"}\n\n```\n#> [1] \"2026-09-16 09:43:33 CEST\"\n#> ─ Session info ───────────────────────────────────────────────────────────────\n#>  setting  value\n#>  version  R version 4.6.1 (2026-06-24)\n#>  os       macOS Tahoe 26.1\n#>  system   aarch64, darwin23\n#>  ui       X11\n#>  language (EN)\n#>  collate  nl_BE.UTF-8\n#>  ctype    nl_BE.UTF-8\n#>  tz       Europe/Brussels\n#>  date     2026-09-16\n#>  pandoc   3.10.2 @ /opt/homebrew/bin/ (via rmarkdown)\n#>  quarto   1.9.37 @ /usr/local/bin/quarto\n#> \n#> ─ Packages ───────────────────────────────────────────────────────────────────\n#>  package     * version date (UTC) lib source\n#>  cli           3.6.6   2026-04-09 [1] CRAN (R 4.6.0)\n#>  digest        0.6.39  2025-11-19 [1] CRAN (R 4.6.0)\n#>  evaluate      1.0.5   2025-08-27 [1] CRAN (R 4.6.0)\n#>  fastmap       1.2.0   2024-05-15 [1] CRAN (R 4.6.0)\n#>  HDDAData    * 1.0.1   2026-09-15 [1] Github (statOmics/HDDAData@b832c71)\n#>  htmltools     0.5.9   2025-12-04 [1] CRAN (R 4.6.0)\n#>  htmlwidgets   1.6.4   2023-12-06 [1] CRAN (R 4.6.0)\n#>  jsonlite      2.0.0   2025-03-27 [1] CRAN (R 4.6.0)\n#>  knitr         1.51    2025-12-20 [1] CRAN (R 4.6.0)\n#>  otel          0.2.0   2025-08-29 [1] CRAN (R 4.6.0)\n#>  rlang         1.2.0   2026-04-06 [1] CRAN (R 4.6.0)\n#>  rmarkdown     2.31    2026-03-26 [1] CRAN (R 4.6.0)\n#>  sessioninfo   1.2.4   2026-06-04 [1] CRAN (R 4.6.0)\n#>  xfun          0.59    2026-06-19 [1] CRAN (R 4.6.0)\n#>  yaml          2.3.12  2025-12-10 [1] CRAN (R 4.6.0)\n#> \n#>  [1] /Library/Frameworks/R.framework/Versions/4.6/Resources/library\n#>  * ── Packages attached to the search path.\n#> \n#> ──────────────────────────────────────────────────────────────────────────────\n```\n:::\n\n\n</details>\n\n# References {-}\n",
    "supporting": [
      "Lab6-Large-Scale-Inference_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}